### ISSUE TITLE
Invalid type for `newval` block parameter in Hash#merge

### ISSUE THREAD

**Issue by hatstand** [sorbet/sorbet#3798] opened 2020-12-15 16:56 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Aa%20%3D%20T.let(%7B%7D%2C%20T%3A%3AHash%5BString%2C%20Integer%5D)%0Ab%20%3D%20T.let(%7B%7D%2C%20T%3A%3AHash%5BString%2C%20Float%5D)%0A%0Aa.merge(b)%20do%20%7Ckey%2C%20oldval%2C%20newval%7C%0A%20%20T.reveal_type(newval)%0Aend)

```ruby
# typed: strict
extend T::Sig

a = T.let({}, T::Hash[String, Integer])
b = T.let({}, T::Hash[String, Float])

a.merge(b) do |key, oldval, newval|
  T.reveal_type(newval)
end
```

#### Observed output

```
editor.rb:8: Revealed type: <top> https://srb.help/7014
     8 |  T.reveal_type(newval)
          ^^^^^^^^^^^^^^^^^^^^^
  From:
    editor.rb:7:
     7 |a.merge(b) do |key, oldval, newval|
                                    ^^^^^^
Errors: 1
```

#### Expected behavior

`newval` should be inferred as `Float` here but instead becomes `<top>`.

**Comment by jez** [comment] 2020-12-15 17:06
dupe of #1098

**Closed by jez** 2020-12-15 17:06 UTC
Labels: bug, unconfirmed
