### ISSUE TITLE
Incorrect control flow short-circuiting when using &&

### ISSUE THREAD

**Issue by orangethunder** [sorbet/sorbet#2462] opened 2020-01-13 09:05 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Adef%20main%0A%20%20a%20%3D%201%0A%20%20b%20%3D%202%0A%0A%20%20if%20a%20%26%26%20b%0A%20%20end%0Aend)

```ruby
# typed: true
def main
  a = 1
  b = 2

  if a && b
  end
end
```

#### Observed output

```
editor.rb:6: This code is unreachable https://srb.help/7006
     6 |  if a && b
             ^
Errors: 1
```

#### Expected behavior

Expected this to type-check successfully. Note that trivially replacing `a && b` with just `a` satisfies the type-checker, which is an inconsistency. Titled my ticket as to a hunch about the cause, not sure if there's a different cause.

**Comment by aisamanra** [comment] 2020-01-13 18:32
This is a duplicate of #820. What's actually happening here is that
```ruby
a && b
```
gets internally desugared to something like
```ruby
$tmp = a
if $tmp
  b
else
  $tmp  # this is actually what is being flagged as unreachable
end
```

in order to emulate short-circuiting behavior. In this case, because `a` has the type `Integer`, Sorbet knows that it will always be "truth-ey", which means it'll always end up evaluating the `b` branch. The fact that an error is raised is itself sensible: if the `a` in `a && b` is always truth-ey, then you can always replace the whole expression with `b` instead. The problem here is that the error is phrased in a confusing way, which is the issue described in #820.

It's worth noting that Sorbet uses type information to compute flow-sensitivity: if the LHS has a type which might actually be "false-ey"—for example, if you replace `a = 1` with `a = T.let(1, T.nilable(Integer))` so that Sorbet believes that `a` has a type which _might_ not always be truth-ey—then Sorbet won't flag an error, c.f. [here](https://sorbet.run/#%23%20typed%3A%20true%0Adef%20main%0A%20%20a%20%3D%20T.let(1%2C%20T.nilable(Integer))%0A%20%20b%20%3D%202%0A%0A%20%20if%20a%20%26%26%20b%0A%20%20end%0Aend).

**Closed by aisamanra** 2020-01-13 18:32 UTC
Labels: bug, unconfirmed

**Comment by orangethunder** [comment] 2020-01-14 02:53
Like I said, replacing `a && b` with just `a` satisfies the type-checker, which is an inconsistency. If it's desired behaviour for the type-checker to disallow `a && b` then it should also disallow `a`, since, building on your reasoning, it can always be replaced with no `if` statement at all.

**Comment by orangethunder** [comment] 2020-01-14 03:11
Forgot to thank you for the detailed explanation, and I'm +1 on a better error message for this.
