### ISSUE TITLE
`srb init` tries to read temporary files and fails

### ISSUE THREAD

**Issue by samirph** [sorbet/sorbet#2425] opened 2020-01-05 21:41 UTC
#### Input
Ran `bundle exec srb init`

#### Observed output
The command fails, so not all gems get their .rbi files and no .rb file gets the typing magic comment.

![image](https://user-images.githubusercontent.com/4563904/71786486-91038080-2fea-11ea-87c3-738f63336736.png)

#### Expected behavior

`srb init` runs successfully and creates .rbi files and add the magic comments to all files.

Maybe we could set to `srb init` ignore some folders? It doesn't seem to respect and `exclude` option in `sorbet/config`

**Comment by ptarjan** [comment] 2020-01-06 19:10
Can you include the contents of the file that is printed in the last error message? That has the info you want in it

**Comment by samirph** [comment] 2020-01-07 22:32
This is the exact content of the file

```
/tmp/d20200107-17743-2rgxsn/reflection.rbi:8: unexpected token kEND https://srb.help/2001
     8 |end
        ^^^

/tmp/d20200107-17743-2rgxsn/reflection.rbi:16: unexpected token tNL https://srb.help/2001
    16 |  sig {returns(::T.untyped)}
    17 |  def to_param(); end

/tmp/d20200107-17743-2rgxsn/reflection.rbi:26: unexpected token kEND https://srb.help/2001
    26 |end
        ^^^

/tmp/d20200107-17743-2rgxsn/reflection.rbi:624006: unexpected token tIDENTIFIER https://srb.help/2001
      624006 |  include ::RecipientType
                ^^^^^^^

/tmp/d20200107-17743-2rgxsn/reflection.rbi:629088: unexpected token tIDENTIFIER https://srb.help/2001
      629088 |  include ::Uidable
                ^^^^^^^

/tmp/d20200107-17743-2rgxsn/reflection.rbi:630874: unexpected token tIDENTIFIER https://srb.help/2001
      630874 |  include ::Uidable

```

**Comment by ptarjan** [comment] 2020-01-07 22:55
so it looks like `/tmp/d20200107-17743-2rgxsn/reflection.rbi:8` is weird. What is around line 8 of that? It seems to not be real ruby.

**Comment by samirph** [comment] 2020-01-09 00:42
Pretty sure this is generated by Sorbet. There is no reflection file in the project or reflection gem in `Gemfile.lock`. This happens when Sorbet is creating the `.rbi` files.

**Comment by ptarjan** [comment] 2020-01-09 01:46
Correct. You want to look at `/tmp/d20200107-17743-2rgxsn/reflection.rbi`
and see why Sorbet is making unparsable stuff. Maybe one of your classes
has a unicode character in it or something?

**Comment by samirph** [comment] 2020-01-09 12:19
Here is the beginning of `reflection.rbi`. I don't know why it would generate a module name with a `#` in the beginning. Any ideas?

```ruby
# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi update

# typed: true

module #<Module:0x0000556c37f74a60>::GenerateSequenceuid
  # Skipping `extend Sorbet::Private::GemGeneratorTracepoint::Tracer::ModuleOverride` because it is an invalid name
end

module #<Module:0x0000556c3e939108>::Sluggableuid
  # Skipping `extend Sorbet::Private::GemGeneratorTracepoint::Tracer::ModuleOverride` because it is an invalid name
  sig {returns(::T.untyped)}
  def to_param(); end

  sig do
    params(
      base: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def self.included(base); end
end
```

**Comment by ptarjan** [comment] 2020-01-09 16:41
Ok. Great. I think you want to find the code in sorbet that emits those
classes and skip them if they are invalid names similar to how the other
line prints `because it is an invalid name`.

**Comment by orangethunder** [comment] 2020-01-11 12:21
I'm experiencing a similar issue when running `srb rbi hidden-definitions`, and it's strange because it worked fine for the past few days but started happening yesterday. Here's the contents of the `reflection.json.err` file:

/tmp/d20200111-4296-5b1nun/reflection.rbi:539982: unexpected token $end https://srb.help/2001
      539982 |    params(
                    ^`

And here's lines 539973 to 539979 of `reflection.rbi`:

`  sig do
    params(
      _: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def self.[](*_); end`

There doesn't seem to be any syntax issue in the above, but running the ruby interpreter over the entire file does give error "unexpected end-of-input, expecting keyword_end" at the last line of the file.

I guess the next step would be tracking down exactly where the missing end could be, but I currently have no ideas on how to track it down in such a massive file. Perhaps it would help if I did some debug mode that dumped things to separate files instead of a single reflection.rbi? Then I could run the ruby interpreter on all of them and easily pick up which one has invalid syntax.

**Comment by orangethunder** [comment] 2020-01-11 12:51
Was easy to track down the issue by doing a `RubyVM::InstructionSequence.compile data` in the loop in `Sorbet::Private::HiddenMethodFinder#gen_source_rbi`. The issue seems to be caused by some other code I submitted a PR for, so will fix that up. In other words, please ignore my comment.

**Comment by samirph** [comment] 2020-01-11 19:24
> Ok. Great. I think you want to find the code in sorbet that emits those classes and skip them if they are invalid names similar to how the other line prints `because it is an invalid name`.

I'm not sure how to debug this.


I would go for this line, since it only checks if it is a `Class` and if it's not, then it just sets it as a module

`ret << (Sorbet::Private::RealStdlib.real_is_a?(klass, Class) ? "class #{class_name}#{superclass_str}\n" : "module #{class_name}\n")`


`gems/sorbet/lib/serialize.rb` line 57

**Comment by samirph** [comment] 2020-10-17 18:47
I found out that the issue happens when creating a .rbi file for a class with lots of metaprogramming. 
I don't think I can share the code though

**Comment by samirph** [comment] 2020-10-17 18:56
Here are the modules generated:
```ruby
module #<Module:0x0000560107e08f90>::GenerateSequenceuid
  # Skipping `extend Sorbet::Private::GemGeneratorTracepoint::Tracer::ModuleOverride` because it is an invalid name
end                                              
                                                                                                                   
module #<Module:0x0000560107f7da88>::GenerateSequenceuid
  # Skipping `extend Sorbet::Private::GemGeneratorTracepoint::Tracer::ModuleOverride` because it is an invalid name
end                                              
                              
module #<Module:0x0000560108273058>::Sluggableuid
```

And so on...
This happens because of module declarations inside the class such as
```ruby
module Sluggable#{uid_name}
```

**Comment by samirph** [comment] 2020-10-17 19:07
First lines of the class that raises this issue:

```ruby

module Uidable
  def self.included(base)
    base.extend ClassMethods
  end
  module ClassMethods
     ....
```

**Comment by jez** [comment] 2022-07-27 20:55
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca

**Closed by jez** 2022-07-27 20:55 UTC
Labels: bug, unconfirmed, srb
