### ISSUE TITLE
Surprising error when assigning value to local variable when declared in different conditional 

### ISSUE THREAD

**Issue by jvilk-stripe** [sorbet/sorbet#5398] opened 2022-03-02 17:37 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/?arg=--print=cfg-text#%23%20typed%3A%20true%0A%0A%23%20Imagine%20this%20situation%20with%20a%20setup%20where%20I%20can't%20easily%20initialize%0A%23%20str%20outside%20of%20the%20conditional%20with%20a%20value%20of%20its%20type.%0Aif%205%20%2B%205%20%3E%2010%0A%20%20str%20%3D%20T.let%28%22%22%2C%20String%29%0Aelse%0A%20%20str%20%3D%20%22%22%0Aend)

```ruby
# typed: true

# Imagine this situation with a setup where I can't easily initialize
# str outside of the conditional with a value of its type.
if 5 + 5 > 10
  str = T.let("", String)
else
  str = ""
end
```

#### Observed output

```
method ::<Class:<root>>#<static-init> {

bb0[rubyRegionId=0, firstDead=-1]():
    <self>: T.class_of(<root>) = cast(<self>: NilClass, T.class_of(<root>));
    <statTemp>$5: Integer(5) = 5
    <statTemp>$6: Integer(5) = 5
    <statTemp>$4: Integer = <statTemp>$5: Integer(5).+(<statTemp>$6: Integer(5))
    <statTemp>$7: Integer(10) = 10
    <ifTemp>$3: T::Boolean = <statTemp>$4: Integer.>(<statTemp>$7: Integer(10))
    <ifTemp>$3 -> (T::Boolean ? bb2 : bb3)

# backedges
# - bb4(rubyRegionId=0)
bb1[rubyRegionId=0, firstDead=-1]():
    <unconditional> -> bb1

# backedges
# - bb0(rubyRegionId=0)
bb2[rubyRegionId=0, firstDead=-1]():
    <cfgAlias>$10: T.class_of(Sorbet::Private::Static) = alias <C Static>
    <cfgAlias>$12: T.class_of(String) = alias <C String>
    <statTemp>$8: Sorbet::Private::Static::Void = <cfgAlias>$10: T.class_of(Sorbet::Private::Static).keep_for_typechecking(<cfgAlias>$12: T.class_of(String))
    <castTemp>$13: String("") = ""
    str: String = cast(<castTemp>$13: String(""), String);
    <returnMethodTemp>$2: String = str
    <unconditional> -> bb4

# backedges
# - bb0(rubyRegionId=0)
bb3[rubyRegionId=0, firstDead=-1]():
    str: NilClass = ""
    <returnMethodTemp>$2: NilClass = str
    <unconditional> -> bb4

# backedges
# - bb2(rubyRegionId=0)
# - bb3(rubyRegionId=0)
bb4[rubyRegionId=0, firstDead=1](<returnMethodTemp>$2: T.nilable(String)):
    <finalReturn>: T.noreturn = return <returnMethodTemp>$2: T.nilable(String)
    <unconditional> -> bb1

}

editor.rb:8: Incompatible assignment to variable declared via let: String("") is not a subtype of NilClass https://srb.help/7001
     8 |  str = ""
                ^^
Errors: 1
```

#### Expected behavior

Sorbet infers the type of `str` to be `String`.

- - -

The workaround is to re-declare `str` in the `else` conditional:

```ruby
str = T.let("", String)
```

**Comment by jez** [comment] 2022-08-06 19:52
Dupe of #649

**Closed by jez** 2022-08-06 19:52 UTC
Labels: bug
