### ISSUE TITLE
Interfaces implemented by attr accessors or T::Structs do no identify signature mismatches

### ISSUE THREAD

**Issue by vinistock** [sorbet/sorbet#4100] opened 2021-03-19 18:31 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20A%3B%20end%0Aclass%20B%3B%20end%0A%0Amodule%20Interface%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20interface!%0A%0A%20%20sig%20%7B%20abstract.returns(A)%20%7D%0A%20%20def%20do_it%3B%20end%0Aend%0A%0Aclass%20ClassImpl%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20Interface%0A%0A%20%20%23%20Error%3A%20Return%20type%20T.nilable(String)%20does%20not%20match%20return%20type%20of%20abstract%20method%20%0A%20%20%23%20Correct!%0A%20%20sig%20%7B%20override.returns(B)%20%7D%0A%20%20def%20do_it%0A%20%20%20%20B.new%0A%20%20end%0Aend%0A%0Aclass%20StructImpl%20%3C%20T%3A%3AStruct%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20Interface%0A%0A%20%20%23%20Does%20not%20identify%20the%20error%0A%20%20%23%20Trying%20to%20add%20sig%20here%20says%20the%20sig%20is%20unused%0A%20%20prop%20%3Ado_it%2C%20B%0Aend%0A%0Aclass%20AttrImpl%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20Interface%0A%0A%20%20sig%20%7B%20void%20%7D%0A%20%20def%20initialize%0A%20%20%20%20%40do_it%20%3D%20T.let(B.new%2C%20B)%0A%20%20end%0A%0A%20%20%23%20Does%20not%20identify%20the%20error%0A%20%20sig%20%7B%20override.returns(B)%20%7D%0A%20%20attr_reader%20%3Ado_it%0Aend%0A)

```ruby
# typed: strict

class A; end
class B; end

module Interface
  extend T::Sig
  extend T::Helpers

  interface!

  sig { abstract.returns(A) }
  def do_it; end
end

class ClassImpl
  extend T::Sig
  include Interface

  # Error: Return type T.nilable(String) does not match return type of abstract method 
  # Correct!
  sig { override.returns(B) }
  def do_it
    B.new
  end
end

class StructImpl < T::Struct
  extend T::Sig
  include Interface

  # Does not identify the error
  # Trying to add sig here says the sig is unused
  prop :do_it, B
end

class AttrImpl
  extend T::Sig
  include Interface

  sig { void }
  def initialize
    @do_it = T.let(B.new, B)
  end

  # Does not identify the error
  sig { override.returns(B) }
  attr_reader :do_it
end
```

#### Observed output

```
editor.rb:23: Return type B does not match return type of abstract method Interface#do_it https://srb.help/5035
    23 |  def do_it
          ^^^^^^^^^
    editor.rb:13: Super method defined here with return type A
    13 |  def do_it; end
          ^^^^^^^^^
Errors: 1
```

#### Expected behavior

The `attr_reader` and the `T::Struct` versions of the implementation should also throw the error `Return type B does not match return type of abstract method` since they are too implementing the interface.

**Comment by jez** [comment] 2022-08-14 02:46
Duplicate of #1841 / #1694

**Closed by jez** 2022-08-14 02:47 UTC
Labels: bug, unconfirmed
