### ISSUE TITLE
Using `T.self_type` in proc params causes generic error 7011

### ISSUE THREAD

**Issue by nicoco007** [sorbet/sorbet#8060] opened 2024-07-30 22:10 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20MyClass%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams%28block%3A%20T.proc.params%28arg0%3A%20T.self_type%29.void%29.void%7D%0A%20%20def%20foo%28%26block%29%0A%20%20%20%20yield%20self%0A%20%20end%0Aend%0A%0Ainst%20%3D%20MyClass.new%0Ainst.foo%20do%20%7Cobj%7C%0Aend)

```ruby
# typed: strict

class MyClass
  extend T::Sig

  sig {params(block: T.proc.params(arg0: T.self_type).void).void}
  def foo(&block)
    yield self
  end
end

inst = MyClass.new
inst.foo do |obj|
end
```

#### Observed output

```
editor.rb:13: Expression does not have a fully-defined type (Did you reference another class's type members?) https://srb.help/7011
    13 |inst.foo do |obj|
    14 |end
  Note:
    Historically, users seeing this error has represented finding a bug in Sorbet
    (or at least finding a test case for which there could be a better error message).
    Consider searching for similar bugs at https://github.com/sorbet/sorbet/issues
    or reporting a new one.

editor.rb:7: Expression does not have a fully-defined type (Did you reference another class's type members?) https://srb.help/7011
     7 |  def foo(&block)
                   ^^^^^
  Note:
    Historically, users seeing this error has represented finding a bug in Sorbet
    (or at least finding a test case for which there could be a better error message).
    Consider searching for similar bugs at https://github.com/sorbet/sorbet/issues
    or reporting a new one.
Errors: 2
```

#### Expected behavior

`obj` should be of type `MyClass`.

- - -

Replacing `T.self_type` with `MyClass` works as expected, but it'd be nice to have this work with `T.self_type` for subclasses.

**Comment by jez** [comment] 2024-07-30 23:05
Duplicate of #5632

**Closed by jez** 2024-07-30 23:05 UTC
Labels: bug, unconfirmed

**Comment by nicoco007** [comment] 2024-07-30 23:16
I'm not sure how I missed that issue or the other one that was closed as duplicate while searching through existing issues. Sorry about that!
