### ISSUE TITLE
Support for "Class whose AttachedClass is bound by some module"

### ISSUE THREAD

**Issue by benbuckman** [sorbet/sorbet#2015] opened 2019-10-24 18:07 UTC
### Problem

I would like to declare a type for a class which includes a mixin. For example:

[→ View on sorbet.run](
https://sorbet.run/#%23%20typed%3A%20strict%0A%0Amodule%20Runnable%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0A%0A%20%20sig%20%7Babstract.void%7D%0A%20%20def%20run%3B%20end%0Aend%0A%0Aclass%20MyScript%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20Runnable%0A%0A%20%20sig%20%7Boverride.void%7D%0A%20%20def%20run%3B%20end%0Aend%0A%0Amodule%20Runner%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(runnable_klass%3A%20Class).void%7D%0A%20%20def%20self.run(runnable_klass)%0A%20%20%20%20runnable_klass.new.run%0A%20%20end%0Aend%0A%0ARunner.run(MyScript))

```rb
# typed: strict

module Runnable
  extend T::Sig
  extend T::Helpers
  interface!

  sig {abstract.void}
  def run; end
end

class MyScript
  extend T::Sig
  include Runnable

  sig {override.void}
  def run; end
end

module Runner
  extend T::Sig

  sig {params(runnable_klass: Class).void}
  def self.run(runnable_klass)
    runnable_klass.new.run
  end
end

Runner.run(MyScript)
```

### Observed output

```
editor.rb:25: Method run does not exist on Object https://srb.help/7003
    25 |    runnable_klass.new.run
            ^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

### Expected behavior

While I was forced to type `runable_klass` as `Class`, I'd like some way to say, "`Class`, but where I know that the attached is bound by `Runnable`".

This is different from `T.class_of(Runnable)`. `T.class_of(Runnable)` refers to the `Runnable` class object itself. The only things that are valid to call on this are `def self.xyz` methods defined within `Runnable`.

**Comment by jez** [comment] 2019-10-25 01:22
The suggested workaround is to use `T.cast` to enforce this at runtime.

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Amodule%20Runnable%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0A%0A%20%20sig%20%7Babstract.void%7D%0A%20%20def%20run%3B%20end%0Aend%0A%0Aclass%20MyScript%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20Runnable%0A%0A%20%20sig%20%7Boverride.void%7D%0A%20%20def%20run%3B%20end%0Aend%0A%0Amodule%20Runner%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(runnable_klass%3A%20Class).void%7D%0A%20%20def%20self.run(runnable_klass)%0A%20%20%20%20T.cast(runnable_klass.new%2C%20Runnable).run%0A%20%20end%0Aend%0A%0ARunner.run(MyScript))

```ruby
# typed: strict

module Runnable
  extend T::Sig
  extend T::Helpers
  interface!

  sig {abstract.void}
  def run; end
end

class MyScript
  extend T::Sig
  include Runnable

  sig {override.void}
  def run; end
end

module Runner
  extend T::Sig

  sig {params(runnable_klass: Class).void}
  def self.run(runnable_klass)
    T.cast(runnable_klass.new, Runnable).run
  end
end

Runner.run(MyScript)
```

**Comment by jez** [comment] 2022-08-06 22:21
This is a duplicate of #62

**Closed by jez** 2022-08-06 22:21 UTC
Labels: enhancement, hard
