### ISSUE TITLE
prefer inherited namespace first (Sorbet-Static)

### ISSUE THREAD

**Issue by md-work** [sorbet/sorbet#2041] opened 2019-10-28 13:51 UTC
Currently Sorbet-Static prefers the global namespace over the inherited namespace. But Ruby works the other way around.

Variant 1: [→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20M%3B%20end%0A%0Aclass%20A%0A%20%20class%20M%3B%20end%0Aend%0A%0Aclass%20B%20%3C%20A%0A%20%20M.new%0Aend)

```ruby
# typed: true

module M; end  # remove to make the error disappear

class A
  class M; end
end

class B < A
  M.new
  # At runtime Ruby uses A::M, so everything is fine.
  # But sorbet-static assumes ::M.
  # Sorbet-Static: Method new does not exist on T.class_of(M) https://srb.help/7003
end
```
&nbsp;

---
&nbsp;

Variant 2: [→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20M%3B%20end%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20class%20M%0A%20%20%20%20def%20foo%3B%20end%0A%20%20end%0Aend%0A%0Aclass%20B%20%3C%20A%0A%20%20sig%20%7Bparams(m%3A%20M).void%7D%0A%20%20def%20bar(m)%0A%20%20%20%20m.foo%0A%20%20end%0Aend)

```ruby
# typed: true

module M; end

class A
  extend T::Sig
  class M
    def foo; end
  end
end

class B < A
  sig {params(m: M).void}
  def bar(m)
    m.foo
    # Sorbet-Static: Method foo does not exist on M https://srb.help/7003
  end
end
```
&nbsp;

---
&nbsp;

Workarounds:
- Explicitly use `A::M`.
- Write `T.unsafe(M).new` (only for variant 1).
- Write `T.untyped` (only variant 2).
&nbsp;

But explicitly using `A::M` isn't the same and it might be a problem if you're managing responsibilities via inheritance.

**Comment by XrXr** [comment] 2019-10-30 22:21
Related: #8

**Comment by jez** [comment] 2020-02-26 00:53
Thanks for those links @XrXr 

I'm going to close this as a dupe of #8.

**Closed by jez** 2020-02-26 00:53 UTC
Labels: bug, unconfirmed
