### ISSUE TITLE
`sorbet rbi hidden-definitions` doesn't read from rbi files

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#1161] opened 2019-07-02 00:42 UTC
#### Input

In the rbi file, `sorbet-rails` defines a custom `Elem` property in "ActiveRecord::Base" like this: 

```ruby
# -- In sorbet-rails/rbi/activerecord.rbi --
class ActiveRecord::Base
  extend ActiveRecord::Querying::Typed
  extend T::Generic
  Elem = type_template(fixed: ActiveRecord::Base)
end
```

We set Elem to be fixed in every individual ActiveRecord::Base subclass
```ruby
# -- In sorbet/rails-rbi/users_role.rbi --

class UsersRole < ApplicationRecord
  extend T::Sig
  extend T::Generic
  extend Site::ModelRelationShared
  extend Site::ClassMethods
  include Site::InstanceMethods
  Elem = type_template(fixed: UsersRole)
end
```

It works with `srb tc`. However, when someone wants to run `srb rbi definitions`. It would raise error like this
```
/tmp/d20190701-14198-dis6ws/reflection.rbi:1347596: Type `Elem` declared by parent `T.class_of(ApplicationRecord)` must be re-declared in `T.class_of(UsersRole)` https://srb.help/5014
     1347596 |class UsersRole < ApplicationRecord
                    ^^^^^^^^^
    /home/dev/sorbet-rails/rbi/activerecord.rbi:149: `Elem` declared in parent here
     149 |  Elem = type_template(fixed: ApplicationRecord)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

It somehow takes into account the rbi from the gem, but not the rbi from the generated model rbi. 

#### Expected behavior

I think it should include information from both and not treat those as issues.

**Comment by manhhung741** [comment] 2019-07-02 00:42
Relevant discussions:
https://sorbet-ruby.slack.com/archives/CJL5B3CEN/p1562023020092300
#1158

**Comment by manhhung741** [comment] 2019-07-02 00:46
Looks like I might be able to remove the `T::Generic` from `ActiveRecord::Base` itself.

**Comment by jez** [comment] 2019-07-02 01:16
@manhhung741 I can't reproduce this in sorbet.run:

https://sorbet.run/#%23%20typed%3A%20true%0A%0A%23%20--%20In%20sorbet-rails%2Frbi%2Factiverecord.rbi%20--%0Aclass%20ActiveRecord%3A%3ABase%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Elem%20%3D%20type_template(fixed%3A%20ActiveRecord%3A%3ABase)%0Aend%0A%0A%23%20--%20In%20sorbet%2Frails-rbi%2Fusers_role.rbi%20--%0A%0Aclass%20UsersRole%20%3C%20ActiveRecord%3A%3ABase%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Elem%20%3D%20type_template(fixed%3A%20UsersRole)%0Aend

Is it possible for you to make a reproducer there? Or alternatively to make a zip file with the minimal files (Gemfile, RBI file, Ruby file) that I could reproduce it locally?

**Comment by manhhung741** [comment] 2019-07-02 01:17
This breaks the subclass of ActiveRecord etc, because they need to override the definition of `Elem`. We do that by autogenerating the class with `Elem` defined. It works with `srb tc` but doesn't work with `srb init` or `srb rbi hidden-definitions`

**Comment by manhhung741** [comment] 2019-07-02 01:20
I'll try to set up some tests in the sample apps we have in `sorbet-rails` and send to you later.

**Comment by manhhung741** [comment] 2019-07-02 01:34
I have a repo for you

https://github.com/manhhung741/rails_app5_2

If you run `srb tc`, there is no problem. If you run `srb rbi hidden-definitions`, it will fail. In the log file you should see the errors I described.

**Comment by manhhung741** [comment] 2019-07-03 21:59
There is also a problem with `srb init` doesn't work when `sorbet-rails` is included in the Gemfile. 
I don't know if there is any work-around for that case. 

People would either have to:
1. Only include `sorbet-rails` after they have run `srb init`
Or
2. Run `sorbet-rails` generation code before `srb init`

**Comment by jez** [comment] 2022-07-27 20:58
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca

**Closed** 2022-07-27 21:00 UTC
Labels: bug, unconfirmed, srb
