### ISSUE TITLE
Redeclaring field with different type in inheritance hierarchy should be forbidden

### ISSUE THREAD

**Issue by varungandhi-src** [sorbet/sorbet#6436] opened 2022-09-28 09:22 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20C%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7B%20void%20%7D%0A%20%20def%20initialize%0A%20%20%20%20%40x%20%3D%20T.let%280%2C%20Integer%29%0A%20%20end%0Aend%0A%0Aclass%20D%20%3C%20C%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7B%20void%20%7D%0A%20%20def%20initialize%0A%20%20%20%20%40x%20%3D%20T.let%28%22%22%2C%20String%29%0A%20%20end%0Aend)

```ruby
# typed: strict

class C
  extend T::Sig
  sig { void }
  def initialize
    @x = T.let(0, Integer)
  end
end

class D < C
  extend T::Sig
  sig { void }
  def initialize
    @x = T.let("", String)
  end
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

This code shouldn't type-check because `String != Integer`.

- - -

Originally flagged in Slack [thread](https://sorbet-ruby.slack.com/archives/CHN2L03NH/p1664338365751229).

**Comment by jez** [comment] 2022-10-02 23:44
Duplicate of #6308

**Closed by jez** 2022-10-02 23:44 UTC
