### ISSUE TITLE
Errata on website

### ISSUE THREAD

**Issue by ukd1** [sorbet/sorbet#4249] opened 2021-06-07 22:53 UTC
#### Input

Visit https://sorbet.org

#### Observed output

```
Sorbet works with your favorite editor to provide IDE features like autocomplete and jump to definition
```

This is from https://github.com/sorbet/sorbet/blob/4f146522e25047f6527a98797672f9b1c462eced/website/pages/en/index.js#L129

#### Expected behavior

Expected behavior is that:
> Sorbet works with your favorite editor to provide IDE features like autocomplete and jump to definition

It doesn't / I can't find the docs or the plugins to make it do so. Currently there are no docs, links, or other projects that are available.

- Related, #1013
- and some links from there about it existing, but being closed source (for now)
  - https://github.com/castwide/solargraph/issues/194#issuecomment-504218711
  - https://twitter.com/darkdimius/status/1141785271958167553

Is it coming soon? If not, could you fix the website to reflect the current state please?

**Comment by jez** [comment] 2021-06-10 18:36
The LSP support is built into Sorbet with the `--lsp` flag. If you have an editor that supports the language server protocol, you can instruct it to launch Sorbet with that flag.

We are working on making this better and in particular publishing a VS Code extension that makes the integration process easier, but we don't have a timeline to commit to for that.

(Closing, as this is not a bug and we do not track our roadmap on GitHub issues.)

**Closed by jez** 2021-06-10 18:36 UTC
Labels: bug, unconfirmed
