### ISSUE TITLE
`T.class_of` should accept type parameters

### ISSUE THREAD

**Issue by basta-stripe** [sorbet/sorbet#4255] opened 2021-06-10 17:31 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters(%3AS)%0A%20%20.params(x%3A%20T.class_of(T.type_parameter(%3AS)))%0A%20%20.returns(T.type_parameter(%3AS))%0Aend%0Adef%20foo(x)%0A%20%20x.new%0Aend%0A)

```ruby
sig do
  type_parameters(:S)
  .params(x: T.class_of(T.type_parameter(:S)))
  .returns(T.type_parameter(:S))
end
def foo(x)
  x.new
end

```

#### Observed output

```
editor.rb:6: T.class_of needs a Class as its argument https://srb.help/5004
     6 |  .params(x: T.class_of(T.type_parameter(:S)))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

I would expect that I can use type parameters with `class_of`. I expect this would require `type_parameters` to have some kind of constraint system ([like TypeScript](https://www.typescriptlang.org/docs/handbook/2/generics.html#generic-constraints)).

**Comment by jez** [comment] 2021-06-10 18:34
This is a dupe of https://github.com/sorbet/sorbet/issues/62. (It is actually quite non-trivial to implement.)

**Closed by jez** 2021-06-10 18:34 UTC
Labels: bug, unconfirmed
