### ISSUE TITLE
Sorbet does not infer type from superclass method call using `super` in sub-class

### ISSUE THREAD

**Issue by amanos1022** [sorbet/sorbet#6938] opened 2023-04-13 16:25 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23typed%3A%20strict%0A%0Aclass%20Parent%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns%28T%3A%3ABoolean%29%7D%0A%20%20def%20is_something%3F%0A%20%20%20%20true%0A%20%20end%0Aend%0A%0Aclass%20Child%20%3C%20Parent%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns%28T%3A%3ABoolean%29%7D%0A%20%20def%20is_something%3F%0A%20%20%20%20super%20%26%26%20is_something_else%3F%0A%20%20end%0A%0A%20%20sig%20%7Breturns%28T%3A%3ABoolean%29%7D%0A%20%20def%20is_something_else%3F%0A%20%20%20%20true%0A%20%20end%0Aend)

```ruby
#typed: strict

class Parent
  extend T::Sig

  sig {returns(T::Boolean)}
  def is_something?
    true
  end
end

class Child < Parent
  extend T::Sig

  sig {returns(T::Boolean)}
  def is_something?
    super && is_something_else?
  end

  sig {returns(T::Boolean)}
  def is_something_else?
    true
  end
end
```

#### Observed output

```
editor.rb:18: Expected T::Boolean but found T.nilable(T::Boolean) for method result type https://srb.help/7005
    18 |  end
          ^^^
  Expected T::Boolean for result type of method is_something?:
    editor.rb:16:
    16 |  def is_something?
          ^^^^^^^^^^^^^^^^^
  Got T.nilable(T::Boolean) originating from:
    editor.rb:17:
    17 |    super && is_something_else?
            ^^^^^
    editor.rb:17:
    17 |    super && is_something_else?
                     ^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

Sorbet should know that the `super` call and `is_something_else?` call both return non-nilable `T::Boolean`s.

- - -

This is similar to issues https://github.com/sorbet/sorbet/issues/373 and https://github.com/sorbet/sorbet/issues/5912 but in those cases return types aren't known. I think this is a legit bug because in this case we explicitly know that the return type for `super`(`Parent#is_something?`) and `Child#is_something_else` are non-nilable booleans.

**Comment by jez** [comment] 2023-04-13 17:07
Dupe of #6828

**Closed by jez** 2023-04-13 17:07 UTC
Labels: bug, unconfirmed
