### ISSUE TITLE
Check overriding of members

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#542] opened 2019-05-16 23:53 UTC
You shouldn't be able to override a method that returns a `String` with one that returns an `Int`.

Said otherwise, recover https://github.com/stripe/sorbet/pull/356

**Comment by jez** [comment] 2020-12-21 22:40
Either fixed, or duplicate of other issues, depending on how you look at it

**Closed by jez** 2020-12-21 22:40 UTC
Labels: enhancement
