### ISSUE TITLE
LSP fails when gems contain a rbi directory  

### ISSUE THREAD

**Issue by donaldong** [sorbet/sorbet#2732] opened 2020-03-02 02:12 UTC
#### Input
With Gemfile:
```
gem 'sorbet'
gem 'sorbet-runtime
gem 'sorbet-coerce', '0.2.3'
```
```
bundle exec srb tc --lsp 
```
#### Observed output

```
Sorbet's language server requires a single input directory.
```
https://github.com/chanzuckerberg/sorbet-coerce/pull/38

#### Expected behavior
No errors.

For people running into the same issue, here is the workaround we currently use:
```
$(bundle show sorbet-static)/libexec/sorbet --lsp
```

**Comment by froydnj** [comment] 2022-01-31 20:08
This is a duplicate of #2496.

**Closed by froydnj** 2022-01-31 20:08 UTC
Labels: bug, IDE
