### ISSUE TITLE
Wrong lowering for type aliases as values

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#2277] opened 2019-12-04 20:17 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0AF%20%3D%20T.type_alias%20do%0A%20%20T.any(Integer%2C%20String)%0Aend%0A%0Adef%20main%0A%20F.new%0Aend)

```ruby
# typed: true
F = T.type_alias do
  T.any(Integer, String)
end

def main
 F.new
end
```

#### Observed output

```
```

#### Expected behavior

Errors statically

- - -

**Comment by DarkDimius** [comment] 2019-12-04 20:19
there's a unclear line between what's allowed to do with types as values and what isn't.
our general stance - you shouldn't use types as values

But some internals of sorbet & other Stripe libraries need to pass them around and call stuff on them

so... it's unclear how many T.unsafe()'s should we expect from them :slightly_smiling_face:

**Comment by jez** [comment] 2020-12-21 22:19
Duplicate of #3335

**Closed by jez** 2020-12-21 22:19 UTC
Labels: enhancement
