### ISSUE TITLE
`T.bind(self, RepeatedClassName)` in dynamic method definition

### ISSUE THREAD

**Issue by sambostock** [sorbet/sorbet#6454] opened 2022-10-04 02:28 UTC
### Problem

Sometimes, it is convenient to generate tests (e.g. when there are many many very similar cases that must all be tested against). In these cases, it is necessary to use `T.bind(self, TheTestClass)`. Consider the following [simplified example](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20MyTest%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20%7B%0A%20%20%20%20%23%20...%0A%20%20%7D.each%20do%20%7Ca%2C%20b%7C%0A%20%20%20%20define_method%28%22test_%23%7Ba%7D_equals_%23%7Bb%7D%22%29%20do%0A%20%20%20%20%20%20T.reveal_type%28self%29%20%20%20%20%23%20Revealed%20type%3A%20T.class_of%28MyTest%29%0A%20%20%20%20%20%20%23%20T.bind%28self%2C%20MyTest%29%20%23%20%F0%9F%91%88%20Fixes%20error%20%F0%9F%91%87%0A%20%20%20%20%20%20assert_equal%28a%2C%20b%29%20%20%20%20%20%23%20%F0%9F%92%A5%20Method%20assert_equal%20does%20not%20exist%20on%20T.class_of%28MyTest%29%0A%20%20%20%20end%0A%20%20end%0A%20%20%0A%20%20private%0A%0A%20%20sig%20%7B%20params%28expected%3A%20Object%2C%20actual%3A%20Object%29.void%20%7D%0A%20%20def%20assert_equal%28expected%2C%20actual%29%0A%20%20%20%20raise%20Exception%2C%20%22%23%7Bexpected%7D%20!%3D%20%23%7Bactual%7D%22%20unless%20expected%20%3D%3D%20actual%0A%20%20end%0Aend):

```ruby
# typed: strict

class MyTest
  extend T::Sig

  {
    # ...
  }.each do |a, b|
    define_method("test_#{a}_equals_#{b}") do
      T.reveal_type(self)    # Revealed type: T.class_of(MyTest)
      # T.bind(self, MyTest) # 👈 Fixes error 👇
      assert_equal(a, b)     # 💥 Method assert_equal does not exist on T.class_of(MyTest)
    end
  end
  
  private

  sig { params(expected: Object, actual: Object).void }
  def assert_equal(expected, actual)
    raise Exception, "#{expected} != #{actual}" unless expected == actual
  end
end
```

This works, but it feels weird to have to repeat the class name.

### Proposed solution

Intuitively, it feels like it should be possible to leverage `T.attached_class`, `T.self_type`, or something else, given that Sorbet thinks that `self` is `T.class_of(MyTest)`

```ruby
    define_method("test_#{a}_equals_#{b}") do
      T.reveal_type(self)            # Revealed type: T.class_of(MyTest)
      T.bind(self, T.attached_class)
      T.reveal_type(self)            # Ideal revealed type: MyTest
      assert_equal(a, b)             # Ideally would now work
    end
```

Currently though, this does not work and results in the following error

```
T.attached_class may only be used in a singleton class method context https://srb.help/5004
|      T.bind(self, T.attached_class)
                    ^^^^^^^^^^^^^^^^
  Note:
    Current context is MyTest, which is an instance class not a singleton class
```

Trying `T.self_type` also doesn't work

```
Expression does not have a fully-defined type (Did you reference another class's type members?) https://srb.help/7011
|      T.bind(self, T.self_type)
       ^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by jez** [comment] 2022-10-04 18:18
Dupe of #64

prototype that doesn't work ongoing in https://github.com/sorbet/sorbet/pull/6181

**Closed by jez** 2022-10-04 18:18 UTC
Labels: enhancement, unconfirmed
