### ISSUE TITLE
Unreachable detection doesn't work with Mutex's 

### ISSUE THREAD

**Issue by zanker-stripe** [sorbet/sorbet#1743] opened 2019-09-10 19:36 UTC
#### Input

https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20MUTEX%20%3D%20Mutex.new%0A%0A%20%20def%20self.test%0A%20%20%20%20return%20true%20if%20%40test%0A%0A%20%20%20%20MUTEX.synchronize%20do%0A%20%20%20%20%20%20return%20true%20if%20%40test%0A%20%20%20%20%20%20%40test%20%3D%20true%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20A.test%0Aend

```ruby
  MUTEX = Mutex.new

  def self.test
    return true if @test

    MUTEX.synchronize do
      return true if @test
      @test = true
    end
  end
```

#### Observed output

```
editor.rb:11: This code is unreachable https://srb.help/7006
    11 |      return true if @test
                     ^^^^
Errors: 1
```

#### Expected behavior

I remember reporting this a while back but I never wrote a ticket for it, so going to do that now to make life easier for tracking! Sometimes it's handy to bypasses mutexes when loading data, mostly in cases where you only care about ensuring an instance variable is set once via a mutex, but after it's set it's fine to bypass the mutex.

Sorbet can't detect that though, since it doesn't treat the `MUTEX.synchronize` call as a possible state change, so you get unreachable code errors.

**Comment by DarkDimius** [comment] 2019-09-12 01:26
duplicate of https://github.com/sorbet/sorbet/issues/42

**Closed by DarkDimius** 2019-09-12 01:26 UTC
Labels: bug, hard

**Comment by zanker-stripe** [comment] 2019-09-12 03:54
Whoops! Sorry about that

**Comment by DarkDimius** [comment] 2019-09-12 04:12
No worries, please continue reporting :-)
