### ISSUE TITLE
Erroneous type error: Incompatible assignment to variable declared via let

### ISSUE THREAD

**Issue by theorygeek** [sorbet/sorbet#3724] opened 2020-11-24 00:56 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aclass%20Field%3B%20end%0A%0Aclass%20Result%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(T.untyped)%7D%0A%20%20def%20foobar%3B%20end%0A%0A%20%20sig%20%7Breturns(T.nilable(T.any(Field%2C%20Integer)))%7D%0A%20%20def%20field%0A%20%20%20%20if%20rand%20%3E%200.5%0A%20%20%20%20%20%20T.let(foobar%5B%22field%22%5D%2C%20Integer)%0A%20%20%20%20else%0A%20%20%20%20%20%20Field.new%0A%20%20%20%20end%0A%20%20end%0Aend%0A)

```ruby
# typed: strict

class Field; end

class Result
  extend T::Sig

  sig {returns(T.untyped)}
  def foobar; end

  sig {returns(T.nilable(T.any(Field, Integer)))}
  def field
    if rand > 0.5
      T.let(foobar["field"], Integer)
    else
      Field.new
    end
  end
end
```

#### Observed output

```
editor.rb:16: Incompatible assignment to variable declared via let: Field is not a subtype of NilClass https://srb.help/7001
    16 |      Field.new
              ^^^^^^^^^
Errors: 1
```

#### Expected behavior

I don't think there should be any errors in this code, both branches of the `if` statement are returning types that comply with the signature.

- - -

**Comment by theorygeek** [comment] 2020-11-24 00:57
(I'm also @ryanfoster-stripe)

**Comment by jez** [comment] 2020-11-24 01:00
Almost verbatim dupe of #649

**Closed by jez** 2020-11-24 01:00 UTC
Labels: bug, unconfirmed
