### ISSUE TITLE
Missing `to_s` in `def without_errors(lines)`

### ISSUE THREAD

**Issue by nickelser** [sorbet/sorbet#2684] opened 2020-02-20 01:00 UTC
#### Input

Massive Rails application, with a 60k line hidden-definitions file. Running `bundle exec srb rbi hidden-definitions`

```
bundle exec srb --version
Sorbet typechecker 0.5.5376 git 60218b9b71ff6a0a210e1882c30c7e3c93ea90e2 built on 2020-02-19 03:51:49 GMT debug_symbols=true
```

#### Observed output

```Traceback (most recent call last):
	12: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/bin/srb-rbi:237:in `<main>'
	11: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/bin/srb-rbi:224:in `main'
	10: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/bin/srb-rbi:232:in `block in make_step'
	 9: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/lib/hidden-definition-finder.rb:38:in `main'
	 8: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/lib/hidden-definition-finder.rb:49:in `main'
	 7: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/lib/hidden-definition-finder.rb:166:in `write_diff'
	 6: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/lib/hidden-definition-finder.rb:197:in `serialize_constants'
	 5: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/lib/hidden-definition-finder.rb:197:in `each'
	 4: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/lib/hidden-definition-finder.rb:204:in `block in serialize_constants'
	 3: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/lib/hidden-definition-finder.rb:261:in `serialize_class'
	 2: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/lib/hidden-definition-finder.rb:286:in `without_errors'
	 1: from /Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/lib/hidden-definition-finder.rb:286:in `reject'
/Users/nickelser/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5376/lib/hidden-definition-finder.rb:286:in `block in without_errors': undefined method `start_with?' for :out:Symbol (NoMethodError)
```

#### Expected behavior

I suspect this: 
https://github.com/sorbet/sorbet/blob/master/gems/sorbet/lib/hidden-definition-finder.rb#L285-L287

needs to change to:

```ruby
  private def without_errors(lines)
    lines.reject {|line| line.to_s.start_with?("#")}
  end
```

but I haven't had time to follow the traceback enough; making that change does let hidden-definition-finder complete.

**Comment by jez** [comment] 2020-02-26 00:09
I'd rather we fix the root cause of the bug, e.g., why is a Symbol getting into `lines` in the first place, rather than paper over it, which will make it harder to work with / reason about what's going on in the future.

**Comment by nickelser** [comment] 2020-02-26 00:42
@jez yep agreed, which is why I didn't submit a PR with that change. i don't have time right now to trace it back and see why it's a symbol.

**Comment by jez** [comment] 2020-02-26 01:22
Actually, looks like this is probably a dupe of #2693 (this one came first but that one has more context).

**Closed by jez** 2020-02-26 01:22 UTC
Labels: bug, unconfirmed
