### ISSUE TITLE
Sorbet appears to miss Liskov violations when using attr_reader and attr_writer

### ISSUE THREAD

**Issue by RyanBrushett** [sorbet/sorbet#4283] opened 2021-06-18 17:05 UTC
#### Input

Two examples here.

The first, using `attr_reader` and `attr_writer`.
Sorbet reports no errors, great job.

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%3B%20end%0Aclass%20B%20%3C%20A%3B%20end%0Aclass%20C%20%3C%20B%3B%20end%0A%0Aclass%20Parent%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20abstract!%0A%0A%20%20sig%20%7B%20overridable.returns(B)%20%7D%0A%20%20attr_reader%20%3Aattr%0A%0A%20%20sig%20%7B%20overridable.params(attr%3A%20B).void%20%7D%0A%20%20attr_writer%20%3Aattr%0Aend%0A%0Aclass%20BadChild1%20%3C%20Parent%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20%23%20I%20expect%20Return%20type%20A%20does%20not%20match%20return%20type%20of%20overridable%20method%0A%20%20sig%20%7B%20override.returns(A)%20%7D%0A%20%20attr_reader%20%3Aattr%0A%0A%20%20sig%20%7B%20override.params(attr%3A%20A).void%20%7D%0A%20%20attr_writer%20%3Aattr%0Aend%0A%0Aclass%20BadChild2%20%3C%20Parent%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20override.returns(C)%20%7D%0A%20%20attr_reader%20%3Aattr%0A%0A%20%20%23%20I%20expect%20Parameter%20attr%20of%20type%20C%20not%20compatible%20with%20type%20of%20overridable%20method%0A%20%20sig%20%7B%20override.params(attr%3A%20C).void%20%7D%0A%20%20attr_writer%20%3Aattr%0Aend)

```ruby
# typed: true

class A; end
class B < A; end
class C < B; end

class Parent
  extend T::Sig
  extend T::Helpers

  abstract!

  sig { overridable.returns(B) }
  attr_reader :attr

  sig { overridable.params(attr: B).void }
  attr_writer :attr
end

class BadChild1 < Parent
  extend T::Sig

  # I expect Return type A does not match return type of overridable method but this passes
  sig { override.returns(A) }
  attr_reader :attr

  sig { override.params(attr: A).void }
  attr_writer :attr
end

class BadChild2 < Parent
  extend T::Sig

  sig { override.returns(C) }
  attr_reader :attr

  # I expect Parameter attr of type C not compatible with type of overridable method but this passes
  sig { override.params(attr: C).void }
  attr_writer :attr
end
```

If we look at a second example with methods written out a bit. Here sorbet complains as I would expect:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%3B%20end%0Aclass%20B%20%3C%20A%3B%20end%0Aclass%20C%20%3C%20B%3B%20end%0A%0Aclass%20Parent%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20abstract!%0A%0A%20%20sig%20%7B%20overridable.returns(B)%20%7D%0A%20%20def%20attr%0A%20%20%20%20B.new%0A%20%20end%0A%0A%20%20sig%20%7B%20overridable.params(attr%3A%20B).void%20%7D%0A%20%20def%20attr%3D(attr)%0A%20%20%20%20%40attr%20%3D%20attr%0A%20%20end%0Aend%0A%0Aclass%20BadChild1%20%3C%20Parent%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20override.returns(A)%20%7D%0A%20%20def%20attr%0A%20%20%20%20A.new%0A%20%20end%0A%0A%20%20sig%20%7B%20override.params(attr%3A%20A).void%20%7D%0A%20%20def%20attr%3D(attr)%0A%20%20%20%20%40attr%20%3D%20attr%0A%20%20end%0Aend%0A%0Aclass%20BadChild2%20%3C%20Parent%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20override.returns(C)%20%7D%0A%20%20def%20attr%0A%20%20%20%20C.new%0A%20%20end%0A%0A%20%20sig%20%7B%20override.params(attr%3A%20C).void%20%7D%0A%20%20def%20attr%3D(attr)%0A%20%20%20%20%40attr%20%3D%20attr%0A%20%20end%0Aend)

```ruby
# typed: true

class A; end
class B < A; end
class C < B; end

class Parent
  extend T::Sig
  extend T::Helpers

  abstract!

  sig { overridable.returns(B) }
  def attr
    B.new
  end

  sig { overridable.params(attr: B).void }
  def attr=(attr)
    @attr = attr
  end
end

class BadChild1 < Parent
  extend T::Sig

  # Error, as expected
  sig { override.returns(A) }
  def attr
    A.new
  end

  sig { override.params(attr: A).void }
  def attr=(attr)
    @attr = attr
  end
end

class BadChild2 < Parent
  extend T::Sig

  sig { override.returns(C) }
  def attr
    C.new
  end

  # Error, as expected
  sig { override.params(attr: C).void }
  def attr=(attr)
    @attr = attr
  end
end
```

#### Observed output

I was surprised to see that the first example doesn't fail.
The second example fails as I'd expect.

#### Expected behavior

I expect both to fail in the way that my second example fails.

cc @Morriar

**Comment by jez** [comment] 2021-06-18 17:16
Thanks for the report.

https://github.com/sorbet/sorbet/blob/0c6192d44e5e3b32b01f04e51885a48d37739b2b/definition_validator/validator.cc#L348

We silence these errors. You can try relaxing this (maybe: check the overrides for rewriterSynthesized methods if the method explicitly had `overridable` set). I don't remember the historical context but my guess is that it was for legacy code in Stripe's codebase reasons.

**Comment by jez** [comment] 2022-08-14 02:48
Duplicate of #1841

**Closed by jez** 2022-08-14 02:48 UTC
Labels: bug
