### ISSUE TITLE
Enhancement: visually highlight untyped code in editor

### ISSUE THREAD

**Issue by bdewater** [sorbet/sorbet#6774] opened 2023-02-23 21:19 UTC
### Problem

It can be hard to spot where typed code stops and untyped code begins (I'm using VS Code and the Sorbet LSP). One example that has bitten our team a few times is with Active Record models:

```rb
relation = User.where(foo: "bar") # => User::PrivateRelationWhereChain

relation.map do |user|
  T.reveal_type(user) # => User
end

relation.each do |user|
  T.reveal_type(user) # => T.untyped
end
```

There have been other times where I was wondering where my autocomplete suggestions went, or why Sorbet didn't complain about a typo I spotted myself. 

Of course all of this can be fixed, but that starts with knowing the problem is there in the first place. Outside of revealing the type manually, or it blowing up on me later, there's no easy way to know right now.

### Proposed solution

A setting that when enabled marks untyped code. It should be off by default. Visual mark could be a wavy underline (like `T.reveal_type`) and/or subdued color (like unreachable code eg `true || false`). I mocked up the above example:

![Screenshot 2023-02-23 at 4 14 42 PM](https://user-images.githubusercontent.com/496367/221032483-4ac9d29c-fdf1-4efe-9b88-b3c66bc0a524.png)

Based on the [LSP docs](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#adding-a-simple-validation) it seems diagnostics are the mechanism for this. IDK if either style mentioned above is easier to implement or not.

**Comment by jez** [comment] 2023-02-23 21:20
Dupe of #437

**Closed by jez** 2023-02-23 21:20 UTC
Labels: enhancement, unconfirmed
