### ISSUE TITLE
A good follow-up to this PR would be to fix this case to use the keyword arguments during overload checking. right now, it treats keyword arguments present in the send as being an untyped hash in the last argument.

### ISSUE THREAD

**Issue by elliottt** [sorbet/sorbet#3506] opened 2020-10-14 20:40 UTC
A good follow-up to this PR would be to fix this case to use the keyword arguments during overload checking. right now, it treats keyword arguments present in the send as being an untyped hash in the last argument.

_Originally posted by @elliottt in https://github.com/sorbet/sorbet/pull/3490#r504868852_

**Comment by jez** [comment] 2020-10-17 00:23
Dupe of #37

**Closed by jez** 2020-10-17 00:23 UTC
