### ISSUE TITLE
Incorrect reference to `Kernel.select` in errors when calling `select` on a `T.nilable(T::Array)`

### ISSUE THREAD

**Issue by marianosimone** [sorbet/sorbet#7498] opened 2023-11-18 17:18 UTC
I think I found a bug in either Sorbet, one of the rbis, or something else.
#### Input
[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amy_array%20%3D%20T.let%28nil%2C%20T.nilable%28T%3A%3AArray%5BString%5D%29%29%0Amy_array.select%20%7B%7Ca%7C%20a.to_s%7D%20)

```ruby
my_array = T.let(nil, T.nilable(T::Array[String]))
my_array.select {|a| a.to_s }
```

#### Observed output

```
editor.rb:5: Method Kernel#select does not take a block https://srb.help/7035
     5 |my_array.select {|a| a.to_s} 
                       ^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/kernel.rbi#L2311: Kernel#select defined here
    2311 |  def select(read_array, write_array=nil, error_array=nil, timeout=nil); end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Autocorrect: Use -a to autocorrect
    editor.rb:5: Delete
     5 |my_array.select {|a| a.to_s} 
                       ^^^^^^^^^^^^^

editor.rb:5: Not enough arguments provided for method Kernel#select on NilClass component of T.nilable(T::Array[String]). Expected: 1..4, got: 0 https://srb.help/7004
     5 |my_array.select {|a| a.to_s} 
                       ^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/kernel.rbi#L2311: Kernel#select defined here
    2311 |  def select(read_array, write_array=nil, error_array=nil, timeout=nil); end
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 2
```

#### Expected behavior

```
Method `select` does not exist on `NilClass` component of `T.nilable(T::Array[String])`
```

#### Notes
- The error references: https://github.com/sorbet/sorbet/blob/083179e6ee7c567296e36c002bdc8ca59d4b1cac/rbi/core/kernel.rbi#L2302-L2311
- `select` is `private` on `NilClass`:
```ruby
[1] pry(main)> nil.select
NoMethodError: private method `select' called for nil:NilClass
```
- `select` is probably there because of https://github.com/sorbet/sorbet/blob/9dbddbe8b4e74e684dcb8ba18d06915b95707494/rbi/core/object.rbi#L27-L30
- This is scary, because Sorbet is happy with calls like: `nil.select([])`

**Comment by jez** [comment] 2023-11-20 21:19
This is a dupe of https://github.com/sorbet/sorbet/issues/4434

I don't know how hard it is to fix, but it hasn't been a super high priority.

**Closed by jez** 2023-11-20 21:19 UTC
Labels: bug, unconfirmed, rbi
