### ISSUE TITLE
srb rbi init fails when printing reflections.json for methods with more than 1 ignored parameter

### ISSUE THREAD

**Issue by franciscoj** [sorbet/sorbet#3561] opened 2020-10-23 09:19 UTC
Some dependencies on our project (e.g. https://github.com/ai/autoprefixer-rails/blob/0fc26b5286264521e3fb4929abd9dec105c15a78/lib/autoprefixer-rails/sprockets.rb#L59-L63) have methods declared where 2 parameters are ignored with `method(_, _)` latest sorbet version fails doing the `bundle exec srb rbi init` with them.

Happens as well when the code itself does this (not only on dependencies)

An example project for reproduction can be found here: https://github.com/franciscoj/sorbet-reproduce-error.

Thanks for the comments on this issue I've been able to pinpoint the version `0.5.5991` as the one that introduces this issue (version `0.5.5981` works) 

#### Input

No errors present on sorbet.run (Adding it just in case)

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Test%0A%20%20def%20m(_%2C%20_)%0A%20%20end%0Aend)

```ruby
class Test
  def m(_, _)
  end
end
```

#### Observed output

When running `bundle exec srb rbi init`

```
Naming all Modules
Naming Bundler::ThorGot LoadError when trying to get nested name Bundler::Thor::RakeCompat
Naming Gem/home/user/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5994/lib/real_stdlib.rb:77: warning: constant Gem::RubyGemsVersion is deprecated
/home/user/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5994/lib/real_stdlib.rb:77: warning: constant Gem::ConfigMap is deprecated
Naming Struct/home/user/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5994/lib/real_stdlib.rb:77: warning: constant Struct::Tms is deprecated
Generating /tmp/d20201023-379925-1s5ppha/reflection.rbi with 900 modules and 36 aliases
Printing your code's symbol table into /tmp/d20201023-379925-1s5ppha/from-source.json
Printing /tmp/d20201023-379925-1s5ppha/reflection.rbi's symbol table into /tmp/d20201023-379925-1s5ppha/reflection.json
Traceback (most recent call last):
	6: from /home/user/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5994/bin/srb-rbi:237:in `<main>'
	5: from /home/user/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5994/bin/srb-rbi:196:in `main'
	4: from /home/user/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5994/bin/srb-rbi:121:in `init'
	3: from /home/user/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5994/bin/srb-rbi:232:in `block in make_step'
	2: from /home/user/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5994/lib/hidden-definition-finder.rb:38:in `main'
	1: from /home/user/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5994/lib/hidden-definition-finder.rb:47:in `main'
/home/user/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0/gems/sorbet-0.5.5994/lib/hidden-definition-finder.rb:151:in `write_constants': /tmp/d20201023-379925-1s5ppha/reflection.rbi had unexpected errors. Check this file for a clue: /tmp/d20201023-379925-1s5ppha/reflection.json.err (RuntimeError)
```

#### Expected behavior

Sorbet would finish running the init as usual.

**Edit** November 6th 2020: Added failing versions.

**Comment by jcoyne** [comment] 2020-10-23 18:22
I have exactly the same problem after updating sorbet:
```
-    sorbet (0.5.5939)
-      sorbet-static (= 0.5.5939)
+    sorbet (0.5.5994)
+      sorbet-static (= 0.5.5994)
     sorbet-coerce (0.2.7)
       polyfill (~> 1.8)
       safe_type (~> 1.1, >= 1.1.1)
@@ -387,7 +387,7 @@ GEM
       sorbet-coerce (>= 0.2.6)
       sorbet-runtime (>= 0.5)
     sorbet-runtime (0.5.5916)
-    sorbet-static (0.5.5939-universal-darwin-19)
+    sorbet-static (0.5.5994-universal-darwin-14)
```

**Comment by mjgiarlo** [comment] 2020-10-26 22:11
Here's what `reflection.json.err` looks like for me:

```shell
$ cat /tmp/d20201026-28849-lotn3p/reflection.json.err
/tmp/d20201026-28849-lotn3p/reflection.rbi:19261: Hash key `_` is duplicated https://srb.help/3011
       19261 |      _: ::T.untyped,
                    ^
    /tmp/d20201026-28849-lotn3p/reflection.rbi:19260: First occurrence of `_` hash key
       19260 |      _: ::T.untyped,
                    ^

/tmp/d20201026-28849-lotn3p/reflection.rbi:69370: Hash key `_` is duplicated https://srb.help/3011
       69370 |      _: ::T.untyped,
                    ^
    /tmp/d20201026-28849-lotn3p/reflection.rbi:69369: First occurrence of `_` hash key
       69369 |      _: ::T.untyped,
                    ^
```

**Comment by orangethunder** [comment] 2020-11-04 13:18
FWIW, I only had 2 gems that were causing an issue. I've already submitted a PR to [autoprefixer-rails](https://github.com/ai/autoprefixer-rails/pull/195). The other was the aws-sdk-master gem. I see that someone did https://github.com/aws/aws-sdk-ruby/pull/2428 to fix it (which is itself a fix for a previous PR). It appears V2 of the AWS SDK has been released with the fix, but not aws-sdk-core as it would be when using V3.

**Comment by jaredbeck** [comment] 2020-11-05 17:35
Does this also affect Proc arguments? If so, I'm afraid this "technique" is quite popular. 

1. Duplicate lambda arguments in rails:

    ```ruby
    # activesupport-6.0.3.4/lib/active_support/deprecation/behaviors.rb:104
    -> message, callstack, _, _ { behavior.call(message, callstack) }
    ```

1. Duplicate block arguments `tmpdir.rb`, in the ruby stdlib:

    ```ruby
    # ~/.rbenv/versions/2.6.6/lib/ruby/2.6.0/tmpdir.rb:87
    path = Tmpname.create(prefix_suffix || "d", *rest) {|path, _, _, d|
    ```

**Comment by albb0920** [comment] 2020-11-06 03:31
Related:
https://github.com/sorbet/sorbet/issues/2273
https://github.com/sorbet/sorbet/pull/3345

@DarkDimius 
Does sorbet expects 3rd party gems to make changes for sorbet to work?

**Comment by connorshea** [comment] 2020-11-07 21:47
The Bootsnap gem also has this problem: https://github.com/Shopify/bootsnap/blob/b54a3679c095cb7aff25c75dcc177d46415a3a4a/lib/bootsnap/compile_cache/iseq.rb#L38

```
/var/folders/2n/6l8d3x457wq9m5fpry0dltb40000gn/T/d20201107-94628-1ls1rjt/reflection.rbi:90940: Hash key `_` is duplicated https://srb.help/3011
       90940 |      _: ::T.untyped,
                    ^
    /var/folders/2n/6l8d3x457wq9m5fpry0dltb40000gn/T/d20201107-94628-1ls1rjt/reflection.rbi:90939: First occurrence of `_` hash key
       90939 |      _: ::T.untyped,
                    ^
```

**Comment by jaredbeck** [comment] 2020-11-25 17:17
> .. downgrading to 0.5.5981 worked for me.

After upgrading to 0.5.6111, I was able to run `srb init`. @connorshea could this be a result of your work (eg. 03261ce) or did I just get lucky :)

**Comment by connorshea** [comment] 2020-11-25 17:21
@jaredbeck if you're on the most recent bootsnap, it should've worked even if the issue is still present in sorbet.

**Comment by Pjata** [comment] 2020-11-27 08:51
I have a rather similar problem, it seems to be related to sorbet-rails maybe?

```
/tmp/d20201127-620-1t4usy5/reflection.rbi:32041: Hash key `_` is duplicated
https://srb.help/3011
       32041 |      _: ::T.untyped,
                    ^
    /tmp/d20201127-620-1t4usy5/reflection.rbi:32040: First occurrence of `_`
hash key
       32040 |      _: ::T.untyped,
                    ^

/tmp/d20201127-620-1t4usy5/reflection.rbi:84435: Hash key `_` is duplicated
https://srb.help/3011
       84435 |      _: ::T.untyped,
                    ^
    /tmp/d20201127-620-1t4usy5/reflection.rbi:84434: First occurrence of `_`
hash key
       84434 |      _: ::T.untyped,
                    ^

class ActionView::NullResolver < ActionView::PathResolver
  DEFAULT_PATTERN = ::T.let(nil, ::T.untyped)
  EXTENSIONS = ::T.let(nil, ::T.untyped)
  sig do
    params(
      path: ::T.untyped,
      exts: ::T.untyped,
      _: ::T.untyped,
      _: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def query(path, exts, _, _); end
end

class AutoprefixerRails::Sprockets
  include ::ActiveSupport::ToJsonWithActiveSupportEncoder
  sig do
    params(
      filename: ::T.untyped,
      block: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def initialize(filename, &block); end

  sig do
    params(
      _: ::T.untyped,
      _: ::T.untyped,
    )
    .returns(::T.untyped)
  end
  def render(_, _); end
```

**Comment by ric2b** [comment] 2020-11-27 19:01
Also being bitten by this, in my case it forced me to update `aws-sdk`.

**Comment by jez** [comment] 2022-07-27 20:52
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca

**Closed by jez** 2022-07-27 20:52 UTC
Labels: bug, srb
