### ISSUE TITLE
Sorbet thinks an Array is a Set

### ISSUE THREAD

**Issue by jaredbeck** [sorbet/sorbet#3405] opened 2020-09-03 17:33 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0AT.let(%0A%20%20%7B%201%20%3D%3E%20%5B%3Ax%5D%20%7D%2C%0A%20%20T%3A%3AHash%5BInteger%2C%20T%3A%3ASet%5BSymbol%5D%5D%0A)%0A)

```ruby
# typed: true
T.let(
  { 1 => [:x] },
  T::Hash[Integer, T::Set[Symbol]]
)
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

Sorbet should say e.g. "Expected Set, got Array"

**Comment by jaredbeck** [comment] 2020-09-03 17:50
Hmmm, it seems this is intentional.

> Sorbet used to take these type parameters into account during runtime type-checking, but .. this behavior was eventually removed.
> https://sorbet.org/docs/stdlib-generics

I can see how this would impact performance, but I'm not sure compromising the integrity of the type system is worth it.

**Comment by jaredbeck** [comment] 2020-09-03 17:52
Re-opening because the docs say that runtime type-checking is disabled, but this issue also demonstrates a problem with static analysis.

**Comment by jez** [comment] 2020-10-18 07:02
This is a bug in how sorbet treats hash literals as shape types.

Closing as a dupe of #11

**Closed** 2020-10-18 07:06 UTC
Labels: bug, unconfirmed
