### ISSUE TITLE
Incorrect class in error output for variable pinning

### ISSUE THREAD

**Issue by wildmaples** [sorbet/sorbet#6071] opened 2022-07-22 11:30 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Ab%20%3D%20%3Asym%0Ab%20%3D%20T.let%28'str'%2C%20String%29%20%23%20Pinned%20to%20a%20String%0Ab%20%3D%20%3Asym)

```ruby
# typed: true

b = :sym
b = T.let('str', String) # Pinned to a String
b = :sym
```

#### Observed output

```
editor.rb:3: Incompatible assignment to variable declared via let: Symbol(:sym) is not a subtype of NilClass https://srb.help/7001
     3 |b = :sym
            ^^^^

editor.rb:5: Incompatible assignment to variable declared via let: Symbol(:sym) is not a subtype of String https://srb.help/7001
     5 |b = :sym
            ^^^^
Errors: 2
```

#### Expected behavior

I'm not sure if this was intentional, but shouldn't the first assignment of `b` have the error that the `Symbol(:sym) is not a subtype of String` instead of `NilClass`?

**Comment by jez** [comment] 2022-07-22 16:35
I think that this is a duplicate of #3482. If it looks different feel free to reopen.

**Closed by jez** 2022-07-22 16:35 UTC
Labels: bug, unconfirmed
