### ISSUE TITLE
Class.new do .. end method definitions breaks other classes

### ISSUE THREAD

**Issue by bmalinconico** [sorbet/sorbet#6193] opened 2022-08-08 18:45 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0At%20%3D%20Class.new%20do%0A%20%20sig%20%7B%20params%28var%3A%20String%29.void%20%7D%0A%20%20def%20initialize%28var%29%3Bend%0Aend%0A%0Aclass%20Bar%0Aend%0A%0ABar.new%0A)

```ruby
# typed: strict
extend T::Sig

t = Class.new do
  sig { params(var: String).void }
  def initialize(var);end
end

class Bar
end

Bar.new
```

#### Observed output

```
editor.rb:12: Not enough arguments provided for method Object#initialize. Expected: 1, got: 0 https://srb.help/7004
    12 |Bar.new
               ^
    editor.rb:6: Object#initialize defined here
     6 |  def initialize(var);end
          ^^^^^^^^^^^^^^^^^^^

editor.rb:12: Non-private call to private method initialize on Bar https://srb.help/7031
    12 |Bar.new
        ^^^^^^^
    editor.rb:6: Defined in Object here
     6 |  def initialize(var);end
          ^^^^^^^^^^^^^^^^^^^
Errors: 2
```

#### Expected behavior

The class created from the return of `Class.new` is separate from classes that inherit from Class itself. This behavior can be seen in custom defined classes as well.

- - -

**Comment by jez** [comment] 2022-08-08 18:47
Duplicate of #3609.

**Closed by jez** 2022-08-08 18:47 UTC
Labels: bug, unconfirmed
