### ISSUE TITLE
False positive dead code error on elsif branches with 2 booleans

### ISSUE THREAD

**Issue by DanielGilchrist** [sorbet/sorbet#4401] opened 2021-07-25 18:10 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Acondition1%20%3D%20T.let(false%2C%20T%3A%3ABoolean)%0Acondition2%20%3D%20T.let(true%2C%20T%3A%3ABoolean)%0A%0Aif%20condition1%20%26%26%20condition2%0A%20%20T.reveal_type(condition1)%0A%20%20T.reveal_type(condition2)%0Aelsif%20condition1%20%26%26%20!condition2%0A%20%20T.reveal_type(condition1)%0A%20%20T.reveal_type(condition2)%0Aelsif%20!condition1%20%26%26%20condition2%20%23%20Dead%20code%20error%20when%20there%20shouldn't%20be%0A%20%20T.reveal_type(condition1)%0A%20%20T.reveal_type(condition2)%0Aend)

```ruby
# typed: true
extend T::Sig

condition1 = T.let(false, T::Boolean)
condition2 = T.let(true, T::Boolean)

if condition1 && condition2
  T.reveal_type(condition1)
  T.reveal_type(condition2)
elsif condition1 && !condition2
  T.reveal_type(condition1)
  T.reveal_type(condition2)
elsif !condition1 && condition2 # Dead code error when there shouldn't be
  T.reveal_type(condition1)
  T.reveal_type(condition2)
end
```

#### Observed output

```
editor.rb:8: Revealed type: TrueClass https://srb.help/7014
     8 |  T.reveal_type(condition1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  Got TrueClass originating from:
    editor.rb:4:
     4 |condition1 = T.let(false, T::Boolean)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:7:
     7 |if condition1 && condition2
           ^^^^^^^^^^

editor.rb:9: Revealed type: TrueClass https://srb.help/7014
     9 |  T.reveal_type(condition2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  Got TrueClass originating from:
    editor.rb:5:
     5 |condition2 = T.let(true, T::Boolean)
                     ^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:7:
     7 |if condition1 && condition2
           ^^^^^^^^^^^^^^^^^^^^^^^^

editor.rb:11: Revealed type: TrueClass https://srb.help/7014
    11 |  T.reveal_type(condition1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  Got TrueClass originating from:
    editor.rb:4:
     4 |condition1 = T.let(false, T::Boolean)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:7:
     7 |if condition1 && condition2
           ^^^^^^^^^^
    editor.rb:10:
    10 |elsif condition1 && !condition2
              ^^^^^^^^^^

editor.rb:12: Revealed type: FalseClass https://srb.help/7014
    12 |  T.reveal_type(condition2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  Got FalseClass originating from:
    editor.rb:5:
     5 |condition2 = T.let(true, T::Boolean)
                     ^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:7:
     7 |if condition1 && condition2
           ^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:10:
    10 |elsif condition1 && !condition2
              ^^^^^^^^^^

editor.rb:13: This code is unreachable https://srb.help/7006
    13 |elsif !condition1 && condition2 # Dead code error when there shouldn't be
              ^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:13: This condition was always truthy (TrueClass)
    13 |elsif !condition1 && condition2 # Dead code error when there shouldn't be
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  Got TrueClass originating from:
    editor.rb:13:
    13 |elsif !condition1 && condition2 # Dead code error when there shouldn't be
              ^^^^^^^^^^^

editor.rb:14: Revealed type: FalseClass https://srb.help/7014
    14 |  T.reveal_type(condition1)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  Got FalseClass originating from:
    editor.rb:4:
     4 |condition1 = T.let(false, T::Boolean)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:7:
     7 |if condition1 && condition2
           ^^^^^^^^^^
    editor.rb:10:
    10 |elsif condition1 && !condition2
              ^^^^^^^^^^

editor.rb:15: Revealed type: TrueClass https://srb.help/7014
    15 |  T.reveal_type(condition2)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  Got TrueClass originating from:
    editor.rb:5:
     5 |condition2 = T.let(true, T::Boolean)
                     ^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:7:
     7 |if condition1 && condition2
           ^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:13:
    13 |elsif !condition1 && condition2 # Dead code error when there shouldn't be
              ^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 7
```

#### Expected behavior

I would expect there to be no "This code is unreachable" error

- - -

Running the below code in IRB shows that reaching that branch is possible
```ruby
condition1 = false
condition2 = true

if condition1 && condition2
  puts "condition1 && condition2"
elsif condition1 && !condition2
  puts "condition1 && !condition2"
elsif !condition1 && condition2
  puts "!condition1 && condition2"
end
```
![image](https://user-images.githubusercontent.com/13454550/126908817-4f3103e3-2723-4c58-89aa-8b0c794ae83a.png)

**Comment by jez** [comment] 2021-07-27 18:15
This is a dupe of https://github.com/sorbet/sorbet/issues/820

Sorbet is smart enough to know that `condition1` is always false at that point.

I believe the part it's complaining is dead is actually the `&& condition2` part of the second `elsif`, because `!condition1` is always true.

Feel free to reopen if i've misread.

**Closed by jez** 2021-07-27 18:15 UTC
Labels: bug, unconfirmed
