### ISSUE TITLE
Type resolves to `T.nilable(FalseClass)` in `elsif` and `else` branches when checking on `T.untyped`

### ISSUE THREAD

**Issue by DanielGilchrist** [sorbet/sorbet#4125] opened 2021-03-31 09:36 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Anumber%20%3D%20T.let(5%2C%20T.untyped)%0A%0Aif%20number%0A%20%20T.reveal_type(number)%20%23%20ok%0Aelse%0A%20%20T.reveal_type(number)%20%23%20should%20still%20be%20T.untyped%0Aend)

```ruby
# typed: true
number = T.let(5, T.untyped)

if number
  T.reveal_type(number) # ok
else
  T.reveal_type(number) # should still be T.untyped
end

if number
  T.reveal_type(number) # ok
elsif
  T.reveal_type(number) # should still be T.untyped
else
  T.reveal_type(number) # should still be T.untyped
end

#        ok                      should still be T.untyped
number ? T.reveal_type(number) : T.reveal_type(number)
```

#### Observed output

```
editor.rb:7: Revealed type: T.nilable(FalseClass) https://srb.help/7014
     7 |  T.reveal_type(number) # should still be T.untyped
          ^^^^^^^^^^^^^^^^^^^^^
  Got T.nilable(FalseClass) originating from:
    editor.rb:2:
     2 |number = T.let(5, T.untyped)
                 ^^^^^^^^^^^^^^^^^^^
    editor.rb:4:
     4 |if number
           ^^^^^^

editor.rb:5: Revealed type: T.untyped https://srb.help/7014
     5 |  T.reveal_type(number) # ok
          ^^^^^^^^^^^^^^^^^^^^^
  Got T.untyped originating from:
    editor.rb:2:
     2 |number = T.let(5, T.untyped)
                 ^^^^^^^^^^^^^^^^^^^
    editor.rb:4:
     4 |if number
           ^^^^^^

editor.rb:13: Revealed type: T.nilable(FalseClass) https://srb.help/7014
    13 |  T.reveal_type(number) # should still be T.untyped
          ^^^^^^^^^^^^^^^^^^^^^
  Got T.nilable(FalseClass) originating from:
    editor.rb:2:
     2 |number = T.let(5, T.untyped)
                 ^^^^^^^^^^^^^^^^^^^
    editor.rb:4:
     4 |if number
           ^^^^^^
    editor.rb:10:
    10 |if number
           ^^^^^^

editor.rb:15: Revealed type: T.nilable(FalseClass) https://srb.help/7014
    15 |  T.reveal_type(number) # should still be T.untyped
          ^^^^^^^^^^^^^^^^^^^^^
  Got T.nilable(FalseClass) originating from:
    editor.rb:2:
     2 |number = T.let(5, T.untyped)
                 ^^^^^^^^^^^^^^^^^^^
    editor.rb:4:
     4 |if number
           ^^^^^^
    editor.rb:10:
    10 |if number
           ^^^^^^

editor.rb:11: Revealed type: T.untyped https://srb.help/7014
    11 |  T.reveal_type(number) # ok
          ^^^^^^^^^^^^^^^^^^^^^
  Got T.untyped originating from:
    editor.rb:2:
     2 |number = T.let(5, T.untyped)
                 ^^^^^^^^^^^^^^^^^^^
    editor.rb:4:
     4 |if number
           ^^^^^^
    editor.rb:10:
    10 |if number
           ^^^^^^

editor.rb:19: Revealed type: T.nilable(FalseClass) https://srb.help/7014
    19 |number ? T.reveal_type(number) : T.reveal_type(number)
                                         ^^^^^^^^^^^^^^^^^^^^^
  Got T.nilable(FalseClass) originating from:
    editor.rb:2:
     2 |number = T.let(5, T.untyped)
                 ^^^^^^^^^^^^^^^^^^^
    editor.rb:4:
     4 |if number
           ^^^^^^
    editor.rb:10:
    10 |if number
           ^^^^^^
    editor.rb:19:
    19 |number ? T.reveal_type(number) : T.reveal_type(number)
        ^^^^^^

editor.rb:19: Revealed type: T.untyped https://srb.help/7014
    19 |number ? T.reveal_type(number) : T.reveal_type(number)
                 ^^^^^^^^^^^^^^^^^^^^^
  Got T.untyped originating from:
    editor.rb:2:
     2 |number = T.let(5, T.untyped)
                 ^^^^^^^^^^^^^^^^^^^
    editor.rb:4:
     4 |if number
           ^^^^^^
    editor.rb:10:
    10 |if number
           ^^^^^^
    editor.rb:19:
    19 |number ? T.reveal_type(number) : T.reveal_type(number)
        ^^^^^^
Errors: 7
```

#### Expected behavior

I would expect all cases to be `T.untyped`

**Comment by jez** [comment] 2021-03-31 18:25
I believe this is a dupe of

https://github.com/sorbet/sorbet/issues/373

and I believe this is currently expected behavior. Regardless of whether something started out untyped, if it participates in a conditional branch and we're in the `falsy` branch, Sorbet can be sure that it is one of the two falsy values in Ruby, namely either `nil` or `false`.

Feel free to re-open if I have misinterpreted.

**Closed by jez** 2021-03-31 18:25 UTC
Labels: bug, unconfirmed

**Comment by DanielGilchrist** [comment] 2021-04-01 10:17
> I believe this is a dupe of
> 
> #373
> 
> and I believe this is currently expected behavior. Regardless of whether something started out untyped, if it participates in a conditional branch and we're in the `falsy` branch, Sorbet can be sure that it is one of the two falsy values in Ruby, namely either `nil` or `false`.
> 
> Feel free to re-open if I have misinterpreted.

Better example of where this might be a problem: 
https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Anumber%20%3D%20T.let(5%2C%20T.untyped)%0A%0Aif%20number%0Aelse%0A%20%20add_one(number)%0Aend%0A%0Asig%20%7B%20params(num%3A%20T.nilable(Integer)).returns(Integer)%20%7D%0Adef%20add_one(num)%0A%20%20return%201%20if%20num.nil%3F%0A%0A%20%20num%20%2B%201%0Aend

I think in this case since `number` is `T.untyped` most would expect that it would pass without an error. I'm not too fussed about this since the solution is to simply add types but my main concern is that the error message provided is quite confusing
