### ISSUE TITLE
Unreachable code error has no file/line location in module/class scope

### ISSUE THREAD

**Issue by daviddoran** [sorbet/sorbet#2812] opened 2020-03-27 10:30 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20%23%20No%20location%20(file%20%2B%20line)%20for%20this%20error%0A%20%20%40x%20%7C%7C%3D%20T.let(10%2C%20Integer)%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  # No location (file + line) for this error
  @x ||= T.let(10, Integer)
end
```

#### Observed output

```
-e: This code is unreachable https://srb.help/7006
Errors: 1
```

#### Expected behavior

You'd expect file and line location information, which [works for method-scoped errors](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20main%0A%20%20%23%20But%20this%20one%20does%20have%20file%20%2B%20line%0A%20%20y%20%7C%7C%3D%20T.let(10%2C%20Integer)%0Aend):
```
editor.rb:5: This code is unreachable https://srb.help/7006
     5 |  y ||= T.let(10, Integer)
          ^
Errors: 1
```

- - -

**Comment by jez** [comment] 2020-12-08 21:37
Dupe of #1668

**Closed by jez** 2020-12-08 21:37 UTC
Labels: bug, good first issue
