### ISSUE TITLE
Kernel#Integer can return nil

### ISSUE THREAD

**Issue by thomasdziedzic-census** [sorbet/sorbet#5635] opened 2022-04-13 19:11 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aparsed%20%3D%20Integer%28'a'%2C%20exception%3A%20false%29%0Adefault%20%3D%200%0A%0Avalue%20%3D%20parsed%20%7C%7C%20default%20)

```ruby
# typed: strict

parsed = Integer('a', exception: false)
default = 0

value = parsed || default 
```

#### Observed output

```
editor.rb:6: This code is unreachable https://srb.help/7006
     6 |value = parsed || default 
                          ^^^^^^^
    editor.rb:6: This condition was always truthy (Integer)
     6 |value = parsed || default 
                ^^^^^^
  Got Integer originating from:
    editor.rb:3:
     3 |parsed = Integer('a', exception: false)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

When exception is false, the return value could be nil.

**Comment by jez** [comment] 2022-04-13 19:21
dupe of #4336

**Closed by jez** 2022-04-13 19:21 UTC
Labels: bug, unconfirmed, rbi
