### ISSUE TITLE
LSP: Document symbols request fails due to enforce failure

### ISSUE THREAD

**Issue by jvilk-stripe** [sorbet/sorbet#436] opened 2019-05-08 23:36 UTC
#### Input

Unknown; found in log file.

#### Observed output

```
Exception::raise(): Should never happen
Backtrace:
  #3 0x451855 sorbet::realmain::lsp::symbolRef2DocumentSymbolWalkMembers()
  #4 0x451ebb sorbet::realmain::lsp::symbolRef2DocumentSymbol()
  #5 0x452570 sorbet::realmain::lsp::LSPLoop::handleTextDocumentDocumentSymbol()
  #6 0x43fef6 sorbet::realmain::lsp::LSPLoop::processRequestInternal()
  #7 0x43d910 sorbet::realmain::lsp::LSPLoop::processRequest()
  #8 0x4353a3 sorbet::realmain::lsp::LSPLoop::runLSP()
  #9 0x3e151b sorbet::realmain::realmain()
  #10 0x3df95b main
  #11 0x7fd5d5199f45 
  #12 0x39d029 
```

#### Expected behavior

This doesn't happen.

**Comment by jez** [comment] 2024-03-29 18:41
Closing because can't reproduce. Was probably a fast path loc bug but we fixed a ton of those since 2019

**Closed by jez** 2024-03-29 18:41 UTC
Labels: bug, IDE, crash
