### ISSUE TITLE
documentSymbols crash when editing @foo

### ISSUE THREAD

**Issue by azdavis** [sorbet/sorbet#1553] opened 2019-08-12 22:50 UTC
## Input

```rb
# typed: true
class C
  @foo = T.let(3, Integer)
end
```

1. Start with this file
1. Put cursor directly after `@foo`
1. Type `d`

## Expected

No error

## Actual

```
Exception::raise(): main/lsp/DefLocSaver.cc:54 enforced condition ctx.owner.data(ctx)->isMethod() has failed: (no message provided)

Backtrace:
sorbet::Exception::enforce_handler(std::__1::basic_string_view<char, std::__1::char_traits<char> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, int) (in librealmain.so) (Exception.h:57)
sorbet::realmain::lsp::DefLocSaver::postTransformUnresolvedIdent(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::UnresolvedIdent, std::__1::default_delete<sorbet::ast::UnresolvedIdent> >) (in liblsp.so) (DefLocSaver.cc:54)
sorbet::ast::PostPonePostTransform_UnresolvedIdent<sorbet::realmain::lsp::DefLocSaver, sorbet::core::Context, true>::call(sorbet::core::Context, std::__1::unique_ptr<sorbet::ast::UnresolvedIdent, std::__1::default_delete<sorbet::ast::UnresolvedIdent> >, sorbet::realmain::lsp::DefLocSaver&) (in liblsp.so) (treemap.h:232)
sorbet::ast::TreeMapper<sorbet::realmain::lsp::DefLocSaver, sorbet::core::Context>::mapUnresolvedIdent(std::__1::unique_ptr<sorbet::ast::UnresolvedIdent, std::__1::default_delete<sorbet::ast::UnresolvedIdent> >, sorbet::core::Context) (in liblsp.so) (treemap.h:462)
sorbet::ast::TreeMapper<sorbet::realmain::lsp::DefLocSaver, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in liblsp.so) (treemap.h:661)
sorbet::ast::TreeMapper<sorbet::realmain::lsp::DefLocSaver, sorbet::core::Context>::mapAssign(std::__1::unique_ptr<sorbet::ast::Assign, std::__1::default_delete<sorbet::ast::Assign> >, sorbet::core::Context) (in liblsp.so) (treemap.h:474)
sorbet::ast::TreeMapper<sorbet::realmain::lsp::DefLocSaver, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in liblsp.so) (treemap.h:690)
sorbet::ast::TreeMapper<sorbet::realmain::lsp::DefLocSaver, sorbet::core::Context>::mapClassDef(std::__1::unique_ptr<sorbet::ast::ClassDef, std::__1::default_delete<sorbet::ast::ClassDef> >, sorbet::core::Context) (in liblsp.so) (treemap.h:281)
sorbet::ast::TreeMapper<sorbet::realmain::lsp::DefLocSaver, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in liblsp.so) (treemap.h:672)
sorbet::ast::TreeMapper<sorbet::realmain::lsp::DefLocSaver, sorbet::core::Context>::mapInsSeq(std::__1::unique_ptr<sorbet::ast::InsSeq, std::__1::default_delete<sorbet::ast::InsSeq> >, sorbet::core::Context) (in liblsp.so) (treemap.h:601)
sorbet::ast::TreeMapper<sorbet::realmain::lsp::DefLocSaver, sorbet::core::Context>::mapIt(std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >, sorbet::core::Context) (in liblsp.so) (treemap.h:668)
std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> > sorbet::ast::TreeMap::apply<sorbet::core::Context, sorbet::realmain::lsp::DefLocSaver>(sorbet::core::Context, sorbet::realmain::lsp::DefLocSaver&, std::__1::unique_ptr<sorbet::ast::Expression, std::__1::default_delete<sorbet::ast::Expression> >) (in liblsp.so) (treemap.h:712)
sorbet::realmain::lsp::tryApplyDefLocSaver(sorbet::core::GlobalState const&, std::__1::vector<sorbet::ast::ParsedFile, std::__1::allocator<sorbet::ast::ParsedFile> >&) (in liblsp.so) (updates.cc:197)
sorbet::realmain::lsp::LSPLoop::runQuery(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >, sorbet::core::lsp::Query const&, std::__1::vector<sorbet::core::FileRef, std::__1::allocator<sorbet::core::FileRef> > const&) const (in liblsp.so) (updates.cc:382)
sorbet::realmain::lsp::LSPLoop::setupLSPQueryByLoc(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >, std::__1::basic_string_view<char, std::__1::char_traits<char> >, sorbet::realmain::lsp::Position const&, sorbet::realmain::lsp::LSPMethod, bool) const (in liblsp.so) (lsp.cc:57)
sorbet::realmain::lsp::LSPLoop::handleTextDocumentCompletion(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >, sorbet::realmain::lsp::MessageId const&, sorbet::realmain::lsp::CompletionParams const&) const (in liblsp.so) (completion.cc:203)
sorbet::realmain::lsp::LSPLoop::processRequestInternal(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >, sorbet::realmain::lsp::LSPMessage const&) (in liblsp.so) (request_dispatch.cc:217)
sorbet::realmain::lsp::LSPLoop::processRequest(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >, sorbet::realmain::lsp::LSPMessage const&) (in liblsp.so) (request_dispatch.cc:18)
sorbet::realmain::lsp::LSPLoop::runLSP() (in liblsp.so) (protocol.cc:205)
sorbet::realmain::realmain(int, char**) (in librealmain.so) (realmain.cc:455)
main (in sorbet) (main.cc:7)
start (in libdyld.dylib) + 1
```

**Comment by jvilk-stripe** [comment] 2019-08-21 18:44
I am unable to reproduce this bug. Just landed a test for it that passes.

**Closed by jvilk-stripe** 2019-08-21 18:44 UTC
Labels: IDE, bug
