### ISSUE TITLE
`srb rbi gems` modifies gem RBIs generated via `srb init`

### ISSUE THREAD

**Issue by pariser** [sorbet/sorbet#1146] opened 2019-06-30 01:26 UTC
#### Input

Consider the following workflow:
- Install sorbet into an existing ruby project that depends on a single gem (`'first_gem'`)
- Run `srb init` and commit `sorbet/` folder
- Add a new gem to your `Gemfile` (`'second_gem'`) and run `bundle install`
- Run `srb rbi gems`

My expectation, upon running `srb rbi gems` is that the diff would include exactly one added file, `sorbet/rbi/gems/second_gem.rbi`

However, `srb rbi gems` _also_ seems to modify the `# typed:` annotation in the first gem's RBI file, `sorbet/rbi/gems/first_gem.rbi`

I set up an example repository with a branch `init-rbi-gems-issue` that replicates these steps exactly (first gem: `'colored'`, second gem: `'timecop'`) in a series of commits: [example repository](https://github.com/pariser/sorbet-bug/compare/init-rbi-gems-issue)

Specifically, you can see [the modification of the original gem in the final commit](https://github.com/pariser/sorbet-bug/commit/24eab592a41988c2beb144ee5373f816e8dec4a4#diff-59a4a56a730efe339b667b74e81a2b9cL4).

#### Observed output

`srb rbi gems` modifies `# typed:` annotation level on gem RBIs created via `srb init`

#### Expected behavior

`srb rbi gems` should only modify gem RBIs for newly added gems or gems with changed source code (e.g. on gem version changes)

- - -

**Comment by connorshea** [comment] 2019-06-30 01:48
I observed the same behavior with my own project 👍

**Comment by jez** [comment] 2019-07-02 23:41
Thank you for the very specific bug report! It was incredibly helpful.

In case the repo gets deleted, here's the interesting diff:

```diff
diff --git a/sorbet/rbi/gems/colored.rbi b/sorbet/rbi/gems/colored.rbi
index fe60be2..0c8631d 100644
--- a/sorbet/rbi/gems/colored.rbi
+++ b/sorbet/rbi/gems/colored.rbi
@@ -1,7 +1,7 @@
 # This file is autogenerated. Do not edit it by hand. Regenerate it with:
 #   srb rbi gems
 
-# typed: strong
+# typed: true
 #
 # If you would like to make changes to this file, great! Please create the gem's shim here:
 #
```

The problem is that `srb init` actually has two steps which change the files in the `sorbet/rbi/gems` folder:

- the `gems` subcommand, which creates the RBIs
- the `suggest-typed` subcommand, which puts the highest strictness level into each file in a project as it can without introducing errors

So the workaround would be to run

```
srb rbi gems && srb rbi suggest-typed
```

but we could also make this the default behavior. I'm marking as a good first issue in case someone wants to implement this.

**Comment by jasnow** [comment] 2019-07-12 21:24
Saw this today too.

**Closed** 2019-09-12 00:45 UTC
Labels: bug, good first issue
