### ISSUE TITLE
Click to definition doesn't work for `super` calls

### ISSUE THREAD

**Issue by steved-stripe** [sorbet/sorbet#5608] opened 2022-04-08 18:28 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Bar%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7Bparams%28arg%3A%20String%29.void%7D%0A%20%20def%20initalize%28arg%29%0A%20%20end%0Aend%0A%0Aclass%20Foo%20%3C%20Bar%20%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20initialize%0A%20%20%20%20super%28%221000%22%29%0A%20%20end%0Aend)

```ruby
# typed: true

class Bar
  extend T::Sig
  sig {params(arg: String).void}
  def initalize(arg)
  end
end

class Foo < Bar 
  extend T::Sig

  sig {void}
  def initialize
    super("1000")
  end
end
```

#### Observed output

Can't click `super` to navigate to the parent class

#### Expected behavior

Clicking `super` should navigate to the parent class constructor.

- - -

testing with Typescript and it works in vscode:

```typescript
class Bar {
  constructor(param: string) {
    console.log(param);
  }
}

class Foo extends Bar {
  constructor() {
    super('foo');
  }
}
```

https://www.typescriptlang.org/play?#code/MYGwhgzhAEBCYCdoG8CwAoa1gHsB2EALggK7CE4IAUADomALYBc0RCAlngOYCUKGWLLgI4QAUwB0IHF1r0GPANwDoAXwzr0GUJBgAxHDmhiAHoTF4AJjHhI0mbPjZkK1PvcGsSNMdQDkAGaGfkoqmqpAA

**Comment by jez** [comment] 2022-04-08 18:36
Ah sorry, this is a duplicate of #1068 (it's a known problem unfortunately).

TypeScript's job is substantially easier, because there is no multiple inheritance (no mixins / modules). But we do have a few ideas for how to potentially improve this one day.

**Closed by jez** 2022-04-08 18:36 UTC
Labels: bug, unconfirmed
