### ISSUE TITLE
Flow sensitive typing not using `T.must` for local variable

### ISSUE THREAD

**Issue by sambostock** [sorbet/sorbet#6715] opened 2023-02-09 19:15 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Av%20%3D%20T.let%28true%2C%20T.nilable%28TrueClass%29%29%0AT.must%28v%29%0AT.reveal_type%28v%29)

```ruby
# typed: strict
extend T::Sig

v = T.let(true, T.nilable(TrueClass))
T.must(v)
T.reveal_type(v)
```

#### Observed output

```
editor.rb:6: Revealed type: T.nilable(TrueClass) https://srb.help/7014
     6 |T.reveal_type(v)
        ^^^^^^^^^^^^^^^^
  Got T.nilable(TrueClass) originating from:
    editor.rb:4:
     4 |v = T.let(true, T.nilable(TrueClass))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

`v` is a local variable of type `T.nilable(TrueClass)` (not a method call, instance variable, etc.), so after "successfully" invoking `T.must`, it should be safe to assume that its type is _actually_ non-nilable `TrueClass`.

For comparison, Sorbet's flow sensitivity already allows it to do this if you replace `T.must` with a `.nil?` check:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Av%20%3D%20T.let%28true%2C%20T.nilable%28TrueClass%29%29%0Araise%20if%20v.nil%3F%0AT.reveal_type%28v%29)

<table><tr><td>

```ruby
# typed: true
extend T::Sig

v = T.let(true, T.nilable(TrueClass))
raise if v.nil?
T.reveal_type(v)
```

</td><td>

```
editor.rb:6: Revealed type: TrueClass https://srb.help/7014
     6 |T.reveal_type(v)
        ^^^^^^^^^^^^^^^^
  Got TrueClass originating from:
    editor.rb:4:
     4 |v = T.let(true, T.nilable(TrueClass))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:5:
     5 |raise if v.nil?
                 ^^^^^^
Errors: 1
```

</td></tr></table>

It seems reasonable that any reason why it Sorbet couldn't apply do this with `T.must` would also apply to `.nil?` checks. Since the `.nil?` check approach works, it seems like a bug that the `T.must` approach does not.

- - -

**Comment by jez** [comment] 2023-02-09 22:14
Duplicate of #3397

**Closed by jez** 2023-02-09 22:14 UTC
