### ISSUE TITLE
Prohibit calling `new` on MetaTypes of unions and type aliases

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#4172] opened 2021-04-23 00:00 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0AIntegerOrString%20%3D%20T.type_alias%20%7BT.any(Integer%2C%20String)%7D%0A%0AT.any(Integer%2C%20String).new%0AIntegerOrString.new%0A%0ATypeAliasToInteger%20%3D%20T.type_alias%20%7BInteger%7D%0ATypeAliasToInteger.new)

```ruby
# typed: strict
IntegerOrString = T.type_alias {T.any(Integer, String)}

T.any(Integer, String).new
IntegerOrString.new

TypeAliasToInteger = T.type_alias {Integer}
TypeAliasToInteger.new
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

All of these calls to `.new` should be errors, because it doesn't make sense to call `.new` on a union nor a type alias at runtime.

- - -

This is likely a good first bug, in particular because there is so much prior art to cargo cult here:

#3425, #3588, #3985, #3426, #3428.

Here would be the place to start:

https://github.com/sorbet/sorbet/blob/84d982b45857ff2bfe0a5483ec33f88defa5eb4d/core/types/calls.cc#L1240-L1254

**Comment by Morriar** [comment] 2021-04-30 20:43
Duplicate of https://github.com/sorbet/sorbet/issues/3335

**Comment by jez** [comment] 2021-07-14 20:31
Here's a more fully-featured test case:

```ruby
# typed: true

# -- good --

String.new
T::Array[String].new

# -- bad --

T.any(Integer, String).new
T.all(Kernel, Comparable).new
T.nilable(String).new

MyArrayString = T.type_alias {T::Array[String]}
MyArrayString.new

T.noreturn.new
T.untyped.new
T.self_type.new

T.class_of(String).new
T.proc.void.new

class MyGeneric
  extend T::Generic

  X = type_template
end

T.class_of(MyGeneric).new
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0A%23%20--%20good%20--%0A%0AString.new%0AT%3A%3AArray%5BString%5D.new%0A%0A%23%20--%20bad%20--%0A%0AT.any(Integer%2C%20String).new%0AT.all(Kernel%2C%20Comparable).new%0AT.nilable(String).new%0A%0AMyArrayString%20%3D%20T.type_alias%20%7BT%3A%3AArray%5BString%5D%7D%0AMyArrayString.new%0A%0AT.noreturn.new%0AT.untyped.new%0AT.self_type.new%0A%0AT.class_of(String).new%0AT.proc.void.new%0A%0Aclass%20MyGeneric%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20X%20%3D%20type_template%0Aend%0A%0AT.class_of(MyGeneric).new)

**Closed** 2021-07-26 21:37 UTC
Labels: bug, good first issue
