### ISSUE TITLE
Incorrect Constant Resolution During Inheritance

### ISSUE THREAD

**Issue by mgriisser** [sorbet/sorbet#1637] opened 2019-08-21 20:23 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20A%0A%20%20class%20B%0A%20%20end%0A%20%20class%20C%0A%20%20%20%20class%20B%20%3C%20B%0A%20%20%20%20%20%20def%20self.print%0A%20%20%20%20%20%20%20%20'hi'%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0Aputs%20A%3A%3AC%3A%3AB.print)

```ruby
# typed: true
module A
  class B
  end
  class C
    class B < B
      def self.print
        'hi'
      end
    end
  end
end

puts A::C::B.print
```

#### Observed output

```
editor.rb:6: Circular dependency: A::C::B is a parent of itself https://srb.help/5011
     6 |    class B < B
                      ^
    editor.rb:6: Class definition
     6 |    class B < B
            ^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

The class A::C::B here is actually inheriting from class A::B, not itself. While this is very bad code it's not a circular dependency. If you run the above code in a script you'll see it output `hi`.

This could potentially be related to: https://github.com/sorbet/sorbet/issues/8

**Comment by jez** [comment] 2019-08-23 21:56
This is essentially a dupe of #8, as you mention.

We consider this a feature not a bug, because constant resolution through ancestors is a really confusing Ruby practice, and the fix straightforward enough (provide a more explicit path to the constant).

Thanks for the report!

**Closed by jez** 2019-08-23 21:56 UTC
Labels: bug, unconfirmed
