### ISSUE TITLE
defective new on Type Alias isn't detected

### ISSUE THREAD

**Issue by md-work** [sorbet/sorbet#3696] opened 2020-11-19 15:46 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Arequire%20'sorbet-runtime'%0A%0Aclass%20MyString%20%3B%20end%20%20%23%20(edit)%20aprocter%20added%20this%20line%0A%0AAString%20%3D%20T.type_alias%20%7B%20T.any(String%2C%20MyString)%20%7D%0AAString.new%20%20%23%20%3D%3E%20runtime%20error%3A%20undefined%20method%20%60new')

```ruby
# typed: true
require 'sorbet-runtime'

class MyString ; end  # (edit) aprocter added this line

AString = T.type_alias { T.any(String, MyString) }
AString.new  # => runtime error: undefined method `new'
```
&nbsp;

#### Observed output

`AString` is an object, not a class. So there's no method `new`.
But currently Sorbet-Static doesn't mark this as an error.
&nbsp;

#### Expected behavior

Sorbet-Static should warn about the not existing method `new` on an object of the class `T::Private::Types::TypeAlias`.

**Comment by aprocter-stripe** [comment] 2020-11-19 18:08
@md-work Thanks for the bug report! (I made a slight edit to the reproducer, declaring the class `MyString`.)

**Comment by jez** [comment] 2020-12-21 22:08
Duplicate of #3335

**Closed by jez** 2020-12-21 22:08 UTC
Labels: bug, good first issue
