### ISSUE TITLE
Instance variable using `||=` are reported as inaccessible in static checks but not in the LSP

### ISSUE THREAD

**Issue by zanemiller-stripe** [sorbet/sorbet#4302] opened 2021-06-24 19:48 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%20%20sig(%3Afinal)%20%7Bvoid%7D%0A%20%20def%20initialize()%0A%20%20%20%20%40foo%20%7C%7C%3D%20T.let(%0A%20%20%20%20%20%20'bar'%2C%0A%20%20%20%20%20%20String%0A%20%20%20%20)%0A%20%20end%0Aend)

```ruby
# typed: strict
extend T::Sig

class Foo
  extend T::Sig
  sig(:final) {void}
  def initialize()
    @foo ||= T.let(
      'bar',
      String
    )
  end
end
```

#### Observed output

```

# typed: strict
extend T::Sig

class Foo
  extend T::Sig
  sig(:final) {void}
  def initialize()
    @foo ||= T.let(
      'bar',
      String
    )
  end
end


-e: This code is unreachable https://srb.help/7006
    editor.rb:8: This condition was always truthy (String)
     8 |    @foo ||= T.let(
            ^^^^
  Got String originating from:
    editor.rb:8:
     8 |    @foo ||= T.let(
            ^^^^
Errors: 1
```

#### Expected behavior

The static failure should be reported in the editor. Additionally it seems like this being reported as inaccessible is ~wrong in this case.

- - -
Example of the editor vs the static output, since that is where the failure of this disconnect happens
![image](https://user-images.githubusercontent.com/34630066/123323469-63fea280-d4ea-11eb-89a2-f7bce89af482.png)

**Comment by jez** [comment] 2022-08-07 00:56
I'm not seeing the LSP problem reproduce anymore, and the other half of the request (to improve the error message itself) is a dupe of #1668.

**Closed by jez** 2022-08-07 00:56 UTC
Labels: bug, IDE
