### ISSUE TITLE
Calling `nil?` on non-nilable value in a conditional doesn't report dead code

### ISSUE THREAD

**Issue by DanielGilchrist** [sorbet/sorbet#3769] opened 2020-12-08 21:17 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20main%0A%20%20if%205.nil%3F%0A%20%20%20%20puts%20%22This%20should%20error%20as%20unreachable%22%0A%20%20end%0A%0A%20%20unless%205%0A%20%20%20%20puts%20%22Errors%20as%20unreachable%20as%20expected%22%0A%20%20end%0Aend)

```ruby
# typed: true

def main
  if 5.nil?
    puts "This should error as unreachable"
  end

  unless 5
    puts "Errors as unreachable as expected"
  end
end
```

#### Observed output

```
editor.rb:9: This code is unreachable https://srb.help/7006
     9 |    puts "Errors as unreachable as expected"
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior
I would expect Sorbet to error stating that `puts "This should error as unreachable"` is unreachable (error 7006)

**Comment by jez** [comment] 2022-08-06 22:46
This is a dupe of #621

**Closed by jez** 2022-08-06 22:46 UTC
Labels: bug
