### ISSUE TITLE
Can't make method alias to non existing method `object_id`

### ISSUE THREAD

**Issue by iMacTia** [sorbet/sorbet#6488] opened 2022-10-19 15:18 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Person%20%0A%20%20alias%20unique_id%20object_id%0Aend)

```ruby
# typed: true
extend T::Sig

class Person 
  alias unique_id object_id
end
```

#### Observed output

```
editor.rb:5: Can't make method alias from unique_id to non existing method object_id https://srb.help/5037
     5 |  alias unique_id object_id
                          ^^^^^^^^^
Errors: 1
```

#### Expected behavior

`object_id` is a method in `Object` and should therefore exist, making it possible to alias it.
I've already tried adding a `include Kernel` to the `Person` class, but that doesn't work.

**Comment by jez** [comment] 2022-10-19 16:54
Duplicate of #2378

**Closed by jez** 2022-10-19 16:54 UTC
