### ISSUE TITLE
Unreachable code error when modifying variable in while loop

### ISSUE THREAD

**Issue by Earlopain** [sorbet/sorbet#8401] opened 2024-12-23 12:26 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#index%20%3D%200%0Alexed%20%3D%20%5B%3AFIRST%2C%20%3ASECOND%5D%0Alength%20%3D%20lexed.length%0A%0Aidentifiers%20%3D%20%5B%5D%0A%0Awhile%20index%20%3C%20length%0A%20%20token%20%3D%20lexed%5Bindex%5D%0A%20%20index%20%2B%3D%201%0A%0A%20%20case%20token%0A%20%20when%20%3AFIRST%0A%0A%20%20%20%20identifiers.push%28%22abc%22%29%0A%20%20when%20%3ASECOND%0A%20%20%20%20if%20%28identifier%20%3D%20identifiers%5B0%5D%29%0A%20%20%20%20%20%20puts%20identifier%0A%20%20%20%20end%0A%20%20end%0Aend%0A)

```ruby
index = 0
lexed = [:FIRST, :SECOND]
length = lexed.length

identifiers = []

while index < length
  token = lexed[index]
  index += 1

  case token
  when :FIRST

    identifiers.push("abc")
  when :SECOND
    if (identifier = identifiers[0])
      puts identifier
    end
  end
end
```

#### Observed output

```
editor.rb:17: This code is unreachable https://srb.help/7006
    17 |      puts identifier
              ^^^^^^^^^^^^^^^
    editor.rb:16: This condition was always falsy (NilClass)
    16 |    if (identifier = identifiers[0])
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got NilClass originating from:
    editor.rb:16:
    16 |    if (identifier = identifiers[0])
                             ^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

No errors. Since in the first loop, the array is being filled, in the second one the array is not empty anymore.

**Comment by froydnj** [comment] 2024-12-23 14:17
The immediate fix is that you need a `T.let` on `identifiers` to let Sorbet know its type up front: [sorbet.run](https://sorbet.run/#index%20%3D%200%0Alexed%20%3D%20%5B%3AFIRST%2C%20%3ASECOND%5D%0Alength%20%3D%20lexed.length%0A%0Aidentifiers%20%3D%20T.let%28%5B%5D%2C%20T%3A%3AArray%5BString%5D%29%0A%0Awhile%20index%20%3C%20length%0A%20%20token%20%3D%20lexed%5Bindex%5D%0A%20%20index%20%2B%3D%201%0A%0A%20%20case%20token%0A%20%20when%20%3AFIRST%0A%0A%20%20%20%20identifiers.push%28%22abc%22%29%0A%20%20when%20%3ASECOND%0A%20%20%20%20if%20%28identifier%20%3D%20identifiers%5B0%5D%29%0A%20%20%20%20%20%20puts%20identifier%0A%20%20%20%20end%0A%20%20end%0Aend%0A).  Sorbet sees `identifiers` being initialized as a zero-element array, and does not model the modifications to it done by `push`.

I do agree Sorbet could be more helpful in telling you how to potentially fix the problem, though.

**Comment by Earlopain** [comment] 2024-12-23 14:37
Appreciate the prompt reply. In this case, the code doesn't actually employ sorbet during runtime so unfortunately I'm not able to give it such hints.

**Comment by froydnj** [comment] 2024-12-23 14:43
> Appreciate the prompt reply. In this case, the code doesn't actually employ sorbet during runtime so unfortunately I'm not able to give it such hints.

That's unfortunate.  In that case, you have two options:

* initialize `identifiers` with `Array.new` so Sorbet will consider it to not be fixed as a zero-element array; or
* use [`T.unsafe`](https://sorbet.org/docs/troubleshooting#tunsafe) on the access: `T.unsafe(identifiers)[0]`

**Comment by Earlopain** [comment] 2024-12-23 14:48
> initialize identifiers with Array.new so Sorbet will consider it to not be fixed as a zero-element array

Great tip, thanks for the help!

**Comment by jez** [comment] 2024-12-23 16:46
Duplicate of #4331

**Closed** 2024-12-23 16:46 UTC
Labels: bug
