### ISSUE TITLE
`srb init` fails with an existing rails app when generating symbol table

### ISSUE THREAD

**Issue by AnIrishDuck** [sorbet/sorbet#1276] opened 2019-07-11 22:00 UTC
I've solved all the obvious issues with my project, and now I've been stumped for a while:

```
Generating /tmp/d20190710-5951-1ohisfh/reflection.rbi with 8423 modules and 141 aliases
Printing your code's symbol table into /tmp/d20190710-5951-1ohisfh/from-source.json
/home/docker/.gem/ruby/2.4.0/gems/sorbet-0.4.4413/lib/hidden-definition-finder.rb:117:in `write_constants': Your source can't be read by Sorbet. (RuntimeError)
You can try `find . -type f | xargs -L 1 -t bundle exec srb tc --no-config --error-white-list 1000` and hopefully the last file it is processing before it dies is the culprit.
If not, maybe the errors in this file will help: /tmp/d20190711-155-11qm7ib/from-source.json.err
	from /home/docker/.gem/ruby/2.4.0/gems/sorbet-0.4.4426/lib/hidden-definition-finder.rb:47:in `main'
	from /home/docker/.gem/ruby/2.4.0/gems/sorbet-0.4.4426/lib/hidden-definition-finder.rb:38:in `main'
	from /home/docker/.gem/ruby/2.4.0/gems/sorbet-0.4.4426/bin/srb-rbi:229:in `block in make_step'
	from /home/docker/.gem/ruby/2.4.0/gems/sorbet-0.4.4426/bin/srb-rbi:121:in `init'
	from /home/docker/.gem/ruby/2.4.0/gems/sorbet-0.4.4426/bin/srb-rbi:196:in `main'
	from /home/docker/.gem/ruby/2.4.0/gems/sorbet-0.4.4426/bin/srb-rbi:234:in `<main>'
```

I've tried running the suggested command (`find . -type f | xargs -L 1 -t bundle exec srb tc --no-config --error-white-list 1000`). No individual `bundle exec srb tc` exits with errors:

```
docker@11b635da953a:/usr/src/app$ find . -type f | xargs -L 1 -t bundle exec srb tc --no-config --error-white-list 1000 2>&1 | grep -v 'No errors' | grep -v 'bundle exec'
docker@11b635da953a:/usr/src/app$
```

Here's the output of `from-source.json.err`:

```
You must pass either `-e` or at least one folder or ruby file.

Typechecker for Ruby
Usage:
  sorbet [OPTION...] <path 1> <path 2> ...

  -e, string     Parse an inline ruby string (default: )
  -q, --quiet    Silence all non-critical errors
  -v, --verbose  Verbosity level [0-3]
  -h,            Show short help
      --help     Show long help
      --version  Show version
```

I've traced the failure down to [this file](https://github.com/sorbet/sorbet/blob/8f29af2bd014c50d9612835cfa0da536820361e6/gems/sorbet/lib/hidden-definition-finder.rb#L102). What I don't understand is this command that's getting forked:

```
File.realpath("#{__dir__}/../bin/srb"),
        'tc',
        '--print=symbol-table-full-json',
        '--stdout-hup-hack',
        '--silence-dev-message',
        '--no-error-count',
```

Running this command in a known good environment works. But with our rails application, the same command fails. It insists I pass in a path or `-e` expression to type check, per the error message above. Is it somehow looking for something that's missing in this project?

I've been dead in the water for a while, and feel like I'm missing something obvious.

**Comment by jasnow** [comment] 2019-07-11 23:00
What is your OS and hardware versions?

**Comment by jasnow** [comment] 2019-07-11 23:01
Tell us what is in this file: /tmp/d20190711-155-11qm7ib/from-source.json.err

**Comment by jasnow** [comment] 2019-07-11 23:12
This is the condition that was true to trigger the **You must pass either `-e` or at least one folder or ruby file.** message:
```
if (raw.count("e") == 0 && opts.inputFileNames.empty() && !opts.runLSP && opts.storeState.empty()) {
```

**Comment by jasnow** [comment] 2019-07-11 23:19
What happens when you run "srb" ?

**Comment by jasnow** [comment] 2019-07-12 12:15
Also what version of Rails?

**Comment by AnIrishDuck** [comment] 2019-07-12 16:07
> What is your OS and hardware versions?

This is on Dinghy, a docker OSX wrapper. Our docker images are based off Ubuntu xenial:

```
docker@9de2da163cf3:/usr/src/app$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

> What happens when you run "srb" with no options?

I get the same error message as before:

```
docker@9de2da163cf3:/usr/src/app$ bundle exec srb
You must pass either `-e` or at least one folder or ruby file.

Typechecker for Ruby
Usage:
  sorbet [OPTION...] <path 1> <path 2> ...

  -e, string     Parse an inline ruby string (default: )
  -q, --quiet    Silence all non-critical errors
  -v, --verbose  Verbosity level [0-3]
  -h,            Show short help
      --help     Show long help
      --version  Show version
```

> Also what version of Rails?

```
docker@9de2da163cf3:/usr/src/app$ ruby -v
ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-linux-gnu]
docker@9de2da163cf3:/usr/src/app$ grep 'rails' Gemfile.lock
    rails (5.0.7.2)
```

**Comment by jasnow** [comment] 2019-07-12 16:42
Nothing yells at me so my next step if it was mine would be to add a few put's before the **if** line:
```
puts "1: #{raw.count("e")}"
puts "2: #{opts.opts.inputFileNames.empty() }"
puts "3: #{opts.runLSP}"
puts; "4: #{opts.storeState.empty()}"
if (raw.count("e") == 0 && opts.inputFileNames.empty() && !opts.runLSP && opts.storeState.empty()) {
```

to back into what is the root cause. Yes, I know I am modifying the code but I will remove it after the experiment.

**Comment by AnIrishDuck** [comment] 2019-07-12 20:09
It looks like that file is C++, so I don't think ruby would work in there.

Looking through the rest of the file, it's hard to imagine why the command exits early in "clean" environments. There's no -e flag, there's no input list of files, the command is not being run in language server protocol mode, and `--store-state` is not getting passed in.

I'm not exactly sure how much is involved in building the `srb` binary, but that seems to be getting a bit too far into the weeds...

**Comment by jasnow** [comment] 2019-07-12 20:12
I agree. Sorry for misleading suggestion.

**Comment by connorshea** [comment] 2019-07-13 22:50
I had this issue when I try to run `bundle exec srb rbi hidden-definitions` to update my hidden-definitions, but as I was writing this, apparently updating sorbet-rails fixed the problem 🤷‍♂

**Comment by ajoneil** [comment] 2019-08-27 05:15
We're also seeing this with developers running Dinghy + xhyve - haven't had a chance to debug it properly yet.

**Comment by dorianmariefr** [comment] 2021-03-20 23:27
Same issue and the suggested command prints a bunch of errors:

```
~/s/socializus> find . -type f | xargs -L 1 -t bundle exec srb tc --no-config --isolate-error-code 1000
bundle exec srb tc --no-config --isolate-error-code 1000 ./sorbet/config
ERROR:  While executing gem ... (OptionParser::InvalidArgument)
    invalid argument: -v 
/Users/dorianmariefr/.rvm/gems/ruby-2.7.2/bundler/gems/sorbet-548807710587/gems/sorbet/bin/srb: line 109: /libexec/sorbet: No such file or directory
bundle exec srb tc --no-config --isolate-error-code 1000 ./sorbet/rbi/gems/rb-fsevent.rbi
ERROR:  While executing gem ... (OptionParser::InvalidArgument)
    invalid argument: -v 
/Users/dorianmariefr/.rvm/gems/ruby-2.7.2/bundler/gems/sorbet-548807710587/gems/sorbet/bin/srb: line 109: /libexec/sorbet: No such file or directory
bundle exec srb tc --no-config --isolate-error-code 1000 ./sorbet/rbi/gems/easy_translate.rbi
ERROR:  While executing gem ... (OptionParser::InvalidArgument)
    invalid argument: -v 
/Users/dorianmariefr/.rvm/gems/ruby-2.7.2/bundler/gems/sorbet-548807710587/gems/sorbet/bin/srb: line 109: /libexec/sorbet: No such file or directory
bundle exec srb tc --no-config --isolate-error-code 1000 ./sorbet/rbi/gems/activerecord.rbi
```

**Comment by jez** [comment] 2022-07-27 20:56
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca

**Closed by jez** 2022-07-27 20:56 UTC
Labels: feedback, srb
