### ISSUE TITLE
Type narrowing not working on union type of classes

### ISSUE THREAD

**Issue by paracycle** [sorbet/sorbet#4008] opened 2021-02-17 19:28 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%3B%20end%0Aclass%20B%3B%20end%0Aclass%20C%3B%20end%0A%0Afoo%20%3D%20T.let(%0A%20%20T.unsafe(nil)%2C%20%0A%20%20T.any(T.class_of(A)%2C%20T.class_of(B)%2C%20T.class_of(C))%0A)%0A%0Aif%20foo%20%3D%3D%20B%0A%20%20T.reveal_type(foo)%20%23%20this%20is%20fine%0Aelse%0A%20%20T.reveal_type(foo)%20%23%20why%20does%20this%20still%20have%20%60T.class_of(B)%60%20in%20it%3F%0Aend)

```ruby
# typed: true

class A; end
class B; end
class C; end

foo = T.let(
  T.unsafe(nil), 
  T.any(T.class_of(A), T.class_of(B), T.class_of(C))
)

if foo == B
  T.reveal_type(foo) # this is fine
else
  T.reveal_type(foo) # why does this still have `T.class_of(B)` in it?
end
```

#### Observed output

```
editor.rb:15: Revealed type: T.any(T.class_of(A), T.class_of(B), T.class_of(C)) https://srb.help/7014
    15 |  T.reveal_type(foo) # why does this still have `T.class_of(B)` in it?
          ^^^^^^^^^^^^^^^^^^
  Got T.any(T.class_of(A), T.class_of(B), T.class_of(C)) originating from:
    editor.rb:7:
     7 |foo = T.let(
     8 |  T.unsafe(nil), 
     9 |  T.any(T.class_of(A), T.class_of(B), T.class_of(C))
    10 |)

editor.rb:13: Revealed type: T.class_of(B) https://srb.help/7014
    13 |  T.reveal_type(foo) # this is fine
          ^^^^^^^^^^^^^^^^^^
  Got T.class_of(B) originating from:
    editor.rb:7:
     7 |foo = T.let(
     8 |  T.unsafe(nil), 
     9 |  T.any(T.class_of(A), T.class_of(B), T.class_of(C))
    10 |)
    editor.rb:12:
    12 |if foo == B
           ^^^^^^^^
Errors: 2 
```

#### Expected behavior

The expected behaviour is for the type of `foo` to be `T.any(T.class_of(A), T.class_of(C))` in the `else` branch:

```
editor.rb:15: Revealed type: T.any(T.class_of(A), T.class_of(C)) https://srb.help/7014
    15 |  T.reveal_type(foo) # why does this still have `T.class_of(B)` in it?
          ^^^^^^^^^^^^^^^^^^
  Got T.any(T.class_of(A), T.class_of(C)) originating from:
    editor.rb:7:
     7 |foo = T.let(
     8 |  T.unsafe(nil), 
     9 |  T.any(T.class_of(A), T.class_of(B), T.class_of(C))
    10 |)

editor.rb:13: Revealed type: T.class_of(B) https://srb.help/7014
    13 |  T.reveal_type(foo) # this is fine
          ^^^^^^^^^^^^^^^^^^
  Got T.class_of(B) originating from:
    editor.rb:7:
     7 |foo = T.let(
     8 |  T.unsafe(nil), 
     9 |  T.any(T.class_of(A), T.class_of(B), T.class_of(C))
    10 |)
    editor.rb:12:
    12 |if foo == B
           ^^^^^^^^
Errors: 2 
```

**Comment by jez** [comment] 2022-08-14 20:32
Duplicate of #5416

**Closed by jez** 2022-08-14 20:32 UTC
Labels: bug
