### ISSUE TITLE
LSP: documentSymbols crash

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#254] opened 2019-04-09 21:26 UTC
```
std::__1::__throw_out_of_range(char const*) (in sorbet) (stdexcept:0)
sorbet::core::Loc::source(sorbet::core::GlobalState const&) const (in sorbet) (string:1784)
sorbet::core::Symbol::argumentName(sorbet::core::GlobalState const&) const (in sorbet) (Symbols.cc:0)
sorbet::realmain::lsp::methodDetail(sorbet::core::GlobalState const&, sorbet::core::SymbolRef, sorbet::core::TypePtr, sorbet::core::TypePtr, std::__1::shared_ptr<sorbet::core::TypeConstraint>) (in sorbet) (string:1427)
sorbet::realmain::lsp::symbolRef2DocumentSymbol(sorbet::core::GlobalState const&, sorbet::core::SymbolRef, sorbet::core::FileRef) (in sorbet) (memory:2621)
sorbet::realmain::lsp::symbolRef2DocumentSymbolWalkMembers(sorbet::core::GlobalState const&, sorbet::core::SymbolRef, sorbet::core::FileRef, std::__1::vector<std::__1::unique_ptr<sorbet::realmain::lsp::DocumentSymbol, std::__1::default_delete<sorbet::realmain::lsp::DocumentSymbol> >, std::__1::allocator<std::__1::unique_ptr<sorbet::realmain::lsp::DocumentSymbol, std::__1::default_delete<sorbet::realmain::lsp::DocumentSymbol> > > >&) (in sorbet) (memory:2637)
sorbet::realmain::lsp::symbolRef2DocumentSymbol(sorbet::core::GlobalState const&, sorbet::core::SymbolRef, sorbet::core::FileRef) (in sorbet) (memory:2621)
sorbet::realmain::lsp::LSPLoop::handleTextDocumentDocumentSymbol(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >, sorbet::realmain::lsp::MessageId const&, sorbet::realmain::lsp::DocumentSymbolParams const&) (in sorbet) (memory:2637)
sorbet::realmain::lsp::LSPLoop::processRequestInternal(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >, sorbet::realmain::lsp::LSPMessage const&) (in sorbet) (variant:697)
sorbet::realmain::lsp::LSPLoop::processRequest(std::__1::unique_ptr<sorbet::core::GlobalState, std::__1::default_delete<sorbet::core::GlobalState> >, sorbet::realmain::lsp::LSPMessage const&) (in sorbet) (memory:2649)
sorbet::realmain::lsp::LSPLoop::runLSP() (in sorbet) (memory:2642)
sorbet::realmain::realmain(int, char**) (in sorbet) (memory:2642)
main (in sorbet) (main.cc:0)
start (in libdyld.dylib) + 1
```

on 6cbddb9db746364c00bd6f920f0f23d826d4f54a

**Comment by jez** [comment] 2024-03-29 18:41
Closing because can't reproduce. Was probably a fast path loc bug but we fixed a ton of those since 2019

**Closed by jez** 2024-03-29 18:41 UTC
Labels: bug, IDE, crash
