### ISSUE TITLE
Unexpected unreachable code error when comparing float and integer

### ISSUE THREAD

**Issue by DanielGilchrist** [sorbet/sorbet#6276] opened 2022-08-21 12:01 UTC
#### Input
[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0A%23%23%23%20Example%20in%20method%20%23%23%23%0Asig%20%7Bparams%28n%3A%20T.any%28Integer%2C%20Float%29%29.void%7D%0Adef%20some_method%28n%29%0A%20%20to_i%20%3D%20n.to_i%0A%20%20to_f%20%3D%20n.to_f%20%0A%0A%20%20if%20to_i%20%3D%3D%20to_f%0A%20%20%20%20to_i%20%23%20this%20is%20reachable%20with%20%60some_method%281.0%29%60%20as%201%20%3D%3D%201.0%20%3D%3E%20true%0A%20%20else%0A%20%20%20%20to_f%0A%20%20end%0Aend%0A%0A%23%20Example%20call%20where%20%22unreachable%20code%22%20would%20be%20incorrect%0Asome_method%281.0%29%0A%0A%23%23%23%20Example%20in%20global%20scope%20%23%23%23%0Ato_i%20%3D%201.0.to_i%0Ato_f%20%3D%201.0.to_f%20%0A%0A%23%20Errors%20with%20assignment%0Avalue%20%3D%20if%20to_i%20%3D%3D%20to_f%0A%20%20to_i%0Aelse%0A%20%20to_f%0Aend%0A%0A%23%20Doesn't%20error%20without%20assignment%0Aif%20to_i%20%3D%3D%20to_f%0A%20%20to_i%0Aelse%0A%20%20to_f%0Aend%0A)

```ruby
# typed: true
extend T::Sig

### Example in method ###
sig {params(n: T.any(Integer, Float)).void}
def some_method(n)
  to_i = n.to_i
  to_f = n.to_f 

  if to_i == to_f
    to_i # this is reachable with `some_method(1.0)` as 1 == 1.0 => true
  else
    to_f
  end
end

# Example call where "unreachable code" would be incorrect
some_method(1.0)

### Example in global scope ###
to_i = 1.0.to_i
to_f = 1.0.to_f 

# Errors with assignment
value = if to_i == to_f
  to_i
else
  to_f
end

# Doesn't error without assignment
if to_i == to_f
  to_i
else
  to_f
end
```

#### Observed output

```
editor.rb:11: This code is unreachable https://srb.help/7006
    11 |    to_i # this is reachable with `some_method(1.0)` as 1 == 1.0 => true
            ^^^^
    editor.rb:10: This condition was always falsy (T::Boolean)
    10 |  if to_i == to_f
             ^^^^^^^^^^^^
  Got T::Boolean originating from:
    editor.rb:10:
    10 |  if to_i == to_f
             ^^^^^^^^^^^^

editor.rb:26: This code is unreachable https://srb.help/7006
    26 |  to_i
          ^^^^
    editor.rb:25: This condition was always falsy (T::Boolean)
    25 |value = if to_i == to_f
                   ^^^^^^^^^^^^
  Got T::Boolean originating from:
    editor.rb:25:
    25 |value = if to_i == to_f
                   ^^^^^^^^^^^^
Errors: 2
```

#### Expected behavior

I wouldn't expect comparing `from_i` and `from_f` to result in an unreachable code error in either case as there are cases where it could be reached
- - -

**Comment by jez** [comment] 2022-08-21 15:58
Duplicate of #6194

**Closed by jez** 2022-08-21 15:58 UTC
Labels: bug, unconfirmed
