### ISSUE TITLE
`T.must` has unexpected behavior with `+=`

### ISSUE THREAD

**Issue by angeqyang** [sorbet/sorbet#4007] opened 2021-02-17 18:49 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#begin%0A%20%20retries%20%7C%7C%3D%200%0A%20%20raise%20'error'%20if%20retries%20%3C%203%0Arescue%20StandardError%0A%20%20T.must(retries)%20%2B%3D%201%0A%20%20retry%0Aend)

```ruby
begin
  retries ||= 0
  raise 'error' if retries < 3
rescue StandardError
  T.must(retries) += 1
  retry
end
```

#### Observed output

```
editor.rb:5: unexpected token tOP_ASGN https://srb.help/2001
     5 |  T.must(retries) += 1
                          ^^

editor.rb:6: No begin block around retry https://srb.help/6001
     6 |  retry
          ^^^^^
Errors: 2
```

#### Expected behavior
I would've expected `T.must(retries) += 1` to parse correctly, especially since it's actually the result of running Sorbet autocorrect on the line `retries += 1`.

The `retry` error doesn't happen on my local machine, I think that's just a playground issue.

- - -

**Comment by jez** [comment] 2022-02-03 22:47
I noticed that this is a dupe of #3370. I like that repro test case slightly better, so I'm closing this one.

**Closed by jez** 2022-02-03 22:47 UTC
Labels: bug
