### ISSUE TITLE
"attr_reader" which implements an abstract method but lacks "override" does not cause error

### ISSUE THREAD

**Issue by iking96** [sorbet/sorbet#4094] opened 2021-03-17 18:02 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20Test%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20interface!%0A%0A%20%20sig%20%7B%20abstract.returns(String)%20%7D%0A%20%20def%20foo%3B%20end%0Aend%0A%0Aclass%20Implementation%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20Test%0A%0A%20%20def%20initialize%0A%20%20%20%20%40foo%20%3D%20T.let('Foo'%2C%20String)%0A%20%20end%0A%0A%20%20sig%20%7B%20returns(String)%20%7D%0A%20%20attr_reader%20%3Afoo%0Aend%0A%0Asig%20%7Bvoid%7D%0Adef%20foo%0A%20%20Implementation.new.foo%0Aend%0A%0Afoo())

```ruby
# typed: true
extend T::Sig

module Test
  extend T::Sig
  extend T::Helpers

  interface!

  sig { abstract.returns(String) }
  def foo; end
end

class Implementation
  extend T::Sig
  include Test

  def initialize
    @foo = T.let('Foo', String)
  end

  sig { returns(String) }
  attr_reader :foo
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

I expected a error indicating that the reader sig was not declared with override. Similar to this:
```
editor.rb:23: Method Implementation#foo implements an abstract method Test#foo but is not declared with override. https://srb.help/5051
    23 |  def foo
          ^^^^^^^
    editor.rb:11: defined here
    11 |  def foo; end
          ^^^^^^^
Errors: 1
```

**Comment by jez** [comment] 2022-08-14 21:12
Duplicate of #1841

**Closed by jez** 2022-08-14 21:12 UTC
Labels: bug
