### ISSUE TITLE
Using Enumerable#select with attribute name shouldn't complain about nil attribute

### ISSUE THREAD

**Issue by ashkulz** [sorbet/sorbet#3906] opened 2021-01-18 05:57 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20returns(T.nilable(String))%20%7D%0A%20%20attr_reader%20%3Aname%0A%20%20def%20initialize(name%3Dnil)%0A%20%20%20%20%40name%20%3D%20name%0A%20%20end%0Aend%0A%0Aa%20%3D%20%5BFoo.new%2C%20Foo.new(%22A%22)%5D%0Aa.select(%26%3Aname).sort_by(%26%3Aname)%0A)

```ruby
# typed: true

class Foo
  extend T::Sig

  sig { returns(T.nilable(String)) }
  attr_reader :name
  def initialize(name=nil)
    @name = name
  end
end

a = [Foo.new, Foo.new("A")]
a.select(&:name).sort_by(&:name)
```

#### Observed output

```
editor.rb:14: Returning value that does not conform to block result type https://srb.help/7005
    14 |a.select(&:name).sort_by(&:name)
                                  ^^^^^
  Expected T.any(T::Array[BasicObject], Comparable)
  Got T.nilable(String) originating from:
    editor.rb:14:
    14 |a.select(&:name).sort_by(&:name)
                                  ^^^^^
Errors: 1
```

#### Expected behavior

It should pass, as the `select` is ensuring that it becomes not-nil i.e. `String` instead of `T.nilable(String)`. This didn't use to error out in `0.5.6134` but has started erroring out recently.

**Comment by raffitzz** [comment] 2022-03-03 10:18
I have exact the same problem but with Time.

`colletion.map { |val| map_val(val) }.max_by(&:date)`

I get this error:
`Expected T.any(T::Array[BasicObject], Comparable) but found T.nilable(Time) for block result type https://srb.help/7005`

No idea how to solve this and seems pretty much the same issue.

**Comment by jez** [comment] 2022-08-06 19:50
I don't think we're going to be able to support this. The problem is that there is no way for Sorbet to ascribe a type to the intermediate result of `a.select(&:name)` that remembers anything about the types things contained on the elements of the array. The result type is simply `T::Array[Foo]`--Sorbet does not have some sort of syntax that would allow the type to be `T::Array[Foo but if you call #name it won't be nil]`.

Even TypeScript, which does have some more powerful, related features (type predicates) [doesn't even support this use case](https://www.typescriptlang.org/play?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBWCMQTCABi8AwAG9FCUSpwGMh8ldUJROCMAD6gLjcSDJDKQbgAbiZzIQnEEXPYsHQZAAFKz2ZzuXyBTxhaLuABKUCM5kmgSCAJqlAAXn6bMgkpNAF9FM7FMkuIqGpkpvpiFzhsqAPqrDlyzWG+mu93meqNcGrNkLSDK5J0gqgWnwADaAF0I1KSu4jjBIIqxaAban4OaRdAFCqU4arQA+HEWu36h3MwQlsvcAKIBgEZWNiut1A+wR+zUp9vIfX6l1AA).

I appreciate the sentiment, as this kind of code would be nice to be able to write concisely. Unfortunately I don't think it's going to have an obvious solution any time soon, so I'm going to close the issue. Thanks for the idea.

**Closed by jez** 2022-08-06 19:50 UTC
Labels: bug, unconfirmed
