### ISSUE TITLE
Add support for Ruby 2.6.5

### ISSUE THREAD

**Issue by marisveide** [sorbet/sorbet#2343] opened 2019-12-16 17:01 UTC
### Problem

At the moment, I can add sorbet gem only to `ruby 2.6.3` project.
But our project is on `ruby 2.6.5`, and sorbet gem doesn't get added there by the bundler, as apparently it is set to be working only with `2.6.3`.

### Proposed solution

Please, make sorbet work also on `ruby 2.6.5`.

Thanks!

**Comment by jez** [comment] 2019-12-16 22:02
I can't reproduce this.

```
mkdir empty && cd empty
echo '2.6.5' > .ruby-version
echo $'source "https://rubygems.org"\ngem "sorbet", group: :development\ngem "sorbet-runtime"' > Gemfile
rbenv install
rbenv rehash
bundle install
```

Works fine for me.

Closing as unreproducible.

**Closed by jez** 2019-12-16 22:02 UTC
Labels: enhancement, unconfirmed

**Comment by bagmangood** [comment] 2019-12-17 20:21
FWIW I'm experiencing the same issue in builds (not on my mac host machine), but when running in a container

```bash
docker run --rm -it ruby:2.6 gem install sorbet
```

Results in 

> ERROR:  Could not find a valid gem 'sorbet-static' (= 0.4.5146) (required by 'sorbet' (>= 0)) in any repository
> ERROR:  Possible alternatives: sorbet-static

**Comment by bagmangood** [comment] 2019-12-17 20:25
I would guess that https://github.com/sorbet/sorbet/issues/2250 is the root source of the issue, and it doesn't look like there is a linux build up on rubygems right now

<img width="466" alt="Screen Shot 2019-12-17 at 12 25 26 PM" src="https://user-images.githubusercontent.com/261604/71031520-5b910480-20c8-11ea-901f-703597d58d27.png">

**Comment by marisveide** [comment] 2019-12-18 08:45
I have the same error when running on ruby `2.6.5` (using `rvm` on MacOS).

```
maris@Maris-Mac ruby-types % bundle add sorbet    
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Could not find sorbet-static-0.4.5158-universal-darwin-14 in any of the sources
```

**Comment by bagmangood** [comment] 2019-12-18 18:40
@marisveide that's interesting because rubygems has that upright now 🤔 https://rubygems.org/gems/sorbet-static/versions/0.4.5158-universal-darwin-14

**Comment by bagmangood** [comment] 2019-12-18 23:19
workaround I just found (for gems or other places where you can't/shouldn't specify  a version): explicitly require all of them gems (rather than implicitly), i.e. 
```ruby
  spec.add_development_dependency 'sorbet'
  spec.add_development_dependency 'sorbet-static'
```

or

```ruby
gem 'sorbet'
gem 'sorbet-static'
```

Bundler will only install a version that satisfies all dependencies (and can find)
