### ISSUE TITLE
Build `T::Class[AttachedClass]`

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#62] opened 2019-01-16 22:07 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20M%0A%20%20def%20some_instance_method%3B%20end%0Aend%0A%0Aclass%20A%0A%20%20include%20M%0Aend%0A%0AT.let(A.new%2C%20M)%0A%0A%23%20There%20is%20no%20type%20to%20write%20on%20the%20RHS%20that's%20valid%0AT.let(A%2C%20T.class_of(M))%0A%0A%23%20We'd%20like%20to%20implement%20something%20to%20make%20this%20work%0A%23%20T.let(A%2C%20T%3A%3AClass%5BM%5D)%0A%0A%23%20sig%20%7Bparams(klass%3A%20T%3A%3AClass%5BM%5D).void%7D%0Asig%20%7Bparams(klass%3A%20Class).void%7D%0Adef%20example1(klass)%0A%20%20x%20%3D%20klass.new%0A%20%20T.reveal_type(x)%20%20%20%20%20%20%20%20%23%20ideally%3A%20%60M%60%0A%20%20x.some_instance_method%20%20%23%20ideally%3A%20no%20error%0Aend)

```ruby
# typed: true
extend T::Sig

module M
  def some_instance_method; end
end

class A
  include M
end

T.let(A.new, M)

# There is no type to write on the RHS that's valid
T.let(A, T.class_of(M))

# We'd like to implement something to make this work
# T.let(A, T::Class[M])

# sig {params(klass: T::Class[M]).void}
sig {params(klass: Class).void}
def example1(klass)
  x = klass.new
  T.reveal_type(x)        # ideally: `M`
  x.some_instance_method  # ideally: no error
end
```

#### Observed output

```
editor.rb:24: Revealed type: Object https://srb.help/7014
    24 |  T.reveal_type(x)        # ideally: `M`
          ^^^^^^^^^^^^^^^^
  Got Object originating from:
    editor.rb:23:
    23 |  x = klass.new
              ^^^^^^^^^

editor.rb:25: Method some_instance_method does not exist on Object https://srb.help/7003
    25 |  x.some_instance_method  # ideally: no error
          ^^^^^^^^^^^^^^^^^^^^^^
  Got Object originating from:
    editor.rb:23:
    23 |  x = klass.new
              ^^^^^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:25: Replace with singleton_method
    25 |  x.some_instance_method  # ideally: no error
            ^^^^^^^^^^^^^^^^^^^^

editor.rb:15: Argument does not have asserted type T.class_of(M) https://srb.help/7007
    15 |T.let(A, T.class_of(M))
        ^^^^^^^^^^^^^^^^^^^^^^^
  Got T.class_of(A) originating from:
    editor.rb:15:
    15 |T.let(A, T.class_of(M))
              ^
Errors: 3
```

#### Expected behavior

- The commented-out `T.let` holds
- The revealed type of `x` is `M`
- `x.some_instance_method` type checks.

**Comment by akshay-stripe** [comment] 2019-08-22 18:14
subscribing. cc @axyjo

**Comment by manhhung741** [comment] 2019-09-14 23:06
subscribing

**Comment by searls** [comment] 2022-05-20 22:54
I left [this comment](https://github.com/sorbet/sorbet/issues/3856#issuecomment-1132279289) yesterday on #3856. Is it a dupe of #62?

(Either way, this capability would be great for my mocking library, [Mocktail](https://github.com/testdouble/mocktail)! Without it there's not much value in typing)

**Comment by grncdr** [comment] 2022-05-25 11:47
It's a bit unclear to me from the example given whether this actually covers the same use-case as #3856. Specifically this example does not make any use of type parameters.

Does this issue imply that the following signature will be possible?

```rb
sig { type_parameters(:E).param(T::Class[T.type_parameter(:E)]).returns(T.type_parameter(:E)) }
```

If not, I think #3856 is a separate issue.

**Closed** 2023-05-11 23:45 UTC
Labels: enhancement, hard
