### ISSUE TITLE
Allow class_of to operate on generics

### ISSUE THREAD

**Issue by grncdr** [sorbet/sorbet#3856] opened 2021-01-01 16:48 UTC
### Problem

I am trying to write a well-typed event bus, where the `#on` method takes an event class and calls the given block with instances of that class.

[Simplified example](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20EventBus%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20def%20initialize%0A%20%20%20%20%40subscribers%20%3D%20Hash.new%20%7B%20%7Ch%2C%20e%7C%20h%5Be%5D%20%3D%20%5B%5D%20%7D%0A%20%20end%0A%0A%20%20sig%20%7B%0A%20%20%20%20type_parameters(%3AEvent).%0A%20%20%20%20params(%0A%20%20%20%20%20%20event_class%3A%20T.class_of(T.type_parameter(%3AEvent))%2C%0A%20%20%20%20%20%20subscriber%3A%20T.proc.params(event%3A%20T.type_parameter(%3AEvent)).void%2C%0A%20%20%20%20).void%0A%20%20%7D%0A%20%20def%20on(event_class%2C%20%26subscriber)%0A%20%20%20%20%40subscribers%5Bevent_class%5D%20%3C%3C%20subscriber%0A%20%20end%0A%0A%20%20def%20broadcast(event)%0A%20%20%20%20return%20unless%20%40subscribers.key%3F(event.class)%0A%0A%20%20%20%20%40subscribers%5Bevent.class%5D.each%20do%20%7Csubscriber%7C%0A%20%20%20%20%20%20subscriber.call(event)%0A%20%20%20%20end%0A%20%20end%0Aend%0A%0A%0Aclass%20SomeEvent%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%7Bparams(message%3A%20String).void%7D%0A%20%20def%20initialize(message)%0A%20%20%20%20%40message%20%3D%20message%0A%20%20end%0A%0A%20%20sig%20%7Breturns(String)%7D%0A%20%20attr_reader%20%3Amessage%0Aend%0A%0Abus%20%3D%20EventBus.new%0Abus.on(SomeEvent)%20do%20%7Cevent%7C%0A%20%20T.reveal_type(event)%0Aend%0A%0A%0A%0A%0A)

### Proposed solution

I _guess_ what I would expect is for the computation of `T.class_of` to be deferred until there is a concrete type available (in this case, at call-sites for `EventBus#on`).

Alternatively, it might be useful to have a `T.instance_of(Foo)` helper, which results in the return type of `Foo.new`, but in any case one would still need to defer the resolution to the call site of the generic method.

**Comment by searls** [comment] 2022-05-19 22:56
I believe I also have this issue as I attempt to add type-checking to my mocking library [Mocktail](https://github.com/testdouble/mocktail) as @paracycle & @Morriar were teaching me Sorbet at their [RailsConf workshop](https://railsconf.org/program/workshops#session-1307).

Because Mocktail provides functionality to return fake instances of provided types, we need to be able to refer to a generic type's instance & class in the type signature. So I was imagining something like this:

```ruby
sig do
  type_parameters(:E)
    .params(type: T.class_of(T.type_parameter(:E)))
    .returns(T.type_parameter(:E))
end
def self.of(type)
  # …
end
```

Which fails with:

```
T.class_of needs a class or module as its argument
```

Here's a [runnable example](https://sorbet.run/#%23%20typed%3A%20true%0A%0A%0Amodule%20Mocktail%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20%23%20Returns%20an%20instance%20of%20%60type%60%20whose%20implementation%20is%20mocked%20out%0A%20%20sig%20do%0A%20%20%20%20type_parameters%28%3AE%29%0A%20%20%20%20%20%20.params%28type%3A%20T.class_of%28T.type_parameter%28%3AE%29%29%29%0A%20%20%20%20%20%20.returns%28T.type_parameter%28%3AE%29%29%0A%20%20end%0A%20%20def%20self.of%28type%29%0A%20%20%20%20type.new%20%23%20TODO%0A%20%20end%0Aend).

Being able to add meaningful type information to Mocktail would really supercharge its usefulness in test-driven development and providing great messages as invocations are used to drive the creation of new types and methods, so it'd be really awesome to see support for this! 

Thanks for all your hard work 💖

**Comment by searls** [comment] 2022-05-20 22:56
Possible dupe of #62

**Comment by jez** [comment] 2022-05-24 23:09
Yes, this looks like a dupe of #62. Thanks for finding.

**Closed by jez** 2022-05-24 23:09 UTC
Labels: enhancement, unconfirmed
