### ISSUE TITLE
`This code is unreachable` not reported for `return` in an if

### ISSUE THREAD

**Issue by neilparikh** [sorbet/sorbet#7067] opened 2023-06-03 00:05 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Aa%20%3D%20%22foo%22%0A%0Aif%20a.nil%3F%0A%20%20return%0Aend%0A%0Aif%20a.nil%3F%0A%20%20raise%20%22error%22%0Aend%0A%0Aputs%20a)

```ruby
# typed: strict
extend T::Sig

a = "foo"

if a.nil?
  return
end

if a.nil?
  raise "error"
end

puts a
```

#### Observed output

```
editor.rb:11: This code is unreachable https://srb.help/7006
    11 |  raise "error"
          ^^^^^^^^^^^^^
    editor.rb:10: This condition was always falsy (T::Boolean)
    10 |if a.nil?
           ^^^^^^
  Got T::Boolean originating from:
    editor.rb:10:
    10 |if a.nil?
           ^^^^^^
Errors: 1
```

#### Expected behavior

There should be a `This code is unreachable` error reported for line 7 too.

- - -

**Comment by neilparikh** [comment] 2023-06-03 00:10
If we change the program to the following, we do get an error report.
```
# typed: strict
extend T::Sig

a = "foo"

if a.nil?
  a
  return
end

if a.nil?
  raise "error"
end

puts a
```
Here's the CFG for the original program:
<img width="1142" alt="Screenshot 2023-06-02 at 5 07 29 PM" src="https://github.com/sorbet/sorbet/assets/614836/d7de6115-dcdc-4be9-9ce6-3690843e00bc">

And here's the CFG for the new program.
<img width="1138" alt="Screenshot 2023-06-02 at 5 08 36 PM" src="https://github.com/sorbet/sorbet/assets/614836/5f074c1d-03f9-4bc8-b755-4300646c268f">

So it looks like the knowledge that `a` is `T.noreturn` isn't being passed to the `return` block for some reason.

**Comment by jez** [comment] 2023-06-03 05:38
Dupe of https://github.com/sorbet/sorbet/issues/621

**Closed by jez** 2023-06-03 05:38 UTC
Labels: bug
