### ISSUE TITLE
Sorbet should flag when a private method is accessed outside of the class

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#1814] opened 2019-09-19 22:05 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20attr_reader%20%3Avc%0A%0A%20%20def%20vc_2%3B%20end%0Aend%0A%0Aclass%20B%20%3C%20A%0A%20%20private%20%3Avc%0A%20%20private%20%3Avc_2%0A%0A%20%20private%20%0A%20%20def%20vc_3%3B%20end%0Aend%0A%0AA.new.vc%0AB.new.vc%0A%0AA.new.vc_2%0AB.new.vc_2%0A%0AB.new.vc_3%0A%0A)

```ruby
# typed: true
class A
  attr_reader :vc

  def vc_2; end
end

class B < A
  private :vc
  private :vc_2

  private 
  def vc_3; end
end

A.new.vc
B.new.vc

A.new.vc_2
B.new.vc_2

B.new.vc_3

```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

It should flag people to not use private method, or treat private method doesn't exist
- - -

**Comment by manhhung741** [comment] 2019-09-19 22:06
cc @annieechen

**Comment by jez** [comment] 2019-09-20 02:58
Dupe of #1011

**Closed by jez** 2019-09-20 02:58 UTC
Labels: bug
