### ISSUE TITLE
Abstract class methods can be implemented as Struct consts without any errors

### ISSUE THREAD

**Issue by bhargavrpatel** [sorbet/sorbet#5581] opened 2022-04-05 13:41 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0Aextend%20T%3A%3AHelpers%0A%0Aclass%20Base%20%3C%20T%3A%3AInexactStruct%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20abstract!%0A%0A%20%20sig%20%7B%20abstract.returns%28Integer%29%20%7D%0A%20%20def%20test_meth%3B%20end%0Aend%0A%0A%0Aclass%20Implementation%20%3C%20Base%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%0A%20%20%23%20Set%20it%20as%20a%20constant%20rather%20than%20delcaring%20as%20override%20works..%0A%20%20const%20%3Atest_meth%2C%20String%2C%20default%3A%20%22something%22%0Aend%0A%0Aa%20%3D%20Implementation.new%28test_meth%3A%20%22passing%22%29%0Aputs%20a.test_meth)

```ruby
# typed: true
extend T::Sig
extend T::Helpers

class Base < T::InexactStruct
  extend T::Sig
  extend T::Helpers

  abstract!

  # NOTE: We've declared this as returning an Integer
  sig { abstract.returns(Integer) }
  def test_meth; end
end


class Implementation < Base
  extend T::Sig
  extend T::Helpers

  # Set it as a constant rather than delcaring as override works..
  # NOTE: We've declared this as a String
  const :test_meth, String, default: "something"
end

a = Implementation.new(test_meth: "passing")
puts a.test_meth
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

We should not be able to instantiate the Abstract class as we have not implemented `test_meth` method, but simply have a struct `const` in its place. Alternatively, if we do want to allow the behaviour (it does seem kind of nice to have this) of allowing abstract methods that result a static response be inputs in implementation classes, we need to do type checking to ensure that `test_meth` is an Integer and not a String.

--- 

This seems like a bug specific to parent classes being `InExactStruct`

**Comment by froydnj** [comment] 2022-04-06 13:42
This is unfortunate, but it is expected behavior.

Sorbet internally considers `const :test_meth, String, default: "something"` to be ~equivalent to writing

```ruby
def test_meth
  @test_meth
end
```

But Sorbet only considers classes that inherit from `T::Struct` as wanting the associated methods for `prop` and `const` to be typed.  Therefore there's no type associated with `@test_meth` and no `sig` associated with `test_meth`.  So `test_meth` returns `T.untyped` and is compatible with the abstract method returning `Integer`.  However, as you note, the types would not be correct at runtime, and sorbet-runtime should be able to raise an error in that case.

Fixing this would be possible, but it would be a significant change in how Sorbet treats `prop` and `const`.

**Comment by jez** [comment] 2022-08-14 02:47
Duplicate of #1694

**Closed by jez** 2022-08-14 02:47 UTC
Labels: bug
