### ISSUE TITLE
Sorbet doesn't warn about a type in a case statement that isn't set in a sig

### ISSUE THREAD

**Issue by streeter** [sorbet/sorbet#5692] opened 2022-04-25 17:15 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Aclass%20Access%20%3C%20T%3A%3AEnum%0A%20%20enums%20do%0A%20%20%20%20Foo%20%3D%20new%0A%20%20%20%20Bar%20%3D%20new%0A%20%20end%0Aend%0A%0Asig%20%7Bparams%28access%3A%20T.nilable%28Access%29%29.returns%28Access%29%7D%0Adef%20foo%28access%3A%29%0A%20%20case%20access%0A%20%20when%20true%0A%20%20%20%20Access%3A%3AFoo%0A%20%20when%20false%2C%20nil%0A%20%20%20%20Access%3A%3ABar%0A%20%20when%20Access%0A%20%20%20%20access%0A%20%20else%0A%20%20%20%20T.absurd%28access%29%0A%20%20end%0Aend%0A)

```ruby
# typed: strict
extend T::Sig

class Access < T::Enum
  enums do
    Foo = new
    Bar = new
  end
end

sig {params(access: T.nilable(Access)).returns(Access)}
def foo(access:)
  case access
  when true
    Access::Foo
  when false, nil
    Access::Bar
  when Access
    access
  else
    T.absurd(access)
  end
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

I'd expect there be at least an error telling me that the `true` case is not required or unreachable, and ideally that `false` is also not something that can be used.

**Comment by jez** [comment] 2022-04-25 18:00
Dupe of #621

**Closed by jez** 2022-04-25 18:00 UTC
Labels: bug, unconfirmed

**Comment by jez** [comment] 2022-04-25 19:17
(Unfortunately #621 is a bit tricky to fix 😢)

**Comment by streeter** [comment] 2022-04-25 20:10
I believe it! Also, I should've searched for this as an existing issue :D #sorbet made me think it was a new one
