### ISSUE TITLE
IDE: Autocomplete trips an ENFORCE sometimes

### ISSUE THREAD

**Issue by jvilk-stripe** [sorbet/sorbet#430] opened 2019-05-08 22:48 UTC
#### Input

Unknown. Found in Sorbet logs.

#### Observed output

```
[2019-04-11 15:42:43.224] [consoleAndFile] [error] Exception::raise(): should never happen

[2019-04-11 15:42:43.231] [consoleAndFile] [error] Backtrace:
  #3 0x42dddd sorbet::realmain::lsp::getResultType()
  #4 0x42d2dc sorbet::realmain::lsp::methodDetail()
  #5 0x4446ca sorbet::realmain::lsp::LSPLoop::getCompletionItem()
  #6 0x4467c3 sorbet::realmain::lsp::LSPLoop::handleTextDocumentCompletion()
  #7 0x43ad1f sorbet::realmain::lsp::LSPLoop::processRequestInternal()
  #8 0x439199 sorbet::realmain::lsp::LSPLoop::processRequest()
  #9 0x42e793 sorbet::realmain::lsp::LSPLoop::runLSP()
  #10 0x3da52b sorbet::realmain::realmain()
  #11 0x3d896b main
  #12 0x7f3d87d1af45
  #13 0x396029 _start
```

#### Expected behavior

Doesn't do that.

**Comment by jez** [comment] 2019-11-26 19:42
Dupe of #681

**Closed by jez** 2019-11-26 19:42 UTC
Labels: IDE, bug
