### ISSUE TITLE
too optimistic typing for fields

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#42] opened 2019-01-16 22:02 UTC
https://sorbet.run/#def%20pollute_s%0A%20%20%40s%20%3D%20%22no%22%0Aend%0A%0Adef%20foo%0A%20%20%40s%20%3D%201%0A%20%20pollute_s()%0A%20%20T.reveal_type(%40s)%0Aend

 

should not pass typechecking

Comments:
11/Nov/18 7:12 AM;jez;Why is this? I thought that we always treated fields as T.untyped unless they were explicitly annotated?

12/Nov/18 12:29 AM;dmitry;Depending on if they were explicitly declared they start as T.untyped or with declared type indeed.

But after they start with that type, we map them to a local variable per method, similarly how we do with constants. And this does not account for a fact that this field can be mutated as other methods are  invoked.

Originally reported by @dmitry-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1401

**Comment by jez** [comment] 2020-12-21 22:51
Duplicate of #1374

**Closed by jez** 2020-12-21 22:51 UTC
Labels: hard
