### ISSUE TITLE
Overriding initialize in Struct block result in error

### ISSUE THREAD

**Issue by XrXr** [sorbet/sorbet#485] opened 2019-05-10 21:01 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#A%20%3D%20Struct.new(%3Afoo)%20do%0A%20%20def%20initialize(how%3A%2034)%0A%20%20%20%20super(how)%0A%20%20end%0Aend%0A%0Aputs%20A.new(how%3A%20234234))

```ruby
A = Struct.new(:foo) do
  def initialize(how: 34)
    super(how)
  end
end

puts A.new(how: 234234)
```

#### Observed output

```
editor.rb:1: Method A#initialize redefined with mismatched argument attribute isKeyword. Expected: true, got: false https://sorbet.org/docs/error-reference#4010
     1 |A = Struct.new(:foo) do
     2 |  def initialize(how: 34)
     3 |    super(how)
     4 |  end
     5 |end
    editor.rb:2: Previous definition
     2 |  def initialize(how: 34)
          ^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

No errors. This code executes just fine.

- - -

This has been a problem for a while I guess, but I got hit by it after trying to upgrade our monolith to latest master. We use Struct in this manner quite a bit and it'd be nice if it worked.

This used to work and regressed after #400, I think.

Edit: it looks like Struct#initialize is the only method that you can use super with the block form:

```ruby
A = Struct.new(:foo) do
  def initialize(how:)
    super(how)
  end

  def foo
    super
  end
end

puts A.new(how: 234234)      #=> #<struct A foo=234234>
puts A.new(how: 234234).foo  # NoMethodError: super: no superclass method `foo'
```

**Comment by jez** [comment] 2019-08-23 23:22
I think we're going to close this as "feature not a bug." `Struct`s should be dumb data wrappers, so even doing special things in the initialize is questionable. The fact that Sorbet makes it harder to declare an initialize method for a struct means there's less room for misuse. Especialy so given the understanding that this is not a super pressing request.

**Closed by jez** 2019-08-23 23:22 UTC
Labels: bug
