### ISSUE TITLE
Exhaustiveness checking incorrect with sealed classes and generics

### ISSUE THREAD

**Issue by pantera-stripe** [sorbet/sorbet#3242] opened 2020-06-30 21:09 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Parent%0A%20%20extend%20T%3A%3AGeneric%0A%20%20extend%20T%3A%3AHelpers%0A%20%20sealed!%0A%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20class%20A%3B%20extend%20T%3A%3AGeneric%3B%20include%20Parent%3B%20Elem%20%3D%20type_member%3B%20end%0A%20%20class%20B%3B%20extend%20T%3A%3AGeneric%3B%20include%20Parent%3B%20Elem%20%3D%20type_member%3B%20end%0A%20%20class%20C%3B%20extend%20T%3A%3AGeneric%3B%20include%20Parent%3B%20Elem%20%3D%20type_member%3B%20end%0Aend%0A%0Afoo%20%3D%20T.let(Parent%3A%3AB%5BInteger%5D.new%2C%20Parent%5BInteger%5D)%20%0A%0Acase%20foo%0Awhen%20Parent%3A%3AA%0Awhen%20Parent%3A%3AB%0Awhen%20Parent%3A%3AC%0Aelse%20T.absurd(foo)%0Aend)

```ruby
# typed: true
module Parent
  extend T::Generic
  extend T::Helpers
  sealed!

  Elem = type_member

  class A; extend T::Generic; include Parent; Elem = type_member; end
  class B; extend T::Generic; include Parent; Elem = type_member; end
  class C; extend T::Generic; include Parent; Elem = type_member; end
end

foo = T.let(Parent::B[Integer].new, Parent[Integer]) 

case foo
when Parent::A
when Parent::B
when Parent::C
else T.absurd(foo)
end
```

#### Observed output

```
editor.rb:20: Control flow could reach T.absurd because the type Parent[Integer] wasn't handled https://srb.help/7026
    20 |else T.absurd(foo)
             ^^^^^^^^^^^^^
  Originating from:
    editor.rb:14:
    14 |foo = T.let(Parent::B[Integer].new, Parent[Integer]) 
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:17:
    17 |when Parent::A
             ^^^^^^^^^
    editor.rb:18:
    18 |when Parent::B
             ^^^^^^^^^
    editor.rb:19:
    19 |when Parent::C
             ^^^^^^^^^
Errors: 1
```

#### Expected behavior

Expect no errors. [Removing generics from the module](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Parent%0A%20%20%23%20extend%20T%3A%3AGeneric%0A%20%20extend%20T%3A%3AHelpers%0A%20%20sealed!%0A%0A%20%20%23%20Elem%20%3D%20type_member%0A%0A%20%20class%20A%3B%20extend%20T%3A%3AGeneric%3B%20include%20Parent%3B%20Elem%20%3D%20type_member%3B%20end%0A%20%20class%20B%3B%20extend%20T%3A%3AGeneric%3B%20include%20Parent%3B%20Elem%20%3D%20type_member%3B%20end%0A%20%20class%20C%3B%20extend%20T%3A%3AGeneric%3B%20include%20Parent%3B%20Elem%20%3D%20type_member%3B%20end%0Aend%0A%0Afoo%20%3D%20T.let(Parent%3A%3AB%5BInteger%5D.new%2C%20Parent)%20%0A%0Acase%20foo%0Awhen%20Parent%3A%3AA%0Awhen%20Parent%3A%3AB%0Awhen%20Parent%3A%3AC%0Aelse%20T.absurd(foo)%0Aend) results in correct exhaustiveness checking.

```ruby
# typed: true
module Parent
  # extend T::Generic
  extend T::Helpers
  sealed!

  # Elem = type_member

  class A; extend T::Generic; include Parent; Elem = type_member; end
  class B; extend T::Generic; include Parent; Elem = type_member; end
  class C; extend T::Generic; include Parent; Elem = type_member; end
end

foo = T.let(Parent::B[Integer].new, Parent) 

case foo
when Parent::A
when Parent::B
when Parent::C
else T.absurd(foo)
end
```

- - -

**Comment by jez** [comment] 2020-10-15 00:28
duplicate of #2572

**Closed by jez** 2020-10-15 00:28 UTC
Labels: bug
