### ISSUE TITLE
Returning different array types in separate if branches bypasses typecheck

### ISSUE THREAD

**Issue by asterite** [sorbet/sorbet#6231] opened 2022-08-12 15:50 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20params%28x%3A%20T.untyped%29.returns%28T%3A%3AArray%5BString%5D%29%20%7D%0Adef%20foo%28x%29%0A%20%20if%20x%0A%20%20%20%20%5B1%2C%202%5D%0A%20%20else%0A%20%20%20%20%5B%22b%22%5D%0A%20%20end%0Aend)

```ruby
# typed: true
extend T::Sig

sig { params(x: T.untyped).returns(T::Array[String]) }
def foo(x)
  if x
    [1, 2] # This is not an Array[String] :-)
  else
    ["b"]
  end
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

```
Expected T::Array[String] but found [T.any(Integer, String)] for method result type 
```

### More...

Interestingly, if you change `[1, 2]` to `[1]` it starts working fine.

Sorry if this was already reported as a separate issue, I looked at the open ones and couldn't find it.

**Comment by jez** [comment] 2022-08-12 17:07
Thanks this is a dupe of #4724.

**Closed by jez** 2022-08-12 17:07 UTC
Labels: bug, unconfirmed
