### ISSUE TITLE
`super && boolean` is understood as `T.nilable(T::Boolean)` when `super` and `boolean` are both `T::Boolean`

### ISSUE THREAD

**Issue by lugray** [sorbet/sorbet#6433] opened 2022-09-27 14:38 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Base%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20returns%28T%3A%3ABoolean%29%7D%0A%20%20def%20ready%3F%0A%20%20%20%20true%0A%20%20end%0Aend%0A%0Aclass%20SuperWithAndFails%20%3C%20Base%0A%20%20sig%20%7B%20returns%28T%3A%3ABoolean%29%7D%0A%20%20def%20ready%3F%0A%20%20%20%20super%20%26%26%20true%0A%20%20end%0Aend%0A%0Aclass%20BareSuperIsFine%20%3C%20Base%0A%20%20sig%20%7B%20returns%28T%3A%3ABoolean%29%7D%0A%20%20def%20ready%3F%0A%20%20%20%20super%0A%20%20end%0Aend%0A%0Aclass%20CallingTheSuperMethodOnADifferentInstanceIsFine%20%3C%20Base%0A%20%20sig%20%7B%20returns%28T%3A%3ABoolean%29%7D%0A%20%20def%20ready%3F%0A%20%20%20%20Base.new.ready%3F%20%26%26%20true%0A%20%20end%0Aend)

```ruby
# typed: true

class Base
  extend T::Sig

  sig { returns(T::Boolean)}
  def ready?
    true
  end
end

class SuperWithAndFails < Base
  sig { returns(T::Boolean)}
  def ready?
    super && true
  end
end

class BareSuperIsFine < Base
  sig { returns(T::Boolean)}
  def ready?
    super
  end
end

class CallingTheSuperMethodOnADifferentInstanceIsFine < Base
  sig { returns(T::Boolean)}
  def ready?
    Base.new.ready? && true
  end
end
```

#### Observed output

```
editor.rb:16: Expected T::Boolean but found T.nilable(T::Boolean) for method result type https://srb.help/7005
    16 |  end
          ^^^
  Expected T::Boolean for result type of method ready?:
    editor.rb:14:
    14 |  def ready?
          ^^^^^^^^^^
  Got T.nilable(T::Boolean) originating from:
    editor.rb:15:
    15 |    super && true
            ^^^^^
    editor.rb:15:
    15 |    super && true
                     ^^^^
Errors: 1
```

#### Expected behavior

All of these should pass. Something strange is going on with the type inference when combining `super` with `&&`.

I'd be willing to dig into this, but would need some pointers on where to start: The only files in the codebase containing `super` of `inherit` in their path are in `/test`.

**Comment by froydnj** [comment] 2022-09-27 14:42
This is a duplicate of #373 (`super` is given the type `T.untyped`).

**Closed by froydnj** 2022-09-27 14:42 UTC

**Comment by lugray** [comment] 2022-09-27 15:12
I'll leave #1068 for anyone else following the breadcrumbs.
