### ISSUE TITLE
`T.self_type` not checked in runtime

### ISSUE THREAD

**Issue by marianosimone** [sorbet/sorbet#1284] opened 2019-07-15 16:37 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(T.untyped)%7D%0A%20%20def%20self.x%0A%20%20%20%20return%20new%0A%20%20end%0Aend%0A%0Aclass%20B%20%3C%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(B)%7D%0A%20%20def%20self.x%0A%20%20%20%20super%0A%20%20end%0Aend%0A%0Aclass%20C%20%3C%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Breturns(T.self_type)%7D%0A%20%20def%20self.x%0A%20%20%20%20super%0A%20%20end%0Aend%0A%0AB.x%20%23%20this%20returns%20B%2C%20thus%20everything%20is%20OK%0AC.x%20%23%20this%20returns%20a%20C%2C%20although%20the%20sig%20says%20that%20it%20will%20return%20the%20class%20of%20C.%20Runtime%20doesn't%20complain%2C%20though)

```ruby
# typed: true
class A
  extend T::Sig

  sig {returns(T.untyped)}
  def self.x
    return new
  end
end

class B < A
  extend T::Sig

  sig {returns(B)}
  def self.x
    super
  end
end

class C < A
  extend T::Sig

  sig {returns(T.self_type)}
  def self.x
    super
  end
end

B.x # this returns B, thus everything is OK
C.x # this returns a C, although the sig says that it will return the class of C. Runtime doesn't complain, though
```

#### Observed output
No runtime error

#### Expected behavior
`C.x` should fail, as it's returning an instance of `C`, instead of `T.class_of(C)`

**Comment by DarkDimius** [comment] 2019-07-15 18:28
My experience suggests that this is going to be super hard to enforce.

**Comment by Morriar** [comment] 2021-04-30 16:05
Duplicate of https://github.com/sorbet/sorbet/issues/197

**Closed by Morriar** 2021-04-30 16:05 UTC
Labels: bug, hard
