### ISSUE TITLE
T.self_type cannot be used in interface definition

### ISSUE THREAD

**Issue by qbalin** [sorbet/sorbet#7715] opened 2024-02-20 23:02 UTC
Hi!

I'm trying to define a comparison method named `coalesceable_with?` that takes two objects of the same type and returns a boolean. 

I managed to write an interface, and a concrete class that implements it, but the override implementation of the method will not allow references to `self` or `other`. 

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20Coalesceable%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AHelpers%0A%20%20interface!%0A%0A%20%20sig%20%7B%20abstract.params%28other%3A%20T.self_type%29.returns%28T%3A%3ABoolean%29%20%7D%0A%20%20def%20coalesceable_with%3F%28other%29%3B%20end%0Aend%0A%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20Coalesceable%0A%0A%20%20sig%20%7B%20returns%28Integer%29%20%7D%0A%20%20attr_reader%20%3Avalue%0A%0A%20%20sig%20%7B%20params%28value%3A%20Integer%29.void%20%7D%0A%20%20def%20initialize%28value%29%0A%20%20%20%20%40value%20%3D%20value%0A%20%20end%0A%0A%20%20sig%20%7B%20override.params%28other%3A%20T.self_type%29.returns%28T%3A%3ABoolean%29%20%7D%0A%20%20def%20coalesceable_with%3F%28other%29%0A%20%20%20%20other.value%20%3D%3D%20self.value%20%20%20%20%0A%20%20end%0Aend%0A)

```ruby
# typed: true
extend T::Sig

module Coalesceable
  extend T::Sig
  extend T::Helpers
  interface!

  sig { abstract.params(other: T.self_type).returns(T::Boolean) }
  def coalesceable_with?(other); end
end


class Foo
  extend T::Sig
  include Coalesceable

  sig { returns(Integer) }
  attr_reader :value

  sig { params(value: Integer).void }
  def initialize(value)
    @value = value
  end

  sig { override.params(other: T.self_type).returns(T::Boolean) }
  def coalesceable_with?(other)
    other.value == self.value    
  end
end

```

#### Observed output

```
editor.rb:27: Expression does not have a fully-defined type (Did you reference another class's type members?) https://srb.help/7011
    27 |  def coalesceable_with?(other)
                                 ^^^^^
  Note:
    Historically, users seeing this error has represented finding a bug in Sorbet
    (or at least finding a test case for which there could be a better error message).
    Consider searching for similar bugs at https://github.com/sorbet/sorbet/issues
    or reporting a new one.
Errors: 1
```

#### Expected behavior

- - -

**Comment by jez** [comment] 2024-02-20 23:05
Dupe of #6876

**Closed by jez** 2024-02-20 23:05 UTC
Labels: bug, unconfirmed
