### ISSUE TITLE
Typechecker allows literals in struct prop types

### ISSUE THREAD

**Issue by qaisjp** [sorbet/sorbet#5087] opened 2022-01-11 22:44 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0A%23%20errors%2C%20as%20expected%0AT.let%28-1%2C%20-1%29%0A%0A%23%20should%20error%2C%20but%20doesn't%0Aclass%20X%20%3C%20T%3A%3AStruct%0A%20%20prop%20%3Abar%2C%20-1%2C%20default%3A%20-1%0Aend%0A%0A%23%20as%20expected%2C%20it%20errors%20at%20runtime%3A%0A%23%0A%23%20RuntimeError%3A%20Invalid%20value%20for%20type%20constraint.%0A%23%20Must%20be%20an%20T%3A%3ATypes%3A%3ABase%2C%20a%20class%2Fmodule%2C%20or%20an%20array.%20Got%20a%20%60Integer%60.)

```ruby
# typed: true
extend T::Sig

# errors, as expected
T.let(-1, -1)

# should error, but doesn't
class X < T::Struct
  prop :bar, -1, default: -1
end

# as expected, it errors at runtime:
#
# RuntimeError: Invalid value for type constraint.
# Must be an T::Types::Base, a class/module, or an array. Got a `Integer`.
```

#### Observed output

```
editor.rb:5: Unsupported literal in type syntax https://srb.help/5003
     5 |T.let(-1, -1)
                  ^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:5: Replace with Integer
     5 |T.let(-1, -1)
                  ^^
Errors: 1
```

#### Expected behavior

I expected to see a second error, disallowing this literal in `T::Struct` props.

**Comment by jez** [comment] 2022-01-11 23:00
This is somewhat by design, in an attempt to remain compatible with other Ruby code:

https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20A%20%3C%20T%3A%3AStruct%0A%20%20prop%20%3Afoo%2C%20%3Ainvalid_prop%0Aend%0A%0AA.new.foo%20%23%20error%20%28expected%29

Sorbet does not make an attempt to say that `T::Props` is the only code in the Ruby ecosystem that might define a `prop` DSL, so when it encounters something that doesn't exactly match the allowed shape for the `T::Props` DSL, it silently gives up, leaving the input unchanged.

So I think this is a wontfix, unfortunately.

**Closed by jez** 2022-01-11 23:00 UTC
Labels: bug, unconfirmed
