### ISSUE TITLE
Confusing error message with &. in hash 

### ISSUE THREAD

**Issue by penelope-stripe** [sorbet/sorbet#3356] opened 2020-08-11 16:26 UTC
hey folks, I found a confusing, but not totally wrong error message with sorbet this morning which reduces to this case https://sorbet.run/#%23%20typed%3A%20true%0Afoo%20%3D%20RuntimeError.new%0A%0A%7B%0A%20%20internal_error_class%3A%20foo%26.to_s%0A%7D. While it’s strictly correct that the &. is unreachable because the variable can’t be nil, I didn’t totally understand what this meant at first. Might be a good one to clarify?

**Comment by jez** [comment] 2020-08-11 18:46
Dupe of #36.

**Closed by jez** 2020-08-11 18:46 UTC
Labels: enhancement
