### ISSUE TITLE
Helper to typecheck serialized form of Enum

### ISSUE THREAD

**Issue by smackesey** [sorbet/sorbet#4183] opened 2021-04-29 15:56 UTC
### Problem

In plain Ruby, finite sets of symbols and strings are often used as informal enum "types". Sorbet implements enums via its special T::Enum class, but has no direct support for enums composed of literals. This makes it hard to implement enum type-checking on older code that exposes an interface where a symbol/string belonging to an implicit "enum" is expected as an argument. This limits Sorbet's effectiveness as a gradual type-checking system.

### Proposed solution

I assume there is some specific technical reason Sorbet doesn't implement literal types generally. However, it already does something close for `T::Enum` with `::serialize`/`::deserialize` methods on the enum classes. Seems like a helper function (`T.serialized`?) could be defined to type-check the serialized form of an enum:

```ruby
class Foo < T::Enum
  enums do
    Bar = new(:bar)
    Baz = new(:baz)
  end
end

sig { params(x: Foo).void }
def bing(x); end

sig { void }
def ding; bing(:bar); end  # error

sig { params(x: T.serialized(Foo)).void }
def bing(x); end

sig { void }
def ding; bing(:bar); end  # now it works
```

**Comment by jez** [comment] 2022-08-14 02:52
This seems like a duplicate of #4035 

Thanks for the report, but building up the machinery to do this properly is not easy (we should do it eventually though).

**Closed by jez** 2022-08-14 02:52 UTC
Labels: enhancement, unconfirmed
