### ISSUE TITLE
Type info lost then using T.let+T.any

### ISSUE THREAD

**Issue by itarato** [sorbet/sorbet#4123] opened 2021-03-30 17:17 UTC
#### Input

[→ View on sorbet.run - example without generics](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20MA%0Aend%0A%0Aclass%20CA%0A%20%20include%20MA%0Aend%0A%0Amodule%20MB%0Aend%0A%0Aclass%20CB%0A%20%20include%20MB%0Aend%0A%0Ax%20%3D%20T.let(CA.new%2C%20T.any(CA%2C%20CB))%0A%0Acase%20x%0Awhen%20MA%0A%20%20T.reveal_type(x)%0Awhen%20MB%0A%20%20T.reveal_type(x)%0Aend)

[→ View on sorbet.run - example with generics](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20Gen1%0A%20%20extend(T%3A%3ASig)%0A%20%20extend(T%3A%3AGeneric)%0A%0A%20%20SelfType%20%3D%20type_member%0A%0A%20%20sig%20%7B%20returns(SelfType)%20%7D%0A%20%20attr_reader(%3Aval)%0Aend%0A%0Amodule%20Gen2%0A%20%20extend(T%3A%3ASig)%0A%20%20extend(T%3A%3AGeneric)%0A%0A%20%20SelfType%20%3D%20type_member%0Aend%0A%0Aclass%20C1%0A%20%20extend(T%3A%3ASig)%0A%20%20extend(T%3A%3AGeneric)%0A%20%20include(Gen1)%0A%0A%20%20SelfType%20%3D%20type_member%0Aend%0A%0Aclass%20C2%0A%20%20extend(T%3A%3ASig)%0A%20%20extend(T%3A%3AGeneric)%0A%20%20include(Gen2)%0A%0A%20%20SelfType%20%3D%20type_member%0Aend%0A%0Ax%20%3D%20T.let(C1.new%2C%20T.any(Gen1%5BString%5D%2C%20Gen2%5BInteger%5D))%0Acase%20x%0Awhen%20Gen1%0A%20%20T.reveal_type(x)%20%20%20%20%20%23%20Revealed%20type%3A%20T.all(Gen1%5BT.untyped%5D%2C%20T.any(Gen1%5BString%5D%2C%20Gen2%5BInteger%5D))%20%0A%20%20T.reveal_type(x.val)%20%23%20Revealed%20type%3A%20T.untyped%0Awhen%20Gen2%0A%20%20T.reveal_type(x)%20%20%20%20%20%23%20Revealed%20type%3A%20Gen2%5BInteger%5D%0Aelse%20T.absurd(x)%0Aend)

```ruby
# typed: true

module MA
end

class CA
  include MA
end

module MB
end

class CB
  include MB
end

x = T.let(CA.new, T.any(CA, CB))

case x
when MA
  T.reveal_type(x)
when MB
  T.reveal_type(x)
end
```

#### Observed output

```
editor.rb:23: Revealed type: CB https://srb.help/7014
    23 |  T.reveal_type(x)
          ^^^^^^^^^^^^^^^^
  Got CB originating from:
    editor.rb:17:
    17 |x = T.let(CA.new, T.any(CA, CB))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:20:
    20 |when MA
             ^^

editor.rb:21: Revealed type: T.all(MA, T.any(CA, CB)) https://srb.help/7014
    21 |  T.reveal_type(x)
          ^^^^^^^^^^^^^^^^
  Got T.all(MA, T.any(CA, CB)) originating from:
    editor.rb:17:
    17 |x = T.let(CA.new, T.any(CA, CB))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    editor.rb:20:
    20 |when MA
             ^^
Errors: 2
```

#### Expected behavior

Example without generics:

* Expected: `editor.rb:21: Revealed type: MA`
* Actual: `editor.rb:21: Revealed type: T.all(MA, T.any(CA, CB))`

Example with generics:

* Expected: `Revealed type: Gen1[String]`
* Actual: `Revealed type: T.all(Gen1[T.untyped], T.any(Gen1[String], Gen2[Integer]))`

**Comment by karmakaze** [comment] 2021-08-14 19:35
A `reveal_type(x)` before the `case` is `T.any(CA, CB)` as expected.
When combined with `when MA`, that is logically `T.all(MA, T.any(CA, CB))` as reported on `:21`.

The only thing I can see being done better here is recognize that `CA < MA`, and rewriting in steps:
- `T.any(T.all(MA, CA), T.all(MA, CB))` with `T.all(MA, CB)` being empty, so
- `T.all(MA, CA)` which is simply `CA`

**Comment by jez** [comment] 2022-07-21 03:29
Sorbet is actually modeling intersection types correctly here. The problem is inheritance.

The question being asked boils down to "why doesn't Sorbet collapse `T.all(MA, CB)` to `T.noreturn`?

And the answer is that it **is possible** to inhabit that type: `CB` might have a child class defined like this:

```ruby
class ChildCB < CB
  include MA
end
```

Is is now the case that `ChildCB <: MA` and `ChildCB <: CB` therefore `ChildCB <: T.all(MA, CB)`.

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20MA%0Aend%0A%0Aclass%20CA%0A%20%20include%20MA%0A%20%20def%20only_on_ca%3B%20end%0Aend%0A%0Amodule%20MB%0Aend%0A%0Aclass%20CB%0A%20%20include%20MB%0Aend%0A%0Aclass%20ChildCB%20%3C%20CB%0A%20%20include%20MA%0Aend%0A%0Asig%20%7Bparams%28ca%3A%20CA%29.void%7D%0Adef%20takes_ca%28ca%29%0A%20%20ca.only_on_ca%0Aend%0A%0Asig%20%7Bparams%28x%3A%20T.any%28CA%2C%20CB%29%29.void%7D%0Adef%20example%28x%29%0A%20%20case%20x%0A%20%20when%20MA%0A%20%20%20%20takes_ca%28x%29%0A%20%20end%0Aend%0A%0Aexample%28ChildCB.new%29)

The same logic applies when the class is generic.

You might ask "well why can't Sorbet see that the classes in my example *happen* to not have any children defined like that?"

Answering that is slow. Sorbet would either have to associate a list of subclasses with every parent class (wasted space and time to keep up to date if, like for the majority of classes, that information isn't needed in the end) or to search the entire symbol table lazily when it would need that information (no wasted space, but even more wasted time).

Sorbet **could** special case this when either one of the module or class is final. (It wouldn't make much sense if the module were made final, because a final module has no inhabitants.) So if `CB` were made final (a reasonable refactoring), Sorbet could in fact collapse `T.all(MA, CB)` to `T.noreturn`.

That is an easy change to make, and I plan to put up a PR for it shortly. But I'm going to close this ticket, because the behavior in the top post is actually Sorbet working as intended.

**Closed by jez** 2022-07-21 03:29 UTC
Labels: bug
