### ISSUE TITLE
No type failure for wrong visibility (public vs. private) on implementation of interface

### ISSUE THREAD

**Issue by alexevanczuk** [sorbet/sorbet#7511] opened 2023-11-29 20:15 UTC
I noticed when using interfaces that if you implement an interface method with the wrong signature you get a type error, but you don't get the same issue with the wrong method visibility.

This felt like something the type checker might be able to catch, so wanted to report it!

Thanks for the great work on Sorbet 🙇🏼 

https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20MyInterface%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%20%20interface!%0A%0A%20%20sig%20%7B%20abstract.void%20%7D%0A%20%20def%20my_public_method%3B%20end%0A%0A%20%20sig%20%7B%20abstract.void%20%7D%0A%20%20def%20my_other_public_method%3B%20end%0A%0A%20%20sig%20%7B%20abstract.params%28arg%3A%20String%29.void%20%7D%0A%20%20def%20my_wrong_arity%28arg%29%3B%20end%0Aend%0A%0Aclass%20MyImplementation%0A%20%20extend%20T%3A%3ASig%0A%20%20include%20MyInterface%0A%0A%20%20sig%20%7B%20override.void%20%7D%0A%20%20def%20my_public_method%3B%20end%0A%0A%20%20sig%20%7B%20override.params%28arg%3A%20Integer%29.void%20%7D%0A%20%20def%20my_wrong_arity%28arg%29%3B%20end%0A%0A%20%20private%0A%0A%20%20sig%20%7B%20override.void%20%7D%0A%20%20def%20my_other_public_method%3B%20end%0Aend

**Comment by jez** [comment] 2023-11-29 20:17
Yep, sorry about this.

Dupe of #5522

**Closed by jez** 2023-11-29 20:17 UTC
Labels: bug, unconfirmed
