### ISSUE TITLE
`T.must` should narrow local variables

### ISSUE THREAD

**Issue by amomchilov** [sorbet/sorbet#8048] opened 2024-07-23 21:34 UTC
### Problem

This a special case of #8042 for `T.must`, which is a very common case.

Repeated uses of `T.must` on a local variable shouldn't be necessary. E.g.

```ruby
sig { returns(T.nilable(Object)) } 
def never_actualy_nil = 123

x = never_actualy_nil

p T.must(x).inspect
p T.must(x).to_s # If `x` was `nil`, the line above would've raised `TypeError already
p T.must(x).hash
```

#### Possible workarounds

The best workaround is to just unwrap the original call, and assign its unwrapper result, and this is how `T.must` should be used 99% of the time:

```ruby
x = T.must(never_actualy_nil)

p x.inspect
```

But it doesn't work well with array destrcuturing, where the newly bound variables are always nilable if the array isn't a tuple (even if it's an array of non-nilable types):

```ruby
sig { returns(T::Array[Integer}) }
def not_nils = [1, 2, 3]

x, y, z = not_nils
x = T.must(x) # Not nice :(
y = T.must(y)
z = T.must(z)
```

### Proposed solution

`T.must(x)` should have a side-effect of narrowing the type, as if you had written `raise unless x`. Desired behaviour:

```ruby
x = T.let(something, T.nilable(Object))

T.must(x) # Should work like how `raise TypeError unless x` already works today

T.reveal_type(x) # => `x` narrowed to non-nilable `Object`
```

**Comment by jez** [comment] 2024-07-23 21:44
Duplicate of #3397

This is particularly tricky because Sorbet's whole implementation of pinning relies on seeing an assignment to a variable.

**Closed by jez** 2024-07-23 21:44 UTC
Labels: enhancement, unconfirmed
