### ISSUE TITLE
Sorbet's void is pretty tricky

### ISSUE THREAD

**Issue by leonp1991** [sorbet/sorbet#3413] opened 2020-09-10 16:29 UTC
Hi Sorbet team,

Thanks for such a great tool. I want to express some issues around sorbet's 'void' return value. The way void works in sorbet is generally quite different to other languages and instead of expressing the absense of a return value it kinda represents the presence of a value of no meaning.

This may seem trivial but it does have subtle differences in how it behaves. An example of this when we leverage duck typing.

case 1:
we return no value in plain ruby. This value will be treated as falsey

case 2:
we have a void sig. This value will be treated as truthy.

sorbet try snippet https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20TestCase%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20should_be_falsey_case_1%0A%20%20%20%20false%0A%20%20end%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20should_be_falsey_case_2%0A%20%20%20%20nil%0A%20%20end%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20should_be_falsey_case_3%0A%20%20%20%20%23%20no%20body%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20puts(%22Boo%201!%22)%20if%20TestCase.new.should_be_falsey_case_1%0A%20%20puts(%22Boo%202!%22)%20if%20TestCase.new.should_be_falsey_case_2%0A%20%20puts(%22Boo%203!%22)%20if%20TestCase.new.should_be_falsey_case_3%0Aend

In my opinion this is quite misleading to the meaning and the external usage of the term 'void' in programming.

However It doesn't appear there is a way to make an object type simulate false or nil in ruby. Maybe there is a better name? I'm not sure of what a great solution would be. Maybe there are some static analysis lint rules for using this void type.

Would be good to smooth this edge though as it can be a pretty big gotchya. Keen for thoughts.

**Comment by sharpobject** [comment] 2020-10-01 10:38
This part of the behavior of `void` does not seem to be working:

> Also statically, `srb` will error when typed code tries to inspect the result of a `void` method.

**Comment by ghiculescu** [comment] 2020-10-06 18:11
> This part of the behavior of `void` does not seem to be working in this case:
> 
> > Also statically, `srb` will error when typed code tries to inspect the result of a `void` method.

It works, but only in limited cases. [For example, this errors correctly](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20TestCase%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20should_be_falsey_case_1%0A%20%20%20%20false%0A%20%20end%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20should_be_falsey_case_2%0A%20%20%20%20nil%0A%20%20end%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20should_be_falsey_case_3%0A%20%20%20%20%23%20no%20body%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20puts(%22Boo%201!%22)%20if%20TestCase.new.should_be_falsey_case_1%0A%20%20puts(%22Boo%202!%22)%20if%20TestCase.new.should_be_falsey_case_2%0A%20%20puts(%22Boo%203!%22)%20if%20TestCase.new.should_be_falsey_case_3.nil%3F%0Aend). The problem is when a `void` is treated as the truthy/falsey output of an if statement.

**Comment by jez** [comment] 2020-10-18 06:57
The fact that it's not currently an error to use a void value in a conditional is a bug in Sorbet:

#2913 

That's a pretty good first issue—if someone wants to tackle this I'm happy to advise.

Otherwise, void is special cased to prevent misuse:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0Asig%20%7Bvoid%7D%0Adef%20foo%3B%20end%0Afoo.to_s)

Thanks for the feedback. I'm going to close this, and keep #2913 open.

**Closed by jez** 2020-10-18 06:57 UTC
Labels: feedback
