### ISSUE TITLE
Cannot type_parameter a method that returns a Covariant generic

### ISSUE THREAD

**Issue by Kache** [sorbet/sorbet#6745] opened 2023-02-16 19:46 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0A%0Aclass%20CoBox%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member%28%3Aout%29%0A%0A%20%20sig%20%7B%20params%28value%3A%20Elem%29.void%20%7D%0A%20%20def%20initialize%28value%29%0A%20%20%20%20%40value%20%3D%20value%0A%20%20end%0Aend%0A%0Asig%20%7B%20type_parameters%28%3AV%29.params%28value%3A%20T.type_parameter%28%3AV%29%29.returns%28CoBox%5BT.type_parameter%28%3AV%29%5D%29%20%7D%0Adef%20co_box%28value%29%0A%20%20CoBox.new%28value%29%20%23%20errors%2C%20but%20should%20not%0Aend%0A%0A%23%20covariant%20usage%0AT.let%28co_box%28Bar.new%29%2C%20CoBox%5BBar%5D%29%0AT.let%28co_box%28Baz.new%29%2C%20CoBox%5BBar%5D%29%0A%0A%0A%23%20invariant%20example%20follows%2C%20just%20for%20comparison%0Aclass%20Box%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20sig%20%7B%20params%28value%3A%20Elem%29.void%20%7D%0A%20%20def%20initialize%28value%29%0A%20%20%20%20%40value%20%3D%20value%0A%20%20end%0Aend%0A%0Asig%20%7B%20type_parameters%28%3AV%29.params%28value%3A%20T.type_parameter%28%3AV%29%29.returns%28Box%5BT.type_parameter%28%3AV%29%5D%29%20%7D%0Adef%20box%28value%29%0A%20%20Box.new%28value%29%0Aend%0A%0Aclass%20Bar%3B%20end%0Aclass%20Baz%20%3C%20Bar%3B%20end%0A%0AT.let%28box%28Bar.new%29%2C%20Box%5BBar%5D%29)

```ruby
# typed: true

extend T::Sig

class CoBox
  extend T::Sig
  extend T::Generic

  Elem = type_member(:out)

  sig { params(value: Elem).void }
  def initialize(value)
    @value = value
  end
end

sig { type_parameters(:V).params(value: T.type_parameter(:V)).returns(CoBox[T.type_parameter(:V)]) }
def co_box(value)
  CoBox.new(value) # errors, but should not
end

# covariant usage
T.let(co_box(Bar.new), CoBox[Bar])
T.let(co_box(Baz.new), CoBox[Bar])


# invariant example follows, just for comparison
class Box
  extend T::Sig
  extend T::Generic

  Elem = type_member

  sig { params(value: Elem).void }
  def initialize(value)
    @value = value
  end
end

sig { type_parameters(:V).params(value: T.type_parameter(:V)).returns(Box[T.type_parameter(:V)]) }
def box(value)
  Box.new(value)
end

class Bar; end
class Baz < Bar; end

T.let(box(Bar.new), Box[Bar])
```

#### Observed output

```
editor.rb:19: Expected CoBox[T.type_parameter(:V) (of Object#co_box)] but found CoBox[<top>] for method result type https://srb.help/7005
    19 |  CoBox.new(value) # errors, but should not
          ^^^^^^^^^^^^^^^^
  Expected CoBox[T.type_parameter(:V) (of Object#co_box)] for result type of method co_box:
    editor.rb:18:
    18 |def co_box(value)
        ^^^^^^^^^^^^^^^^^
  Got CoBox[<top>] originating from:
    editor.rb:19:
    19 |  CoBox.new(value) # errors, but should not
          ^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

Perhaps I've misunderstood something, but I think methods like `co_box` shouldn't error.

My current workaround is to have them return `CoBox[T.untyped]`

- - -

**Comment by jez** [comment] 2023-02-16 19:54
You are missing a type annotation on `CoBox.new`:

[→ corrected example](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0A%0Aclass%20CoBox%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member%28%3Aout%29%0A%0A%20%20sig%20%7B%20params%28value%3A%20Elem%29.void%20%7D%0A%20%20def%20initialize%28value%29%0A%20%20%20%20%40value%20%3D%20value%0A%20%20end%0Aend%0A%0Asig%20%7B%20type_parameters%28%3AV%29.params%28value%3A%20T.type_parameter%28%3AV%29%29.returns%28CoBox%5BT.type_parameter%28%3AV%29%5D%29%20%7D%0Adef%20co_box%28value%29%0A%20%20CoBox%5BT.type_parameter%28%3AV%29%5D.new%28value%29%20%23%20errors%2C%20but%20should%20not%0Aend%0A%0A%23%20covariant%20usage%0AT.let%28co_box%28Bar.new%29%2C%20CoBox%5BBar%5D%29%0AT.let%28co_box%28Baz.new%29%2C%20CoBox%5BBar%5D%29%0A%0A%0A%23%20invariant%20example%20follows%2C%20just%20for%20comparison%0Aclass%20Box%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member%0A%0A%20%20sig%20%7B%20params%28value%3A%20Elem%29.void%20%7D%0A%20%20def%20initialize%28value%29%0A%20%20%20%20%40value%20%3D%20value%0A%20%20end%0Aend%0A%0Asig%20%7B%20type_parameters%28%3AV%29.params%28value%3A%20T.type_parameter%28%3AV%29%29.returns%28Box%5BT.type_parameter%28%3AV%29%5D%29%20%7D%0Adef%20box%28value%29%0A%20%20Box.new%28value%29%0Aend%0A%0Aclass%20Bar%3B%20end%0Aclass%20Baz%20%3C%20Bar%3B%20end%0A%0AT.let%28box%28Bar.new%29%2C%20Box%5BBar%5D%29)

This annotation is secretly required. When it is not provided, Sorbet assumes:

- `T.untyped` if the generic is invariant
- `<top>` if the generic is covariant
- `T.noreturn` if the generic is contravariant

The fix for this will be one of #3768 or #4450 (either: require a type argument for all generics, or infer a type argument from the arguments, and require the ones that can't be inferred).

(I've tried both in the past and neither is a simple fix so unfortunately they'll remain open for the time being.)

Closing this as a dupe of those other ones

**Closed** 2023-02-16 19:54 UTC
