### ISSUE TITLE
Bug generating RBI for Rails 6.0.3, Ruby 2.7

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#2994] opened 2020-05-10 04:47 UTC
There are generation errors in Ruby 2.7. It seems to happen in the last few days. I found it out via. Sorbet-rails automated tests.

Sample errors: (notice the double ** and double &&)
```ruby
sorbet/rbi/gems/activerecord.rbi:2489: unexpected token tAMPER https://srb.help/2001
    2489 |  def rotate(**, &&); end
                            ^
sorbet/rbi/gems/activerecord.rbi:2490: unexpected token tAMPER https://srb.help/2001
    2490 |  def sample(**, &&); end
```

**Comment by jaredbeck** [comment] 2020-05-19 02:33
See also:

- https://github.com/sorbet/sorbet/issues/2900
- https://github.com/sorbet/sorbet/issues/2771

**Comment by connorshea** [comment] 2020-06-06 23:50
I did a bit of investigating and found that the behavior indeed differs between versions:

```
# 2.6:
irb(main):003:0> ActiveRecord::Delegation.instance_method(:rotate).parameters
=> [[:rest, :args], [:block, :block]]

# 2.7:
irb(main):008:0> ActiveRecord::Delegation.instance_method(:rotate).parameters
=> [[:rest, :*], [:block, :&]]
```

Seems to be caused by this line on Ruby 2.7: https://github.com/rails/rails/blob/1b3a0a0388cea93ba33e6a951a3ac0aa2e4a8ed7/activerecord/lib/active_record/relation/delegation.rb#L64

There's no special `parameters` return type for the delegation syntax, but there is an issue to create it: https://bugs.ruby-lang.org/issues/16456

We could explicitly add a check for `[[:rest, :*]` and `[:block, :&]]` and correct it to `*args` and  `&block` for now, but it'd be a bit of a hack.

**Comment by bmulholland** [comment] 2020-12-17 16:43
I switched to Tapioca and, with [these steps](https://github.com/Shopify/tapioca/issues/114#issuecomment-740571866), am successfully using Sorbet with Ruby 2.7. This works because Tapioca generates RBI files with `*args` and `&block` instead of the new syntax.

**Comment by connorshea** [comment] 2021-02-09 04:13
I also chose to resolve this by switching to Tapioca.

**Comment by jez** [comment] 2022-07-27 20:53
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca

**Closed by jez** 2022-07-27 20:53 UTC
Labels: bug, unconfirmed, srb
