### ISSUE TITLE
Impossible intersection error not reported on declaration

### ISSUE THREAD

**Issue by cameronmccord2** [sorbet/sorbet#6043] opened 2022-07-18 15:43 UTC
In VS Code and sorbet.run when you declare an invalid intersection with T.all no error is reported on the T.all line. The following line is reported as "This code is unreachable". While the unreachable error is correct its confusing. The T.all should be highlighted with an error.

#### Input

https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Adef%20asdf%0A%20%20T.bind%28self%2C%20T.all%28Time%2C%20Date%29%29%0A%20%20puts%20%22asdf%22%0Aend

```ruby
# typed: true
extend T::Sig

def asdf
  T.bind(self, T.all(Time, Date))
  puts "asdf"
end
```

#### Observed output

```
editor.rb:6: This code is unreachable https://srb.help/7006
     6 |  puts "asdf"
               ^^^^^^
    editor.rb:5: This expression always raises or can never be computed
     5 |  T.bind(self, T.all(Time, Date))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

The invalid T.all should have the error

- - -

<img width="390" alt="Screen Shot 2022-07-18 at 9 40 50 AM" src="https://user-images.githubusercontent.com/2424811/179549278-a0d4fff5-504b-4809-a229-6fc755413e01.png">

**Comment by jez** [comment] 2022-08-06 19:58
Dupe of #225

**Closed by jez** 2022-08-06 19:58 UTC
Labels: bug, unconfirmed
