### ISSUE TITLE
Could not find sorbet-static-0.4.5079-universal-darwin-14 in any of the sources

### ISSUE THREAD

**Issue by michaelwebb76** [sorbet/sorbet#2250] opened 2019-11-28 11:45 UTC
#### Input

On Linux (running on Ubuntu 18.04 in Github Actions):
`bundle install --jobs $(nproc) --retry 3 --without metrics --path vendor/bundle`

#### Observed output

```
Fetching gem metadata from https://rubygems.pkg.github.com/tricycle/...
Fetching gem metadata from https://rubygems.org/...........
Fetching gem metadata from https://rubygems.pkg.github.com/tricycle/..
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Could not find sorbet-static-0.4.5079-universal-darwin-14 in any of the sources
```

#### Expected behavior

Our builds are failing for every one of our private gems, for the same reason. It appears as though the Linux version of this build has not been pushed to Rubygems.

Because these are gems, we are following best practice and not including a Gemfile.lock in each project, so locking down the version is impractical.

**Comment by arielj** [comment] 2019-11-29 15:08
Same issue here. Just added sorbet and sorbet-runtime and when I run `bundle install` I get the exact same message `Could not find sorbet-static-0.4.5079-universal-darwin-14 in any of the sources`.

Inside my gemfile:
    source 'http://rubygems.org'

But that version can be found at rubygems https://rubygems.org/gems/sorbet-static/versions/0.4.5079-universal-darwin-14

My system:
- Linux Mint 19 64-bits
- Kernel: 4.15.0-70-generic
- Ruby 2.5.7 (using rvm)

**Comment by arielj** [comment] 2019-11-29 22:00
Using the previous version works:

`gem 'sorbet', '0.4.5072'`

It looks like sorbet-static gem for linux platforms is not uploaded at rubygems for version 0.4.5079.

**Comment by benreyn** [comment] 2019-12-02 19:09
Any update on when the 0.4.5079 for linux platforms will get uploaded?

**Comment by arielj** [comment] 2019-12-02 19:13
Version 0.4.5083 has linux build:
https://rubygems.org/gems/sorbet-static/versions/0.4.5083-x86_64-linux

Version 0.4.5085 doesn't
https://rubygems.org/gems/sorbet-static/versions

**Comment by benreyn** [comment] 2019-12-02 19:15
Curious why some versions are getting a linux build and some are not. 🤔

**Comment by arielj** [comment] 2019-12-02 19:19
If I understand right, this script builds different versions and uploads them to rubygems https://github.com/sorbet/sorbet/blob/9e697d4d9882c1e3fad92073b68762f12abdfedc/.buildkite/build-static-release.sh. I'm guessing it has to be run on both mac and linux platforms and maybe sometimes it's only run on mac, I'm not sure how is the release process.

**Comment by michaelwebb76** [comment] 2019-12-03 00:23
Why oh why oh why

**Comment by connorshea** [comment] 2019-12-03 00:53
This is causing sorbet-rails' test suite to fail :(

**Comment by leighmcculloch** [comment] 2019-12-04 08:19
I'm seeing this failure on Debian Buster running Ruby 2.6.3:
```
$ gem install sorbet
ERROR:  Could not find a valid gem 'sorbet-static' (= 0.4.5099) (required by 'sorbet' (>= 0)) in any repository
ERROR:  Possible alternatives: sorbet-static
```

**Comment by dmitry-stripe** [comment] 2019-12-04 08:49
> If I understand right, this script builds different versions and uploads them to rubygems https://github.com/sorbet/sorbet/blob/9e697d4d9882c1e3fad92073b68762f12abdfedc/.buildkite/build-static-release.sh. I'm guessing it has to be run on both mac and linux platforms and maybe sometimes it's only run on mac, I'm not sure what's the release process.

that is indeed the job that builds it, and it's run both by linux and mac. If both succeed, nightly will run the following

https://github.com/sorbet/sorbet/blob/master/.buildkite/publish-ruby-gems.sh

and is supposed to upload both

**Comment by dmitry-stripe** [comment] 2019-12-04 08:50
https://buildkite.com/sorbet/sorbet/builds/7871 are logs for run that should have uploaded the `0.4.5099` for linux but didn't.

**Comment by dmitry-stripe** [comment] 2019-12-04 08:56
We seem to have a bug in uploader job: it has downloaded an artifact from buildkite build(see https://buildkite.com/sorbet/sorbet/builds/7871#0dc74d76-13e4-40e3-896f-d2b0485be407/91-106)
but did not upload it to rubygems

**Comment by dmitry-stripe** [comment] 2019-12-04 09:00
interesting, when we run
`gem list --remote rubygems.org --exact 'sorbet-static'` 
you can see that it returns 
```

*** REMOTE GEMS ***



*** REMOTE GEMS ***

sorbet-static (0.4.5099 universal-darwin-14 universal-darwin-15 universal-darwin-16 universal-darwin-17 universal-darwin-18 universal-darwin-19, 0.4.5083 x86_64-linux)
```
so... ruby gem _does_ report that it was uploaded.

I think this is a ruby gems bug.

**Comment by dmitry-stripe** [comment] 2019-12-04 09:02
ok, so I think https://github.com/sorbet/sorbet/blame/master/.buildkite/publish-ruby-gems.sh#L55 is a buggy `if`: it might decide to not upload a platform if another plaform has been uploaded.
 Given it's 1am where I am I'll not attempt to write a better one.
Feel free to make a PR to fix it, would be super happy to review

**Comment by arielj** [comment] 2019-12-04 15:54
Is that `if` even necessary? I mean, the script removes everything from the `_out_` dir, then downloads the artifacts, and then only loops through the files with `$release_version` on the name. Maybe this should be checked outside the loop once and not for each file (just in case this release was already pushed), what do you think? If so, I could send a PR like:

`if ! gem list --remote rubygems.org --exact 'sorbet-static' | grep -q "$release_version"; then
  for gem_archive in .....; do
    with_backoff gem push --verbose "$gem_archive"
  done
fi`

Any thoughts?

**Comment by DarkDimius** [comment] 2019-12-05 06:10
Should be fixed now^^^

**Comment by DarkDimius** [comment] 2019-12-05 06:10
Thank you for your reporting and helping pinpoint the bug!

**Closed by DarkDimius** 2019-12-05 06:10 UTC
Labels: bug, unconfirmed

**Comment by leighmcculloch** [comment] 2019-12-05 06:12
@DarkDimius Thanks! I just attempted running `gem install sorbet` on Debian Buster and I'm seeing the same result as here https://github.com/sorbet/sorbet/issues/2250#issuecomment-561529023.

**Comment by DarkDimius** [comment] 2019-12-05 06:14
> I'm seeing the same result

the cron job will kickoff in 2 minutes and should fix it(our nightly publish runs at 22:15 SF time)

**Comment by DarkDimius** [comment] 2019-12-05 06:16
https://buildkite.com/sorbet/sorbet/builds/7914 is the build, you can monitor it with me :-)

**Comment by DarkDimius** [comment] 2019-12-05 06:35
```
0.4.5109 - December 05, 2019 universal-darwin-19 (4.49 MB)
0.4.5109 - December 05, 2019 universal-darwin-14 (4.49 MB)
0.4.5109 - December 05, 2019 universal-darwin-15 (4.49 MB)
0.4.5109 - December 05, 2019 universal-darwin-18 (4.49 MB)
0.4.5109 - December 05, 2019 x86_64-linux (4.27 MB)
0.4.5109 - December 05, 2019 universal-darwin-17 (4.49 MB)
0.4.5109 - December 05, 2019 universal-darwin-16 (4.49 MB) 
```
could you check again?

**Comment by leighmcculloch** [comment] 2019-12-05 07:14
It works! 👏 🎉 🌮 
```
$ gem install sorbet
Fetching sorbet-static-0.4.5109-x86_64-linux.gem
Fetching sorbet-0.4.5109.gem
Successfully installed sorbet-static-0.4.5109-x86_64-linux
```
Thanks @DarkDimius !

**Comment by michaelwebb76** [comment] 2019-12-05 08:37
Bloody legend @DarkDimius !! Thanks so much.

**Comment by arielj** [comment] 2019-12-05 12:13
Great! I'll keep an eye for a few days since some times it was working without the fix (it could be a false positive) but I believe it's actually fixed.

**Comment by arielj** [comment] 2019-12-06 15:31
I'm not sure if this broke something but it's build failed for mac, it looks like it's trying to upload all variants with one command

@DarkDimius 

https://buildkite.com/sorbet/sorbet/builds/7970#54d3f6d0-8c3d-40f3-9bca-67fb77d24344/121-137

**Comment by arielj** [comment] 2019-12-06 15:37
This commit is the problem https://github.com/sorbet/sorbet/commit/b255b4f7eaef7b8ee6975394124d4c80b8b850ec#diff-4eecb4b53b7482e8b253fc25c7c4a573

**Comment by marisveide** [comment] 2019-12-18 08:47
I have the same error when running on ruby `2.6.5` (using `rvm` on MacOS Catalina).

```
maris@Maris-Mac ruby-types % bundle add sorbet    
Fetching gem metadata from https://rubygems.org/............
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Could not find sorbet-static-0.4.5158-universal-darwin-14 in any of the sources
```

**Comment by arielj** [comment] 2019-12-18 14:39
There's an issue with yesterday's changes, linux and darwin-19 versions are missing.

**Comment by marisveide** [comment] 2019-12-18 14:52
> There's an issue with yesterday's changes, linux and darwin-19 versions are missing.
Thanks - please, ping somewhere when it's fixed... 🙇

**Comment by arielj** [comment] 2019-12-18 15:05
@marisveide you can workaround that error specifying a version for `sorbet-static` on your gemfile until the publishing gets fixed. I suppose your problem is that the darwin-19 version is not published, so you can use an "old" version (from 2 days ago) https://rubygems.org/gems/sorbet-static/versions, something like:

    gem 'sorbet-static', '0.4.5144'

**Comment by chrismv48** [comment] 2020-11-23 19:50
Hi, I'm running into this issue after attempting to `bundle install` a project onto my Raspberry Pi (Raspbian GNU/Linux 10 (buster)). It works fine locally on my mac.

I've tried some of the suggested workarounds such as specifying an older version for sorbet or sorbet-static in my Gemfile, but nothing works.

**Comment by xcskier56** [comment] 2020-12-23 15:31
@chrismv48, have you solved this? I'm having an error that started with 0.5.6100 and after updating to the newest, it's still happening. I'm having the issue with CircleCI linux

**Comment by chrismv48** [comment] 2020-12-27 18:08
> @chrismv48, have you solved this? I'm having an error that started with 0.5.6100 and after updating to the newest, it's still happening. I'm having the issue with CircleCI linux

Unfortunately not. In the end I removed Sorbet from the project because I couldn't get it to work. Hoping to use it again when/if this issue is fixed.

**Comment by toddsundsted** [comment] 2020-12-28 10:27
@xcskier56 @chrismv48 i removed the lockfile from the project (and left Sorbet in place). the specific problem i had was the sorbet artifact (sorbet-static/0.5.6189-universal-darwin-14) that did not match the build platform (linux).

**Comment by Zelnox** [comment] 2020-12-30 20:45
We encountered a similar issue this week on CI (linux). I managed to resolve it by updating locally (OSX) bundler from 2.1.4 to 2.2.3 and updating both sorbet and sorbet-runtime. This finally included in the gem lock file both the darwin and linux dependencies for sorbet-static.

Bundler 2.1.4 was including only the Darwin version of the gem in the lock file.

**Comment by will** [comment] 2020-12-30 22:29
Everything was working for me fine, until I recently updated sorbet, and CI started failing with this issue. I update all gems every week or so, so my guess is something sorbet has done in shipping gems change recently. 

I was on bundler 2.1.4 for a long time, and it just started to fail. @Zelnox thanks, upgrading from 2.1.4 to 2.2.3 appears to have fixed it for me too. It added a bunch of new Darwin builds, then also a linux one, which is what CI needed.

```diff
       sorbet-static (= 0.5.6189)
     sorbet-runtime (0.5.6189)
     sorbet-static (0.5.6189-universal-darwin-14)
+    sorbet-static (0.5.6189-universal-darwin-15)
+    sorbet-static (0.5.6189-universal-darwin-16)
+    sorbet-static (0.5.6189-universal-darwin-17)
+    sorbet-static (0.5.6189-universal-darwin-18)
+    sorbet-static (0.5.6189-universal-darwin-19)
+    sorbet-static (0.5.6189-universal-darwin-20)
+    sorbet-static (0.5.6189-x86_64-linux)
     spoom (1.0.7)
       colorize
       sorbet (~> 0.5.5)
@@ -260,4 +267,4 @@ RUBY VERSION
    ruby 2.6.6p146

 BUNDLED WITH
-   2.1.4
+   2.2.3
```

**Comment by flavienhello** [comment] 2023-03-27 21:18
Hi guys, I have the issue when putting it the gem in the gemfile, 

It look something like that and then fail: 

  * sorbet-static-0.5.10685-x86_64-linux
  * sorbet-static-0.5.10687-java
  * sorbet-static-0.5.10687-universal-darwin-14
  * sorbet-static-0.5.10687-universal-darwin-15
  * sorbet-static-0.5.10687-universal-darwin-16
  * sorbet-static-0.5.10687-universal-darwin-17
  * sorbet-static-0.5.10687-universal-darwin-18
  * sorbet-static-0.5.10687-universal-darwin-19
  * sorbet-static-0.5.10687-universal-darwin-20
  * sorbet-static-0.5.10687-universal-darwin-21
  * sorbet-static-0.5.10687-universal-darwin-22
  * sorbet-static-0.5.10687-x86_64-linux
  * sorbet-static-0.5.10689-java
  * sorbet-static-0.5.10689-universal-darwin-14
  * sorbet-static-0.5.10689-universal-darwin-15
  * sorbet-static-0.5.10689-universal-darwin-16
  * sorbet-static-0.5.10689-universal-darwin-17
  * sorbet-static-0.5.10689-universal-darwin-18
  * sorbet-static-0.5.10689-universal-darwin-19
  * sorbet-static-0.5.10689-universal-darwin-20
  * sorbet-static-0.5.10689-universal-darwin-21
  * sorbet-static-0.5.10689-universal-darwin-22
  * sorbet-static-0.5.10689-x86_64-linux
  * sorbet-static-0.5.10690-java
  * sorbet-static-0.5.10690-universal-darwin-14
  * sorbet-static-0.5.10690-universal-darwin-15
  * sorbet-static-0.5.10690-universal-darwin-16
  * sorbet-static-0.5.10690-universal-darwin-17
  * sorbet-static-0.5.10690-universal-darwin-18
  * sorbet-static-0.5.10690-universal-darwin-19
  * sorbet-static-0.5.10690-universal-darwin-20
  * sorbet-static-0.5.10690-universal-darwin-21
  * sorbet-static-0.5.10690-universal-darwin-22
  * sorbet-static-0.5.10690-x86_64-linux
  * sorbet-static-0.5.10693-java
  * sorbet-static-0.5.10693-universal-darwin-14
  * sorbet-static-0.5.10693-universal-darwin-15
  * sorbet-static-0.5.10693-universal-darwin-16
  * sorbet-static-0.5.10693-universal-darwin-17
  * sorbet-static-0.5.10693-universal-darwin-18
  * sorbet-static-0.5.10693-universal-darwin-19
  * sorbet-static-0.5.10693-universal-darwin-20
  * sorbet-static-0.5.10693-universal-darwin-21
  * sorbet-static-0.5.10693-universal-darwin-22
  * sorbet-static-0.5.10693-x86_64-linux
  * sorbet-static-0.5.10696-java
  * sorbet-static-0.5.10696-universal-darwin-14
  * sorbet-static-0.5.10696-universal-darwin-15
  * sorbet-static-0.5.10696-universal-darwin-16
  * sorbet-static-0.5.10696-universal-darwin-17
  * sorbet-static-0.5.10696-universal-darwin-18
  * sorbet-static-0.5.10696-universal-darwin-19
  * sorbet-static-0.5.10696-universal-darwin-20
  * sorbet-static-0.5.10696-universal-darwin-21
  * sorbet-static-0.5.10696-universal-darwin-22
  * sorbet-static-0.5.10696-x86_64-linux
  * sorbet-static-0.5.10705-java
  * sorbet-static-0.5.10705-universal-darwin-14
  * sorbet-static-0.5.10705-universal-darwin-15
  * sorbet-static-0.5.10705-universal-darwin-16
  * sorbet-static-0.5.10705-universal-darwin-17
  * sorbet-static-0.5.10705-universal-darwin-18
  * sorbet-static-0.5.10705-universal-darwin-19
  * sorbet-static-0.5.10705-universal-darwin-20
  * sorbet-static-0.5.10705-universal-darwin-21
  * sorbet-static-0.5.10705-universal-darwin-22
  * sorbet-static-0.5.10705-x86_64-linux
  * sorbet-static-0.5.10706-java
  * sorbet-static-0.5.10707-java
  * sorbet-static-0.5.10707-universal-darwin-14
  * sorbet-static-0.5.10707-universal-darwin-15
  * sorbet-static-0.5.10707-universal-darwin-16
  * sorbet-static-0.5.10707-universal-darwin-17
  * sorbet-static-0.5.10707-universal-darwin-18
  * sorbet-static-0.5.10707-universal-darwin-19
  * sorbet-static-0.5.10707-universal-darwin-20
  * sorbet-static-0.5.10707-universal-darwin-21
  * sorbet-static-0.5.10707-universal-darwin-22
  * sorbet-static-0.5.10707-x86_64-linux
  * sorbet-static-0.5.10710-java
  * sorbet-static-0.5.10710-universal-darwin-14
  * sorbet-static-0.5.10710-universal-darwin-15
  * sorbet-static-0.5.10710-universal-darwin-16
  * sorbet-static-0.5.10710-universal-darwin-17
  * sorbet-static-0.5.10710-universal-darwin-18
  * sorbet-static-0.5.10710-universal-darwin-19
  * sorbet-static-0.5.10710-universal-darwin-20
  * sorbet-static-0.5.10710-universal-darwin-21
  * sorbet-static-0.5.10710-universal-darwin-22
  * sorbet-static-0.5.10710-x86_64-linux
  * sorbet-static-0.5.10712-java
  * sorbet-static-0.5.10712-universal-darwin-14
  * sorbet-static-0.5.10712-universal-darwin-15
  * sorbet-static-0.5.10712-universal-darwin-16
  * sorbet-static-0.5.10712-universal-darwin-17
  * sorbet-static-0.5.10712-universal-darwin-18
  * sorbet-static-0.5.10712-universal-darwin-19
  * sorbet-static-0.5.10712-universal-darwin-20
  * sorbet-static-0.5.10712-universal-darwin-21
  * sorbet-static-0.5.10712-universal-darwin-22
  * sorbet-static-0.5.10712-x86_64-linux
  * sorbet-static-0.5.10716-java
  * sorbet-static-0.5.10718-java
  * sorbet-static-0.5.10721-java
  * sorbet-static-0.5.10722-java
  * sorbet-static-0.5.10722-universal-darwin-14
  * sorbet-static-0.5.10722-universal-darwin-15
  * sorbet-static-0.5.10722-universal-darwin-16
  * sorbet-static-0.5.10722-universal-darwin-17
  * sorbet-static-0.5.10722-universal-darwin-18
  * sorbet-static-0.5.10722-universal-darwin-19
  * sorbet-static-0.5.10722-universal-darwin-20
  * sorbet-static-0.5.10722-universal-darwin-21
  * sorbet-static-0.5.10722-universal-darwin-22
  * sorbet-static-0.5.10722-x86_64-linux
  * sorbet-static-0.5.10731-java
  * sorbet-static-0.5.10731-universal-darwin-14
  * sorbet-static-0.5.10731-universal-darwin-15
  * sorbet-static-0.5.10731-universal-darwin-16
  * sorbet-static-0.5.10731-universal-darwin-17
  * sorbet-static-0.5.10731-universal-darwin-18
  * sorbet-static-0.5.10731-universal-darwin-19
  * sorbet-static-0.5.10731-universal-darwin-20
  * sorbet-static-0.5.10731-universal-darwin-21
  * sorbet-static-0.5.10731-universal-darwin-22
  * sorbet-static-0.5.10731-x86_64-linux
  * sorbet-static-0.5.10735-java
  * sorbet-static-0.5.10735-universal-darwin-14
  * sorbet-static-0.5.10735-universal-darwin-15
  * sorbet-static-0.5.10735-universal-darwin-16
  * sorbet-static-0.5.10735-universal-darwin-17
  * sorbet-static-0.5.10735-universal-darwin-18
  * sorbet-static-0.5.10735-universal-darwin-19
  * sorbet-static-0.5.10735-universal-darwin-20
  * sorbet-static-0.5.10735-universal-darwin-21
  * sorbet-static-0.5.10735-universal-darwin-22
  * sorbet-static-0.5.10735-x86_64-linux
  * sorbet-static-0.5.10736-java
  * sorbet-static-0.5.10736-universal-darwin-14
  * sorbet-static-0.5.10736-universal-darwin-15
  * sorbet-static-0.5.10736-universal-darwin-16
  * sorbet-static-0.5.10736-universal-darwin-17
  * sorbet-static-0.5.10736-universal-darwin-18
  * sorbet-static-0.5.10736-universal-darwin-19
  * sorbet-static-0.5.10736-universal-darwin-20
  * sorbet-static-0.5.10736-universal-darwin-21
  * sorbet-static-0.5.10736-universal-darwin-22
  * sorbet-static-0.5.10736-x86_64-linux

**Comment by 1c7** [comment] 2023-12-25 15:48
## Error message
```
ERROR:  Could not find a valid gem 'sorbet-static' (>= 0.4.4704) (required by 'redcord' (>= 0)) in any repository
ERROR:  Possible alternatives: sorbet-static-and-runtime, poe_static, sorbet-http, urban-static, bard-static, bard_static, butler_static, core-state, draw_static, ecstatic
```

## Reproduce Error
```
docker run -it public.ecr.aws/docker/library/ruby:3.2.2-slim /bin/bash

gem install redcord
```
