### ISSUE TITLE
`srb rbi gems` does not work when using asdf-vm or chruby

### ISSUE THREAD

**Issue by drapergeek** [sorbet/sorbet#1463] opened 2019-08-01 17:19 UTC
It seems that when using the `srb rbi gems` command on a system that is using either [asdf-vm](https://asdf-vm.com/#/) or [chruby](https://github.com/postmodern/chruby), the command will not create any of the `rbi` files

I've verified that by switching to either `rbenv` or `rvm` this problem is resolved.

#### Input

* Brand new rails app with `sorbet` and `sorbet-runtime` installed
* `srb rbi gems`

#### Observed output

```
Generating: sorbet/rbi/gems/
2019-08-01 13:17:48 WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.
[29/29] require_relative './test/test_helper.rb'2019-08-01 13:17:50 WARN Selenium [DEPRECATION] Selenium::WebDriver::Chrome#driver_path= is deprecated. Use Selenium::WebDriver::Chrome::Service#driver_path= instead.

```
There are no generated files in `sorbet/rbi/gems`

#### Expected behavior

Lots of `rbi` files.

A couple other notes:
* This was tested on ruby 2.5 and 2.6
* This was tested on multiple machines on the same project, the only thing that made a difference in the output was the ruby version manager in use.

**Comment by connorshea** [comment] 2019-08-01 23:08
Per Slack, the potential gem location is determined via this regex, and I'm guessing asdf and chruby don't put it in the expected location: https://github.com/sorbet/sorbet/blob/d922217336adea4098f4f8c84309c77f6ff80fd3/gems/sorbet/lib/gem-generator-tracepoint/tracepoint_serializer.rb#L214

**Comment by stevenharman** [comment] 2019-08-15 19:22
The paths used to install gems does vary a bit between version managers. The following shows how the default paths for various managers either succeed or fail, with the current regex:

```ruby
require "pp"

locations = {
  rvm:    "/Users/[homename]/.rvm/gems/ruby-2.6.3/gems/dumb_delegator-0.8.0/lib/dumb_delegator.rb",
  rbenv:  "/Users/[homename]/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dumb_delegator-0.8.0/lib/dumb_delegator.rb",
  asdf:   "/Users/[homename]/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/dumb_delegator-0.8.0/lib/dumb_delegator.rb",
  chruby: "/Users/[homename]/.gem/ruby/2.6.3/gems/dumb_delegator-0.8.0/lib/dumb_delegator.rb",
}

pp locations.transform_values { |location|
  location.match(/^.*\/gems\/(?:ruby-)?[\d.]+(?:@[^\/]+)?(?:\/bundler)?\/gems\/([^\/]+)-([^-\/]+)\//i)
}
#=>
# {
#   :rvm=>
#    #<MatchData
#     "/Users/[homename]/.rvm/gems/ruby-2.6.3/gems/dumb_delegator-0.8.0/"
#     1:"dumb_delegator"
#     2:"0.8.0">,
#   :rbenv=>
#    #<MatchData
#     "/Users/[homename]/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dumb_delegator-0.8.0/"
#     1:"dumb_delegator"
#     2:"0.8.0">,
#   :asdf=>
#    #<MatchData
#     "/Users/[homename]/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/dumb_delegator-0.8.0/"
#     1:"dumb_delegator"
#     2:"0.8.0">,
#   :chruby=> nil
# }

# Using an updated regex
pp locations.transform_values { |location|
  location.match(/^.*\/\.?gems?\/(?:ruby[-\/]?)?[\d.]+(?:@[^\/]+)?(?:\/bundler)?\/gems\/([^\/]+)-([^-\/]+)\//i)
}
#=>
# {
#   :rvm=>
#    #<MatchData
#     "/Users/[homename]/.rvm/gems/ruby-2.6.3/gems/dumb_delegator-0.8.0/"
#     1:"dumb_delegator"
#     2:"0.8.0">,
#   :rbenv=>
#    #<MatchData
#     "/Users/[homename]/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/dumb_delegator-0.8.0/"
#     1:"dumb_delegator"
#     2:"0.8.0">,
#   :asdf=>
#    #<MatchData
#     "/Users/[homename]/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/dumb_delegator-0.8.0/"
#     1:"dumb_delegator"
#     2:"0.8.0">,
#   :chruby=>
#    #<MatchData
#     "/Users/[homename]/.gem/ruby/2.6.3/gems/dumb_delegator-0.8.0/"
#     1:"dumb_delegator"
#     2:"0.8.0">
# }
```

Interestingly, the `asdf` users should be fine as that path matches the current regex. But as @connorshea suggests, `chruby` users need a tweak to match their install path. So... perhaps there's more to this story?

I'm happy to open a PR with the tweaked regex, but a little unclear on how I'd write a test for that, and am looking for guidance/suggestions on that.

**Comment by stevenharman** [comment] 2019-08-15 21:29
Ah... I see why `asdf` was also failing, and why the above tweak alone is not enough. The first regex used to extract the gem name from the location string is looking for standard lib gems. But it's loose enough that it's also matching the `asdf` path.

```ruby
asdf_gem = "/Users/[homename]/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/dumb_delegator-0.8.0/"

asdf_gem.match(/^.*\/(ruby)\/([\d.]+)\//)
#=> #<MatchData "/Users/[homename]/.asdf/installs/ruby/2.6.3/" 1:"ruby" 2:"2.6.3">
```

This leads me to think we should make that first regex more strict, and also tweak the later to catch `chruby` paths. I'm playing with some test for this now.

**Comment by tt** [comment] 2019-08-16 08:40
@stevenharman, do you think it would be better to use `Gem.path`?

It should be set to the appropriate gem paths even when `GEM_PATH` is unset.

I expect it will therefore work with all version managers and even supports the default Ruby installation on macOS which also stores gems in `/Library/Ruby/Gems/2.3.0` and `/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0` (both unmatched by all suggested patterns). 

You can see the paths by running `gem environment`.

This is what I would change: https://github.com/sorbet/sorbet/compare/master...tt:match-all-known-gem-paths

I'm happy to open a pull request with the change. Let me know if I should.

**Comment by stevenharman** [comment] 2019-08-16 14:28
@tt I was considering something along those lines as well, though perhaps just `Gem.dir` as that's supposed to be ["the path where gems are to be installed."](https://rubyapi.org/2.6/o/gem#method-c-dir). I'm thinking limiting to that directory makes sense since that's where any Gems would have been installed, based on the currently active Ruby, by RubyGems/Bundler.

Here are were Stdlib, extensions (e.g., OS-specific stuff that's not a gem), and gems (including those locked by Bundler to a path, Git SHA, etc...) are installed on my machine, using `rbenv`:

```
StdLib:        ~/.rbenv/versions/2.6.2/lib/ruby/2.6.0 
Extensions:    ~/.rbenv/versions/2.6.2/lib/ruby/site_ruby/2.6.0
Gems:          ~/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems
Bundler:       ~/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/bundler/gems
```

And here's where RubyGems says things should go:

```ruby
Gem.dir  #=>  "~/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0"
Gem.path #=> ["~/.gem/ruby/2.6.0",
         #    "~/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0"]
```

All of which is to say, yes, we could probably use `Gem.dir` as a prefix to the path when trying to determine if a `required` file is a Gem.

And we also need to tighten the regex that's looking for StdLib stuff to make sure it's limiting to paths with `lib/` prefixing the `ruby/1.2.3` portion of the string. That regex should probably be something like

```ruby
/^.*\/lib\/(ruby)\/([\d.]+)\//
```

I've added some new tests for `chrubby`-looking gem paths. I'll also add some for `asdf`-looking paths, and then try the `Gem.dir` approach. Maybe a PR on this fine Friday!

**Comment by panthomakos** [comment] 2019-08-20 00:31
Any updates on this ticket? I noticed there is a similar issue when running this command in the Ruby Docker image (system installed Ruby). I suspect that using the Gem dir would resolve that issue as well.

**Comment by stevenharman** [comment] 2019-08-21 19:31
@panthomakos could you do the following for me, from w/in the running Docker image, and reply with the output?

```sh
$ gem install dumb_delegator
$ # we want the output from the following...
$ ruby -e 'puts $LOADED_FEATURES.last(2); require "dumb_delegator"; puts $LOADED_FEATURES.last(2)'
```

Then to confirm the environment is what we expect:

```sh
$ irb
irb: Gem.dir  #=> We want this output
irb: Gem.path #=> ... and this output too.
```

Thank you!

**Comment by panthomakos** [comment] 2019-08-21 22:30
Using the official 2.4 image:

```
root@b75a23c9e2a2:/usr/src/app# ruby -e 'puts $LOADED_FEATURES.last(2); require "dumb_delegator"; puts $LOADED_FEATURES.last(2)'
/usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean/formatter.rb
/usr/local/lib/ruby/gems/2.4.0/gems/did_you_mean-1.1.0/lib/did_you_mean.rb
/usr/local/bundle/gems/dumb_delegator-0.8.0/lib/dumb_delegator/version.rb
/usr/local/bundle/gems/dumb_delegator-0.8.0/lib/dumb_delegator.rb
```

```
irb(main):001:0> Gem.dir
=> "/usr/local/bundle"
irb(main):002:0> Gem.path
=> ["/root/.gem/ruby/2.4.0", "/usr/local/lib/ruby/gems/2.4.0", "/usr/local/bundle"]
```

Confirmed this with the official Ruby 2.5 image as well:

```
$ docker run -it --rm --entrypoint /bin/bash ruby:2.5
$ gem install dumb_delegator
$ ruby -e 'puts $LOADED_FEATURES.last(2); require "dumb_delegator"; puts $LOADED_FEATURES.last(2)'
/usr/local/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/formatters/plain_formatter.rb
/usr/local/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean.rb
/usr/local/bundle/gems/dumb_delegator-0.8.0/lib/dumb_delegator/version.rb
/usr/local/bundle/gems/dumb_delegator-0.8.0/lib/dumb_delegator.rb

$ irb
irb(main):001:0> Gem.dir
=> "/usr/local/bundle"
irb(main):002:0> Gem.path
=> ["/root/.gem/ruby/2.5.0", "/usr/local/lib/ruby/gems/2.5.0", "/usr/local/bundle"]
```

**Comment by ianks** [comment] 2020-01-14 13:37
any movement here?

**Comment by johngun3** [comment] 2020-04-23 22:35
I just ran into this exact problem and found this issue after the better part of a day of utter confusion. Was using a ruby install managed by chruby and I just installed rvm and the problem is resolved. To prevent pain for those who will surely come after me could we get this over the finish line? I'd be happy to help if I can.

**Comment by wchrisjohnson** [comment] 2022-05-18 20:03
Is this ever going to be addressed?

**Comment by jez** [comment] 2022-07-27 20:56
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca

**Closed by jez** 2022-07-27 20:56 UTC
Labels: bug, unconfirmed, srb
