### ISSUE TITLE
Unreachable code for `T.must().nil?` check not detected in do block

### ISSUE THREAD

**Issue by sedouard** [sorbet/sorbet#2565] opened 2020-01-28 22:05 UTC
#### Input

https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer).returns(String)%7D%0A%20%20def%20self.bar(x)%0A%20%20%20%20x%20%3D%20%5B'string'%2C%20nil%2C%20'string'%5D%0A%20%20%20%20x.each%20do%20%7Citem%7C%0A%20%20%20%20%20%20next%20if%20T.must(item).nil%3F%0A%20%20%20%20%20%20puts%20'hello'%20%0A%20%20%20%20end%0A%20%20%20%20%22done%23%7Bx%7D%22%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20A.bar(3)%0Aend

```ruby
# typed: true
class A
  extend T::Sig

  def self.bar
    x = ['string', nil, 'string']
    x.each do |item|
      next if T.must(item).nil?
      puts 'hello' 
    end
    "done#{x}"
  end
end

def main
  A.bar
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

It should mark line 9 as unreachable code. We already have `nil?`checks for unreachable code in samples like this one:

https://sorbet.run/#%23%20typed%3A%20true%0A%0Ax%20%3D%20T.let(10%2C%20T.nilable(Integer))%0A%0Aif%20T.must(x).nil%3F%0A%20%20T.reveal_type(x)%0Aend%0A%0Ay%20%3D%20T.must(x)%0Aif%20y.nil%3F%0A%20%20T.reveal_type(y)%0Aend

So we really should have an unreachable code error here.

**Comment by trevor-stripe** [comment] 2020-01-28 22:08
An additional example showing the difference in behavior:

[sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Ax%20%3D%20T.let(10%2C%20T.nilable(Integer))%0A%0Aif%20T.must(x).nil%3F%0A%20%20T.reveal_type(x)%0Aend%0A%0Ay%20%3D%20T.must(x)%0Aif%20y.nil%3F%0A%20%20T.reveal_type(y)%0Aend)
```ruby
# typed: true

x = T.let(10, T.nilable(Integer))

if T.must(x).nil?
  T.reveal_type(x)
end

y = T.must(x)
if y.nil?
  T.reveal_type(y)
end
```

**Comment by DarkDimius** [comment] 2020-01-28 22:16
The original case is not a bug: we cant guarantee that the block in `each` will ever execute.

The modified case is due to knoweldge filters deciding that we don't need to track knowledge for temporary of `T.must(x)`.

Overall, this is not a bug, but an enhancement, our control flow tracking is best effort. 
Given that we're unlikely to work on it any time soon, closing.

**Closed by DarkDimius** 2020-01-28 22:16 UTC
Labels: bug
