### ISSUE TITLE
Passing generic class to generic method has spurious error

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#57] opened 2019-01-16 22:04 UTC
https://sorbet.run/#extend%20T%3A%3ASig%0A%0Aclass%20A%0A%20%20extend%20T%3A%3AGeneric%0A%20%20%0A%20%20Elem%20%3D%20type_member%0Aend%0A%0Asig%20%7Btype_parameters(%3AU).params(x%3A%20A%5BT.type_parameter(%3AU)%5D).void%7D%0Adef%20foo(x)%0A%20%20T.reveal_type(x)%0Aend%0A%0Afoo(A.new)%0Afoo(A%5BInteger%5D.new)

^ Using a {{T.type_parameter}} to accept a class generic in an arbitrary type fails in a way that exposes our internals.

The expected behavior for this file is that it type checks, because the {{T.type_parameter(:U)}} is compatible with {{Integer}}.

Originally reported by @jez-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1238

**Comment by jez** [comment] 2019-09-27 05:15
Dupe of #1718. Closing this one because the other one has a better example.

**Closed by jez** 2019-09-27 05:15 UTC
