### ISSUE TITLE
Error on `type_parameters` with default value

### ISSUE THREAD

**Issue by jbourassa** [sorbet/sorbet#4590] opened 2021-09-09 15:16 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0Asig%20do%0A%20%20type_parameters%28%3AA%29%0A%20%20%20%20.params%28v%3A%20T.nilable%28T.type_parameter%28%3AA%29%29%29%0A%20%20%20%20.void%0Aend%0Adef%20assert_result%28v%20%3D%20nil%29%3B%20end)

```ruby
# typed: true
extend T::Sig
sig do
  type_parameters(:A)
    .params(v: T.nilable(T.type_parameter(:A)))
    .void
end
def assert_result(v = nil); end
```

#### Observed output

```
editor.rb:7: Expression does not have a fully-defined type (Did you reference another class's type members?) https://srb.help/7011
     7 |  def assert_result(v = nil)
                                ^^^
Errors: 1
```

#### Expected behavior

Specifying a nil default value should not result in an error.

- - -

Note that removing the default value (`= nil`) makes the error disappear.

**Comment by jez** [comment] 2021-09-09 18:06
Thanks for the report. It might not look like it, but this is a duplicate of this issue:

https://github.com/sorbet/sorbet/issues/1715

unfortunately it's hard to fix so you'll have to work around the absence of this feature for the time being.

**Closed by jez** 2021-09-09 18:06 UTC
Labels: bug, unconfirmed
