### ISSUE TITLE
Type check fails recognizing nil-type after an IF

### ISSUE THREAD

**Issue by itarato** [sorbet/sorbet#8286] opened 2024-11-05 20:49 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Ax%20%3D%204%0Ax%20%3D%20if%20x%20%3D%3D%201%0A%20%201%0Aend%0A%0AT.reveal_type%28x%29%0A)

```ruby
x = 4
x = if x == 1
  1
end

T.reveal_type(x)
```

#### Observed output

```

# typed: strict
extend T::Sig

x = 4
x = if x == 1
  1
end

T.reveal_type(x)



editor.rb:9: Revealed type: Integer https://srb.help/7014
     9 |T.reveal_type(x)
        ^^^^^^^^^^^^^^^^
  Got Integer originating from:
    editor.rb:4:
     4 |x = 4
            ^
    editor.rb:6:
     6 |  1
          ^
Errors: 1
```

#### Expected behavior

Running the code above results `x = nil`. Expected type is `T.nilable(Integer)`.

**Comment by jez** [comment] 2024-11-05 21:08
Hey, thanks for the report, and sorry that you ran into this.

This is a duplicate of #7936. I attempted a solution before, but the simple solution caused tens of thousands of more problems than it solved, and I have not had a chance to revisit it.

**Closed by jez** 2024-11-05 21:08 UTC
Labels: bug, unconfirmed
