### ISSUE TITLE
LSP: Does not report resolver errors in files that lack `typed` sigil. 

### ISSUE THREAD

**Issue by hurricup** [sorbet/sorbet#1187] opened 2019-07-03 07:09 UTC
# Test sample:
```
class Hello
    def something(x)

    end
end

def main
    puts Helo.new
end
```
# Protocol trace:
```
From IDE: 
{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///home/user/RubymineProjects/untitled57/test.rb","languageId":"ruby","version":157,"text":"class Hello\n    def something(x)\n\n    end\nend\n\ndef main\n    puts Helo.new\nend"}}}

From server:
{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/user/RubymineProjects/untitled57/test.rb","diagnostics":[{"range":{"start":{"line":7,"character":9},"end":{"line":7,"character":13}},"severity":1,"code":5002,"message":"Unable to resolve constant `Helo`","relatedInformation":[{"location":{"uri":"https://github.com/sorbet/sorbet/tree/master/rbi/stdlib/gem.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":10}}},"message":"Did you mean: `Gem`?"},{"location":{"uri":"https://github.com/sorbet/sorbet/tree/master/rbi/core/file.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":15}}},"message":"Did you mean: `File`?"},{"location":{"uri":"https://github.com/sorbet/sorbet/tree/master/rbi/core/hash.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":19}}},"message":"Did you mean: `Hash`?"},{"location":{"uri":"https://srb.help/5002","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}}},"message":"Click for more information on this error."}]}]}} 

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/user/RubymineProjects/untitled57/test.rb","diagnostics":[]}}
```
The second request resets diagnostic data in the client.
server was built from tonight's master

**Comment by DarkDimius** [comment] 2019-07-03 08:11
Hi Alexandr, can you share the entire trace?
AFAIK Sorbet never sends to replies for the same file for a single didOpen call thus this seems surprising for me. We also don't observe this issue with VSCode

**Comment by DarkDimius** [comment] 2019-07-03 08:17
You can also observe the complete LSP log in browser console in https://sorbet.run/

Here is a complete log for this snippet, with my annotations in #
```
# initialization handshake
client.ts:166 Read: {"jsonrpc":"2.0","id":0,"method":"initialize","params":{"rootPath":null,"rootUri":null,"capabilities":{"workspace":{"applyEdit":true,"workspaceEdit":{"documentChanges":true},"didChangeConfiguration":{"dynamicRegistration":true},"didChangeWatchedFiles":{"dynamicRegistration":true},"symbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]}},"executeCommand":{"dynamicRegistration":true},"workspaceFolders":true},"textDocument":{"publishDiagnostics":{"relatedInformation":true},"synchronization":{"dynamicRegistration":true,"willSave":true,"willSaveWaitUntil":true,"didSave":true},"completion":{"dynamicRegistration":true,"contextSupport":true,"completionItem":{"snippetSupport":true,"commitCharactersSupport":true,"documentationFormat":["markdown","plaintext"],"deprecatedSupport":true,"preselectSupport":true},"completionItemKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]}},"hover":{"dynamicRegistration":true,"contentFormat":["markdown","plaintext"]},"signatureHelp":{"dynamicRegistration":true,"signatureInformation":{"documentationFormat":["markdown","plaintext"]}},"definition":{"dynamicRegistration":true},"references":{"dynamicRegistration":true},"documentHighlight":{"dynamicRegistration":true},"documentSymbol":{"dynamicRegistration":true,"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":true},"codeAction":{"dynamicRegistration":true,"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"codeLens":{"dynamicRegistration":true},"formatting":{"dynamicRegistration":true},"rangeFormatting":{"dynamicRegistration":true},"onTypeFormatting":{"dynamicRegistration":true},"rename":{"dynamicRegistration":true},"documentLink":{"dynamicRegistration":true},"typeDefinition":{"dynamicRegistration":true},"implementation":{"dynamicRegistration":true},"colorProvider":{"dynamicRegistration":true},"foldingRange":{"dynamicRegistration":true,"rangeLimit":5000,"lineFoldingOnly":true}}},"trace":"off","workspaceFolders":null}}
client.ts:161 Write: {"jsonrpc":"2.0","id":0,"requestMethod":"initialize","result":{"capabilities":{"textDocumentSync":1,"hoverProvider":true,"completionProvider":{"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"referencesProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true}}}
client.ts:166 Read: {"jsonrpc":"2.0","method":"initialized","params":{}}
# default snippet in https://sorbet.run/
client.ts:166 Read: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"inmemory://model/default","languageId":"ruby","version":1,"text":"# typed: true\nclass A\n  extend T::Sig\n\n  sig {params(x: Integer).returns(String)}\n  def bar(x)\n    x.to_s\n  end\nend\n\ndef main\n  A.new.barr(91)   # error: Typo!\n  A.new.bar(\"91\")  # error: Type mismatch!\nend"}}}
client.ts:161 Write: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"inmemory://model/default","diagnostics":[{"range":{"start":{"line":11,"character":2},"end":{"line":11,"character":16}},"severity":1,"code":7003,"message":"Method `barr` does not exist on `A`","relatedInformation":[{"location":{"uri":"inmemory://model/default","range":{"start":{"line":5,"character":2},"end":{"line":5,"character":12}}},"message":"Did you mean: `A#bar`?"},{"location":{"uri":"https://srb.help/7003","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}}},"message":"Click for more information on this error."}]},{"range":{"start":{"line":12,"character":2},"end":{"line":12,"character":17}},"severity":1,"code":7002,"message":"Expected `Integer` but found `String(\"91\")` for argument `x`","relatedInformation":[{"location":{"uri":"inmemory://model/default","range":{"start":{"line":4,"character":14},"end":{"line":4,"character":15}}},"message":"Method `A#bar` has specified `x` as `Integer`"},{"location":{"uri":"inmemory://model/default","range":{"start":{"line":12,"character":12},"end":{"line":12,"character":16}}},"message":"Got String(\"91\") originating from:"},{"location":{"uri":"https://srb.help/7002","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}}},"message":"Click for more information on this error."}]}]}}
# My mouse travels around in order to paste your example from buffer
client.ts:166 Read: {"jsonrpc":"2.0","id":1,"method":"textDocument/hover","params":{"textDocument":{"uri":"inmemory://model/default"},"position":{"line":10,"character":1}}}
client.ts:161 Write: {"jsonrpc":"2.0","id":1,"requestMethod":"textDocument/hover","result":{"contents":{"kind":"markdown","value":"```ruby\nsig {returns(T.untyped)}\n```"}}}
# I actually paste the example from this issue
client.ts:166 Read: {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"uri":"inmemory://model/default","version":2},"contentChanges":[{"text":"# typed: true\nclass Hello\n    def something(x)\n\n    end\nend\n\ndef main\n    puts Helo.new\nend"}]}}
client.ts:161 Write: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"inmemory://model/default","diagnostics":[{"range":{"start":{"line":8,"character":9},"end":{"line":8,"character":13}},"severity":1,"code":5002,"message":"Unable to resolve constant `Helo`","relatedInformation":[{"location":{"uri":"https://github.com/sorbet/sorbet/tree/beecfbcc014c33282ea65f03a61fbb74535a5435/rbi/stdlib/gem.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":10}}},"message":"Did you mean: `Gem`?"},{"location":{"uri":"https://github.com/sorbet/sorbet/tree/beecfbcc014c33282ea65f03a61fbb74535a5435/rbi/core/file.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":15}}},"message":"Did you mean: `File`?"},{"location":{"uri":"https://github.com/sorbet/sorbet/tree/beecfbcc014c33282ea65f03a61fbb74535a5435/rbi/core/hash.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":19}}},"message":"Did you mean: `Hash`?"},{"location":{"uri":"https://srb.help/5002","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}}},"message":"Click for more information on this error."}]}]}}
```

As you see, there is no second `textDocument/publishDiagnostics` from Sorbet. In order to trigger a second one, there has to be a request from client.

**Comment by hurricup** [comment] 2019-07-03 09:35
Is it possible to start an lsp server with protocol logging?
Here is the full trace I can see in my logs:
```
{"jsonrpc":"2.0","id":"1","method":"initialize","params":{"processId":null,"rootPath":"/home/user/RubymineProjects/untitled57","rootUri":"file:///home/user/RubymineProjects/untitled57","capabilities":{"workspace":{"applyEdit":false,"workspaceEdit":{"documentChanges":true,"resourceOperations":["create","delete","rename"],"failureHandling":"transactional"},"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":false},"symbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"dynamicRegistration":false},"executeCommand":{"dynamicRegistration":false},"workspaceFolders":true,"configuration":false},"textDocument":{"synchronization":{"willSave":false,"willSaveWaitUntil":false,"didSave":false,"dynamicRegistration":true},"completion":{"completionItem":{"snippetSupport":false,"commitCharactersSupport":false,"documentationFormat":["plaintext"],"deprecatedSupport":false,"preselectSupport":false},"completionItemKind":{},"dynamicRegistration":true},"hover":{"contentFormat":["plaintext"],"dynamicRegistration":false},"signatureHelp":{"signatureInformation":{"documentationFormat":["plaintext"],"parameterInformation":{"labelOffsetSupport":false}},"dynamicRegistration":false},"references":{"dynamicRegistration":false},"documentHighlight":{"dynamicRegistration":false},"documentSymbol":{"symbolKind":{"valueSet":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26]},"hierarchicalDocumentSymbolSupport":false,"dynamicRegistration":false},"formatting":{"dynamicRegistration":false},"rangeFormatting":{"dynamicRegistration":false},"onTypeFormatting":{"dynamicRegistration":false},"declaration":{"linkSupport":false,"dynamicRegistration":false},"definition":{"linkSupport":false,"dynamicRegistration":false},"typeDefinition":{"linkSupport":false,"dynamicRegistration":false},"implementation":{"linkSupport":false,"dynamicRegistration":false},"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["quickfix","refactor","refactor.extract","refactor.inline","source","source.organizeImports","refactor.rewrite"]}},"dynamicRegistration":false},"codeLens":{"dynamicRegistration":false},"documentLink":{"dynamicRegistration":false},"colorProvider":{"dynamicRegistration":false},"rename":{"prepareSupport":false,"dynamicRegistration":false},"publishDiagnostics":{"relatedInformation":false},"foldingRange":{"rangeLimit":2147483647,"lineFoldingOnly":false,"dynamicRegistration":false}}}}} 

{"jsonrpc":"2.0","id":"1","requestMethod":"initialize","result":{"capabilities":{"textDocumentSync":1,"hoverProvider":true,"completionProvider":{"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"referencesProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true}}} 

{"jsonrpc":"2.0","method":"initialized","params":{}} 

{"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///home/user/RubymineProjects/untitled57/test.rb","languageId":"ruby","version":157,"text":"class Hello\n    def something(x)\n\n    end\nend\n\ndef main\n    puts Helo.new\nend"}}} 

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/user/RubymineProjects/untitled57/test.rb","diagnostics":[{"range":{"start":{"line":7,"character":9},"end":{"line":7,"character":13}},"severity":1,"code":5002,"message":"Unable to resolve constant `Helo`","relatedInformation":[{"location":{"uri":"https://github.com/sorbet/sorbet/tree/master/rbi/stdlib/gem.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":10}}},"message":"Did you mean: `Gem`?"},{"location":{"uri":"https://github.com/sorbet/sorbet/tree/master/rbi/core/file.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":15}}},"message":"Did you mean: `File`?"},{"location":{"uri":"https://github.com/sorbet/sorbet/tree/master/rbi/core/hash.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":19}}},"message":"Did you mean: `Hash`?"},{"location":{"uri":"https://srb.help/5002","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}}},"message":"Click for more information on this error."}]}]}} 

{"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/user/RubymineProjects/untitled57/test.rb","diagnostics":[]}} 
```
Additionally, i've changed document (changed `Helo` to `Hello`) and didn't get new diagnostics
```
{"jsonrpc":"2.0","method":"textDocument/didChange","params":{"textDocument":{"version":231,"uri":"file:///home/user/RubymineProjects/untitled57/test.rb"},"contentChanges":[{"range":{"start":{"line":7,"character":12},"end":{"line":7,"character":12}},"rangeLength":0,"text":"class Hello\n    def something(x)\n\n    end\nend\n\ndef main\n    puts Hello.new\nend\n\n\n"}]}}
```
And nothing from server side.
here is the command used to run:
`sorbet --lsp --dir /home/user/RubymineProjects/untitled57 --disable-watchman --enable-all-experimental-lsp-features --silence-dev-message`
Btw, why do I need to provide a dir when starting server? Shouldn't root be set up with initialization?

```

**Comment by DarkDimius** [comment] 2019-07-03 16:04
> Is it possible to start an lsp server with protocol logging?

pass `-vv` for `verbose`


> Btw, why do I need to provide a dir when starting server? Shouldn't root be set up with initialization?

No good reason externally. Stripe runs Sorbet on a different machine from one that runs IDE and they talk over network.

**Comment by jvilk-stripe** [comment] 2019-07-03 17:59
@hurricup The file you're opening is not typed, so Sorbet won't report errors. 

[See on Sorbet.run](https://sorbet.run/#class%20Hello%0A%20%20%20%20def%20something(x)%0A%0A%20%20%20%20end%0Aend%0A%0Adef%20main%0A%20%20%20%20puts%20Helo.new%0Aend):
```ruby
class Hello
    def something(x)

    end
end

def main
    puts Helo.new
end
```

I suspect what's happening is the following:

* When Sorbet initializes, it reads the contents of `/home/user/RubymineProjects/untitled57`, which contains a `test.rb` with `# typed: true`. It discovers a type error, and reports it to the editor.
* Sorbet processes the `didOpen`, which lacks the type sigil, and the file no longer has errors.

I don't believe this is a bug, so I'm closing this thread. Feel free to reopen if I'm wrong!

**Comment by jvilk-stripe** [comment] 2019-07-03 18:02
Actually, I'm reopening; I realized that CLI Sorbet reports errors, so my hunch was incorrect. 🤦‍♂

**Comment by jvilk-stripe** [comment] 2019-07-03 18:05
[Adding `# typed: false` fixes the issue](https://sorbet.run/#%23%20typed%3A%20false%0Aclass%20Hello%0A%20%20%20%20def%20something(x)%0A%0A%20%20%20%20end%0Aend%0A%0Adef%20main%0A%20%20%20%20puts%20Helo.new%0Aend), but we should probably treat the file as if it's implicitly `# typed: false`:

**Comment by hurricup** [comment] 2019-07-03 18:07
I see. I'll try this tomorrow. Thanks

**Comment by hurricup** [comment] 2019-07-03 18:08
Is missing of diagnostic on document change the same story?

**Comment by DarkDimius** [comment] 2019-07-03 18:11
@jvilk-stripe I'm still unable to reproduce. if you open
https://sorbet.run/#class%20Hello%0A%20%20%20%20def%20something(x)%0A%0A%20%20%20%20end%0Aend%0A%0Adef%20main%0A%20%20%20%20puts%20Helo.new%0Aend
there's a single `textDocument/publishDiagnostics`
AFAIK there's no code between LSP and normal pass that could have treated this file differently.
Are you sure your story is what is happening?

**Comment by DarkDimius** [comment] 2019-07-03 18:12
> Adding # typed: false fixes the issue, but we should probably treat the file as if it's implicitly # typed: false.

This is what Sorbet does by default and has been doing since introduction of typed sigils

**Comment by jvilk-stripe** [comment] 2019-07-03 18:20
@DarkDimius Look at your link again. CLI reports the error (on right), LSP (on left) does not. There's no squiggle.

There's a difference in behavior between what LSP does during initialization (when it first reads the files from disk) and what it does to process changes (when didOpen happens). During initialization, LSP reports the same error as the CLI. Once didOpen happens, though, it no longer reports errors for the file.

**Comment by jvilk-stripe** [comment] 2019-07-03 18:21
> Is missing of diagnostic on document change the same story?

Yes, it's the same issue. During initialization (when Sorbet reads things from disk), it reports the error. But once it's open in the editor, it stops reporting the error.

It all comes down to the missing typed sigil. This is a bug in Sorbet that we should fix.

**Comment by DarkDimius** [comment] 2019-07-03 18:30
@jvilk-stripe 
> @DarkDimius Look at your link again. CLI reports the error (on right), LSP (on left) does not. There's no squiggle.

> There's a difference in behavior between what LSP does during initialization (when it first reads the files from disk) and what it does to process changes (when didOpen happens). During initialization, LSP reports the same error as the CLI. Once didOpen happens, though, it no longer reports errors for the file.

I think we disagree.
This is specifically a quirk of sorbet.run. It actually runs sorbet _twice_. Once by running LSP, once, by running with `-e` 
https://github.com/sorbet/sorbet/blob/7bbc8c652d4c1ea044d01d59778beea3a5627fb1/emscripten/main.cc#L16
Note that we force `-e` to `typed: true` if it doesn't have a sigil:
https://github.com/sorbet/sorbet/blob/7bbc8c652d4c1ea044d01d59778beea3a5627fb1/main/realmain.cc#L393-L396


> During initialization, LSP reports the same error as the CLI. 

AFAIK this isn't true, see above & message log from communication

**Comment by DarkDimius** [comment] 2019-07-03 18:42
IRL'd with @jvilk-stripe and indeed, there's a bug. He was right. I think we have both effects, we have the fact that sorbet.run forces stuff into `typed: true` mode for right pane _and_ we have a bug.

```
[T12476287][2019-07-03T11:39:25.554276] Read: {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"colorProvider":null,"completion":{"completionItem":{"snippetSupport":false}},"signatureHelp":{"signatureInformation":{"parameterInformation":{"labelOffsetSupport":true}}}},"workspace":{"applyEdit":true,"didChangeWatchedFiles":{"dynamicRegistration":true}}},"initializationOptions":{"cacheDirectory":"/tmp/cquery","completion":{"filterAndSort":false}},"processId":70687,"rootPath":"/Users/dmitry/.empty","rootUri":"file:///Users/dmitry/.empty","trace":"off"},"id":1}
[T12476275][2019-07-03T11:39:25.557297] Write: {"jsonrpc":"2.0","id":1,"requestMethod":"initialize","result":{"capabilities":{"textDocumentSync":1,"hoverProvider":true,"completionProvider":{"triggerCharacters":["."]},"signatureHelpProvider":{"triggerCharacters":["(",","]},"definitionProvider":true,"referencesProvider":true,"documentSymbolProvider":true,"workspaceSymbolProvider":true}}}
[T12476287][2019-07-03T11:39:25.559594] Read: {"jsonrpc":"2.0","method":"initialized","params":{}}
[T12476287][2019-07-03T11:39:25.561689] Read: {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{"initializationOptions":{"cacheDirectory":"/tmp/cquery","completion":{"filterAndSort":false}}}}}
[T12476287][2019-07-03T11:39:25.564715] Read: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"ruby","text":"# typed: true\n\n1 + \"s\"\n","uri":"file:///Users/dmitry/.empty/a.rb","version":0}}}
[T12476275][2019-07-03T11:39:25.629629] Write: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/dmitry/.empty/a.rb","diagnostics":[{"range":{"start":{"line":2,"character":0},"end":{"line":2,"character":7}},"severity":1,"code":7002,"message":"Expected `Integer` but found `String(\"s\")` for argument `arg0`","relatedInformation":[{"location":{"uri":"https://github.com/sorbet/sorbet/tree/1beae38af163add1e13e897e4771727a0a40c338/rbi/core/integer.rbi#L104","range":{"start":{"line":103,"character":8},"end":{"line":103,"character":12}}},"message":"Method `Integer#+` has specified `arg0` as `Integer`"},{"location":{"uri":"file:///Users/dmitry/.empty/a.rb","range":{"start":{"line":2,"character":4},"end":{"line":2,"character":7}}},"message":"Got String(\"s\") originating from:"},{"location":{"uri":"https://srb.help/7002","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}}},"message":"Click for more information on this error."}]}]}}
[T12476275][2019-07-03T11:39:25.629673] Write: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/dmitry/.empty/foo.rb","diagnostics":[{"range":{"start":{"line":7,"character":9},"end":{"line":7,"character":13}},"severity":1,"code":5002,"message":"Unable to resolve constant `Helo`","relatedInformation":[{"location":{"uri":"https://github.com/sorbet/sorbet/tree/1beae38af163add1e13e897e4771727a0a40c338/rbi/stdlib/gem.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":10}}},"message":"Did you mean: `Gem`?"},{"location":{"uri":"https://github.com/sorbet/sorbet/tree/1beae38af163add1e13e897e4771727a0a40c338/rbi/core/file.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":15}}},"message":"Did you mean: `File`?"},{"location":{"uri":"https://github.com/sorbet/sorbet/tree/1beae38af163add1e13e897e4771727a0a40c338/rbi/core/hash.rbi#L3","range":{"start":{"line":2,"character":0},"end":{"line":2,"character":19}}},"message":"Did you mean: `Hash`?"},{"location":{"uri":"https://srb.help/5002","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}}},"message":"Click for more information on this error."}]}]}}
[T12476275][2019-07-03T11:39:25.631184] Write: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/dmitry/.empty/a.rb","diagnostics":[{"range":{"start":{"line":2,"character":0},"end":{"line":2,"character":7}},"severity":1,"code":7002,"message":"Expected `Integer` but found `String(\"s\")` for argument `arg0`","relatedInformation":[{"location":{"uri":"https://github.com/sorbet/sorbet/tree/1beae38af163add1e13e897e4771727a0a40c338/rbi/core/integer.rbi#L104","range":{"start":{"line":103,"character":8},"end":{"line":103,"character":12}}},"message":"Method `Integer#+` has specified `arg0` as `Integer`"},{"location":{"uri":"file:///Users/dmitry/.empty/a.rb","range":{"start":{"line":2,"character":4},"end":{"line":2,"character":7}}},"message":"Got String(\"s\") originating from:"},{"location":{"uri":"https://srb.help/7002","range":{"start":{"line":0,"character":0},"end":{"line":0,"character":0}}},"message":"Click for more information on this error."}]}]}}
[T12476287][2019-07-03T11:40:57.507089] Read: {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"ruby","text":"class Hello\n    def something(x)\n\n    end\nend\n\ndef main\n    puts Helo.new\nend\n","uri":"file:///Users/dmitry/.empty/foo.rb","version":0}}}
[T12476275][2019-07-03T11:40:57.508242] Write: {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///Users/dmitry/.empty/foo.rb","diagnostics":[]}}
```

**Closed** 2019-07-03 20:57 UTC
Labels: bug, unconfirmed, waiting on author
