### ISSUE TITLE
Incorrect code is unreachable error when a `call` method is defined using class_eval

### ISSUE THREAD

**Issue by fcheung** [sorbet/sorbet#6448] opened 2022-10-01 12:16 UTC
I've come across an issue where when defining a method `call` inside a class_eval block (originally this was inside a rspec context) sorbet seems to think method blocks are never reached

In the below example I don't get an error if:
- I comment out the definition of call
- I define call in the main body of Dummy (ie `class Dummy; def call; end; end`
- I remove the Nilable from the sig

I also get the error if I replace the definition of Dummy with

```
Class.new do
  def call
  end 
end
```
  

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23typed%3A%20true%0Aclass%20Dummy%0Aend%0ADummy.class_eval%20do%0A%20%20def%20call%0A%20%20end%0Aend%0A%0Aextend%20T%3A%3ASig%0Asig%20%7B%20params%28block%3A%20T.nilable%28T.proc.params%28record%3A%20Integer%29.void%29%29.void%20%7D%20%20%20%0Adef%20foo%28%26block%29%20%0A%20%20T.must%28block%29.call%281%29%0Aend%0A%0Afoo%20%7B%7Cvalue%7C%20value%7D%0A)

```ruby
#typed: true
class Dummy
end
Dummy.class_eval do
  def call
  end
end

extend T::Sig
sig { params(block: T.nilable(T.proc.params(record: Integer).void)).void }   
def foo(&block) 
  T.must(block).call(1)
end

foo {|value| value}

```

#### Observed output

```
editor.rb:15: This code is unreachable https://srb.help/7006
    15 |foo {|value| value}
              ^^^^^
    editor.rb:15: This expression always raises or can never be computed
    15 |foo {|value| value}
        ^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

- - -

**Comment by jez** [comment] 2022-10-02 23:42
Duplicate of #3609

**Closed** 2022-10-03 00:28 UTC
