### ISSUE TITLE
Incorrectly throwing unreachable code error (#7006)

### ISSUE THREAD

**Issue by parthingle** [sorbet/sorbet#2987] opened 2020-05-08 04:25 UTC
**Input**
[See on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20B).returns(T%3A%3ABoolean)%7D%0A%20%20def%20broken(x)%0A%20%20%20%20x.nil%3F%20%7C%7C%20x.test.nil%3F%20%7C%7C%20T.must(x.test)%20%3E%200%0A%20%20end%0A%0A%20%20sig%20%7Bparams(x%3A%20B).returns(T%3A%3ABoolean)%7D%0A%20%20def%20fixed(x)%0A%20%20%20%20return%20true%20if%20x.nil%3F%0A%20%20%20%20x.test.nil%3F%20%7C%7C%20x.test%20%3E%200%0A%20%20end%0Aend%0A%0Aclass%20B%0A%20%20def%20test%0A%20%20end%0Aend%0A%0A%0A)
```
# typed: true
class A
  extend T::Sig

  sig {params(x: B).returns(T::Boolean)}
  def broken(x)
    x.nil? || x.test.nil? || T.must(x.test) > 0
  end

  sig {params(x: B).returns(T::Boolean)}
  def fixed(x)
    return true if x.nil?
    x.test.nil? || x.test > 0
  end
end

class B
  def test
  end
end



```

In the function `broken` input x of type B, it is completely logical for the conditional to yield `true` at any point before we reach `T.must(x.test)`, but Sorbet says the first two expressions are unreachable. 

```
editor.rb:7: This code is unreachable https://srb.help/7006
     7 |    x.nil? || x.test.nil? || T.must(x.test) > 0
            ^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

**Expected Behavior**
This should not be a problem. For now I've gotten around the problem by refactoring the code (`def fixed`)

You can reproduce this error with any compound conditional of a similar structure

**Comment by DarkDimius** [comment] 2020-05-08 06:36
This is a confusing error. What it means is that `x.nil?` is never true and thus first component of `||` is redundant. But the way it does it is super confusing.

Closing as duplicate of https://github.com/sorbet/sorbet/issues/820 as they are the same fundamentally

**Closed by DarkDimius** 2020-05-08 06:36 UTC
