### ISSUE TITLE
Static checker does not register T::Struct props of T::Hash[<tuple>, anything]

### ISSUE THREAD

**Issue by zanemiller-stripe** [sorbet/sorbet#2915] opened 2020-04-21 23:55 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%20%3C%20T%3A%3AStruct%0A%20%20prop%20%3Afoo%2C%20T%3A%3AHash%5B%5BString%2C%20String%5D%2C%20String%5D%2C%20default%3A%20%7B%7D%0Aend%0A%0AA.new.foo%0A)

```ruby
# typed: true
class A < T::Struct
  prop :foo, T::Hash[[String, String], String], default: {}
end

A.new.foo
```

#### Observed output

```
editor.rb:6: Method foo does not exist on A https://srb.help/7003
     6 |A.new.foo
        ^^^^^^^^^
Errors: 1
```

At runtime this works as expected:

```ruby
# typed: true
class A < T::Struct
  prop :foo, T::Hash[[String, String], String], default: {}
end

A.new.foo # => {}
```

#### Expected behavior

The static checker should not error on this case.

- - -

**Comment by trevor-stripe** [comment] 2020-04-22 20:08
The issue is the key to the hash. Does it have to be a tuple, or could you make a different type?

https://github.com/sorbet/sorbet/issues/1991

**Comment by zanemiller-stripe** [comment] 2020-04-22 20:12
I can work around it, just wanted to report as it fails in a pretty confusing way.

**Comment by Morriar** [comment] 2021-04-30 20:49
Duplicate of https://github.com/sorbet/sorbet/issues/1991

**Closed by Morriar** 2021-04-30 20:49 UTC
Labels: bug
