### ISSUE TITLE
Check method compatibility between super- and subclasses

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#69] opened 2019-01-16 22:12 UTC
Subclasses that override a superclass's method should be required to use a compatible signature.

Comments:
21/Dec/18 10:49 PM;jamesiry;This ticket has been closed as won't do because it hasn't been updated in over a year. If you feel strongly about it please contact @jamesiry-stripe

Originally reported by @nelhage-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-325

**Comment by jez** [comment] 2022-04-24 22:56
Duplicate of #2652

**Closed by jez** 2022-04-24 22:56 UTC
