### ISSUE TITLE
Loss of information when combining method-level and class-level generics

### ISSUE THREAD

**Issue by djudd-stripe** [sorbet/sorbet#3558] opened 2020-10-22 18:36 UTC
#### Input
First example:

https://sorbet.run/#extend%20T%3A%3ASig%0A%0Aclass%20Burrito%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Value%20%3D%20type_member%0Aend%0A%0Asig%20do%0A%20%20type_parameters(%3AT)%0A%20%20.params(%0A%20%20%20%20blk%3A%20T.proc.returns(Burrito%5BT.type_parameter(%3AT)%5D)%0A%20%20)%0A%20%20.returns(Burrito%5BT.type_parameter(%3AT)%5D)%0Aend%0Adef%20unwrap(blk)%0A%20%20blk.call%0Aend%0A%0Av%20%3D%20T.cast(nil%2C%20Burrito%5BInteger%5D)%20%23%20hack%20to%20demonstrate%0Ax%20%3D%20unwrap(-%3E%20%7Bv%7D)%0AT.reveal_type(x)%20%23%20should%20be%20Burrito%5BInteger%5D%2C%20is%20Burrito%5BT.untyped%5D

```ruby
class Burrito
  extend T::Generic
  Value = type_member
end

sig do
  type_parameters(:T)
  .params(
    blk: T.proc.returns(Burrito[T.type_parameter(:T)])
  )
  .returns(Burrito[T.type_parameter(:T)])
end
def unwrap(blk)
  blk.call
end

v = T.cast(nil, Burrito[Integer]) # hack to demonstrate
x = unwrap(-> {v})
T.reveal_type(x) # should be Burrito[Integer], is Burrito[T.untyped]
```

Second example:

https://sorbet.run/#extend%20T%3A%3ASig%0A%0Aclass%20Burrito%0A%20%20extend%20T%3A%3AGeneric%0A%20%20Value%20%3D%20type_member%0Aend%0A%0Asig%20do%0A%20%20type_parameters(%3AT)%0A%20%20.params(%0A%20%20%20%20blk%3A%20T.proc.returns(T.type_parameter(%3AT))%0A%20%20)%0A%20%20.returns(Burrito%5BT.type_parameter(%3AT)%5D)%0Aend%0Adef%20wrap(blk)%0A%20%20T.unsafe(blk.call)%20%23%20hack%20to%20demonstrate%0Aend%0A%0Ax%20%3D%20wrap(-%3E%20%7B1%7D)%0AT.reveal_type(x)%20%23%20should%20be%20Burrito%5BInteger%5D%2C%20is%20Burrito%5BT.untyped%5D

```ruby
class Burrito
  extend T::Generic
  Value = type_member
end

sig do
  type_parameters(:T)
  .params(
    blk: T.proc.returns(T.type_parameter(:T))
  )
  .returns(Burrito[T.type_parameter(:T)])
end
def wrap(blk)
  T.unsafe(blk.call) # hack to demonstrate
end

x = wrap(-> {1})
T.reveal_type(x) # should be Burrito[Integer], is Burrito[T.untyped]
```

#### Observed output
First example:
```
editor.rb:21: Revealed type: Burrito[T.untyped] https://srb.help/7014
    21 |T.reveal_type(x) # should be Burrito[Integer], is Burrito[T.untyped]
        ^^^^^^^^^^^^^^^^
  From:
    editor.rb:20:
    20 |x = unwrap(-> {v})
            ^^^^^^^^^^^^^^
Errors: 1
```

Second example:
```
editor.rb:20: Revealed type: Burrito[T.untyped] https://srb.help/7014
    20 |T.reveal_type(x) # should be Burrito[Integer], is Burrito[T.untyped]
        ^^^^^^^^^^^^^^^^
  From:
    editor.rb:19:
    19 |x = wrap(-> {1})
            ^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

We should preserve the type information from the proc's return value into the function's return value.

Possibly related to https://github.com/sorbet/sorbet/issues/3461 (which shows up if you make the methods take `&blk` instead of lambdas/procs) and/or https://github.com/sorbet/sorbet/issues/38

**Comment by itarato** [comment] 2021-03-11 13:59
Possibly even simpler example ([link](https://sorbet.run/#%23typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aproc%20%3D%20-%3E%20%7B%20T.let(1%2C%20Integer)%20%7D%0AT.reveal_type(proc))):

```ruby
#typed: true
extend T::Sig

proc = -> { T.let(1, Integer) }
T.reveal_type(proc)
```

Out:

```
editor.rb:5: Revealed type: T.proc.returns(T.untyped) https://srb.help/7014
     5 |T.reveal_type(proc)
        ^^^^^^^^^^^^^^^^^^^
  Got T.proc.returns(T.untyped) originating from:
    editor.rb:4:
     4 |proc = -> { T.let(1, Integer) }
               ^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

**Comment by djudd-stripe** [comment] 2021-03-11 17:19
@itarato I suspect that's unrelated - I think that's just a limitation of type inference, which is purely local in Sorbet. I know it won't infer method return types, so I'm not surprised it won't infer proc return types.

**Comment by jez** [comment] 2022-07-15 06:22
It is as itarato mentions; this is a duplicate of #4149. There's nothing particularly wrong about generics here, it's just a case of `unwrap` being given `T.untyped` as the input, and therefore the constraint solution produces `T.untyped`.

**Closed by jez** 2022-07-15 06:22 UTC
Labels: bug
