### ISSUE TITLE
Have some way to model a Class that includes some Module

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#67] opened 2019-01-16 22:10 UTC
https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20A%0Aend%0A%0Aclass%20B%0A%20%20include%20A%0Aend%0A%0Aextend%20T%3A%3AHelpers%0A%0Asig.returns(T.all(T.class_of(A)%2C%20Class))%0Adef%20foo%0A%20%20B%0Aend

This is being hit here: https://git.corp.stripe.com/stripe-internal/pay-server/commit/f5c354f91c82#diff-64e8c168d966b0ba7a378b51b1ec3b6eR13

Originally reported by @pt-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1106

**Comment by karmakaze** [comment] 2021-07-08 20:48
I was trying to understand this issue in relation to one I was reporting #4329

This one could be [simplified to the following](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20A%0Aend%0A%0Aclass%20B%0A%20%20include%20A%0Aend%0A%0Asig%20%7B%20returns(T.class_of(A))%20%7D%0Adef%20foo%0A%20%20B%0Aend):
```
# typed: true
extend T::Sig

module A
end

class B
  include A
end

sig { returns(T.class_of(A)) }
def foo
  B
end
```
resulting in
```
editor.rb:13: Expected T.class_of(A) but found T.class_of(B) for method result type https://srb.help/7005
    13 |  B
          ^
  Expected T.class_of(A) for result type of method foo:
    editor.rb:12:
    12 |def foo
        ^^^^^^^
  Got T.class_of(B) originating from:
    editor.rb:13:
    13 |  B
          ^
Errors: 1
```
but is it showing the same problem that's being reported by this issue or a different one?

**Comment by jez** [comment] 2022-08-06 19:57
This is a dupe of #62

**Closed by jez** 2022-08-06 19:57 UTC
Labels: hard
