### ISSUE TITLE
`srb tc` crashes with segmentation fault error

### ISSUE THREAD

**Issue by st0012** [sorbet/sorbet#6569] opened 2022-11-17 16:03 UTC
I can't reproduce this issue on sorbet.run, so I created a [repo](https://github.com/st0012/sorbet-issue) for reproduction. The main script looks like this:

```rb
# typed: true
# frozen_string_literal: true

class Foo
  extend T::Generic

  X = type_member { { fixed: Object } }
end

class Bar < Foo
  X = type_template { { fixed: Object } }
end
```

`Gemfile`

```rb
# frozen_string_literal: true

source "https://rubygems.org"

gem "tapioca", require: false
gem "sorbet-static-and-runtime", "0.5.10560"
```

On [sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%23%20frozen_string_literal%3A%20true%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20X%20%3D%20type_member%20%7B%20%7B%20fixed%3A%20Object%20%7D%20%7D%0Aend%0A%0Aclass%20Bar%20%3C%20Foo%0A%20%20X%20%3D%20type_template%20%7B%20%7B%20fixed%3A%20Object%20%7D%20%7D%0Aend), it passes type-checking. 

But when I run it locally, it crashes:

```
$ bundle exec srb tc
/Users/hung-wulo/.gem/ruby/3.1.2/gems/sorbet-0.5.10560/bin/srb: line 46: 17653 Segmentation fault: 11  "${sorbet}" "${args[@]}"
```

#### Expected behavior

It doesn't crash.

**Comment by jez** [comment] 2022-11-17 16:55
Duplicate of #5719

**Closed by jez** 2022-11-17 16:55 UTC
Labels: bug, unconfirmed
