### ISSUE TITLE
Block parameters lose information about type_parameters

### ISSUE THREAD

**Issue by vinistock** [sorbet/sorbet#4744] opened 2021-10-18 15:59 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters%28%3AItem%29.params%28%0A%20%20%20%20list%3A%20T%3A%3AArray%5BT.type_parameter%28%3AItem%29%5D%2C%0A%20%20%20%20block%3A%20T.proc.params%28arg0%3A%20T.type_parameter%28%3AItem%29%29.void%0A%20%20%29.void%0Aend%0Adef%20foo%28list%2C%20%26block%29%0Aend%0A%0Afoo%28%5B1%2C%202%2C%203%5D%29%20do%20%7Citem%7C%0A%20%20T.reveal_type%28item%29%0Aend%0A)

```ruby
# typed: true

extend T::Sig

sig do
  type_parameters(:Item).params(
    list: T::Array[T.type_parameter(:Item)],
    block: T.proc.params(arg0: T.type_parameter(:Item)).void
  ).void
end
def foo(list, &block)
end

foo([1, 2, 3]) do |item|
  T.reveal_type(item)
end

```

#### Observed output

```
editor.rb:15: Revealed type: <top> https://srb.help/7014
    15 |  T.reveal_type(item)
          ^^^^^^^^^^^^^^^^^^^
  Got <top> originating from:
    editor.rb:14:
    14 |foo([1, 2, 3]) do |item|
                           ^^^^
Errors: 1
```

#### Expected behavior

The type of the block parameter `item` in this case should be integer. The funny thing is that hovering over the `foo` invocation displays the correct type for the block's `arg0`, but for some reason inside the block the type information is lost.

**Comment by jez** [comment] 2021-10-18 17:34
Thanks. This is a dupe of #1098 (hard) but the example is good. I'm going to merge it into there for an extra test case.

**Closed as completed by jez** 2021-10-18 17:34 UTC
Labels: bug, unconfirmed
