### ISSUE TITLE
Bug with parameter of type_template

### ISSUE THREAD

**Issue by benbuckman-stripe** [sorbet/sorbet#333] opened 2019-04-22 17:46 UTC
https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20View%0A%20%20extend%20T%3A%3AHelpers%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20abstract!%0A%0A%20%20ModelInstance%20%3D%20type_template%0A%20%20ViewInstance%20%3D%20type_template%0A%0A%20%20sig%20%7Bparams(model%3A%20ModelInstance).void%7D%0A%20%20def%20initialize(model)%3B%20end%0A%0A%20%20sig%20%7Bparams(model%3A%20ModelInstance).returns(ViewInstance)%7D%0A%20%20def%20self.create(model)%0A%20%20%20%20new(model)%0A%20%20end%0Aend%0A%0Aclass%20MyView%20%3C%20View%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20ModelInstance%20%3D%20type_template(fixed%3A%20MyView)%0A%20%20ViewInstance%20%3D%20type_template(fixed%3A%20self)%0Aend%0A

This raises an error,
> `T.class_of(View)::ModelInstance` doesn't match `T.class_of(View)::ModelInstance`

The two sides of this comparison are the same, so they should match.

**Comment by DarkDimius** [comment] 2019-10-09 19:32
I believe this is a duplicate of a bug that was already fixed.
While this bug has been reported as a use site bug, the actual error is that `initialize` sig shouldn't have been permitted as it refers to attached classes type parameter.

**Closed by DarkDimius** 2019-10-09 19:32 UTC
