### ISSUE TITLE
Return value of incorrect type from a method is not reported

### ISSUE THREAD

**Issue by Slike9** [sorbet/sorbet#6358] opened 2022-09-09 07:01 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20returns%28String%29%20%7D%0Adef%20foo%0A%20%20if%20cond%0A%20%20%20%2010%20%23%20%3C%3C%3C%20Value%20of%20incorrect%20type%0A%20%20else%0A%20%20%20%20T.unsafe%28nil%29%0A%20%20end%0Aend%0A%0Asig%20%7B%20returns%28T%3A%3ABoolean%29%20%7D%0Adef%20cond%0A%20%20true%0Aend)

```ruby
# typed: true
extend T::Sig

sig { returns(String) }
def foo
  if cond
    10 # <<< Value of incorrect type
  else
    T.unsafe(nil)
  end
end

sig { returns(T::Boolean) }
def cond
  true
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

```
Expected String but found Integer(10) for method result type https://srb.help/7005
```

- - -

* It works correctly with explicit `return` :  [→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20returns%28String%29%20%7D%0Adef%20foo%0A%20%20if%20cond%0A%20%20%20%20return%2010%20%23%20%3C%3C%3C%20Value%20of%20incorrect%20type%0A%20%20else%0A%20%20%20%20T.unsafe%28nil%29%0A%20%20end%0Aend%0A%0Asig%20%7B%20returns%28T%3A%3ABoolean%29%20%7D%0Adef%20cond%0A%20%20true%0Aend)
* It works correctly if `else` branch returns a typed value (not T.untyped):  [→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20returns%28String%29%20%7D%0Adef%20foo%0A%20%20if%20cond%0A%20%20%20%2010%20%23%20%3C%3C%3C%20Value%20of%20incorrect%20type%0A%20%20else%0A%20%20%20%20%22str%22%0A%20%20end%0Aend%0A%0Asig%20%7B%20returns%28T%3A%3ABoolean%29%20%7D%0Adef%20cond%0A%20%20true%0Aend)
* It works correctly if `else` branch is omitted: [→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20returns%28T.nilable%28String%29%29%20%7D%0Adef%20foo%0A%20%20if%20cond%0A%20%20%20%2010%20%23%20%3C%3C%3C%20Value%20of%20incorrect%20type%0A%20%20end%0Aend%0A%0Asig%20%7B%20returns%28T%3A%3ABoolean%29%20%7D%0Adef%20cond%0A%20%20true%0Aend)

**Comment by jez** [comment] 2022-09-09 13:27
Duplicate of #4129

**Closed by jez** 2022-09-09 13:27 UTC
Labels: bug, unconfirmed
