### ISSUE TITLE
Potential bug in sorting basic blocks

### ISSUE THREAD

**Issue by marianosimone-stripe** [sorbet/sorbet#3211] opened 2020-06-18 21:17 UTC
#### Input

```ruby
my_flag = true
number = T.let(0, Integer)
while my_flag
  if my_flag
    break
  end
end
T.reveal_type(number)
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20'strict'%0A%0Amy_flag%20%3D%20true%0Anumber%20%3D%20T.let(0%2C%20Integer)%0Awhile%20my_flag%0A%20%20if%20my_flag%0A%20%20%20%20break%0A%20%20end%0Aend%0AT.reveal_type(number))

#### Observed output

```
T.nilable(Integer)
```

#### Expected behavior

`Integer`

**Comment by DarkDimius** [comment] 2020-06-18 21:18
It's not a bug per-se as type is correct(more general), but it could have been better, thus marking as "enchancement"

**Comment by marianosimone** [comment] 2020-06-27 00:27
Doesn't this look like https://github.com/sorbet/sorbet/issues/96?

**Comment by jez** [comment] 2021-05-21 23:22
Dupe of #96

**Closed by jez** 2021-05-21 23:22 UTC
Labels: enhancement
