### ISSUE TITLE
Confusing error on && with always true left operand

### ISSUE THREAD

**Issue by tanin47** [sorbet/sorbet#2633] opened 2020-02-10 05:54 UTC
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20params(x%3A%20Integer%2C%20y%3A%20Integer).void%0Aend%0Adef%20main(x%2C%20y)%0A%20%20if%20x%20%26%26%20y%0A%20%20%20%20puts%20%22Hello%22%0A%20%20end%0Aend)

```ruby
# typed: strict

extend T::Sig

sig do
  params(x: Integer, y: Integer).void
end
def main(x, y)
  if x && y
    puts "Hello"
  end
end
```

#### Observed output

```
editor.rb:9: This code is unreachable https://srb.help/7006
     9 |  if x && y
             ^
Errors: 1
```

#### Expected behavior

In Ruby, using Integer as a condition is confusing because `0` is interpreted as `true`.

It's great that Sorbet prevents that. However, the error message should have been clearer.

Thank you.

**Comment by DarkDimius** [comment] 2020-02-10 18:26
Thank you, this is a valid improvement suggestion, but a duplicate of 
https://github.com/sorbet/sorbet/issues/820.

**Closed by DarkDimius** 2020-02-10 18:26 UTC
Labels: bug, unconfirmed
